Adds Linked wikis
EveripediaNetwork/ep-ui pull request #1021
Opened 2022-12-22 11:26 UTC by Royal-lobster

related to https://github.com/EveripediaNetwork/issues/issues/930

### [DRAFT]

2023-01-05 14:57 UTC, Simplypheyie96 approved these changes
it looks great. 
I assume that there is a limit to the number of linked wikis that can be added right? @Royal-lobster 
Or maybe a scroll bar inside the modal for when the content gets bigger.

2023-01-05 15:05 UTC, Royal-lobster commented
> it looks great. I assume that there is a limit to the number of linked wikis that can be added right? @Royal-lobster Or maybe a scroll bar inside the modal for when the content gets bigger.

yes ! the modal is scrollable if the content inside gets longer.

2023-01-06 15:31 UTC, Adebesin-Cell approved these changes
LG 🚀

2023-01-06 16:08 UTC, Softdev1 requested changes
I think the prediction is not fetching the required names 
<img width="1153" alt="SCR-20230106-np5" src="https://user-images.githubusercontent.com/32770520/211051186-129d0d18-55c8-4ba6-844f-9f7a37108921.png">

2023-01-06 16:53 UTC, Royal-lobster commented
> I think the prediction is not fetching and it is not adding the required names <img alt="SCR-20230106-np5" width="1153" src="https://user-images.githubusercontent.com/32770520/211051186-129d0d18-55c8-4ba6-844f-9f7a37108921.png">

Thanks for the review ! now it should be fixed.

2023-01-06 20:00 UTC, kesar commented on src/components/Editor/EditorModals/EditWikiDetailsModal/LinkedWikisInput.tsx
> +const LinkedWikisInput = ({ wiki }: { wiki: Wiki }) => {
245 LoC component, another possible refactoring here 

Not needed to fix for merge 👍🏻

2023-01-06 20:04 UTC, kesar commented on src/components/Landing/HeroCard.tsx
> +              getWikiSummary(wiki, CARD_DETAILS_LENGTH as WikiSummarySize)}
cant you define CARD_DETAILS_LENGTH as WikiSummarySize on intialization? that would make it easier to read here

2023-01-06 20:05 UTC, kesar commented on src/components/Landing/TrendingWikis.tsx
> +              {wiki && getWikiSummary(wiki, 60 as WikiSummarySize)}
doesnt work fine 65 ? so you can use WikiSummarySize.Small ?

2023-01-07 10:02 UTC, Royal-lobster commented on src/components/Landing/TrendingWikis.tsx
> +              {wiki && getWikiSummary(wiki, 60 as WikiSummarySize)}
Oh yes i believe 65 will look fine. i will create a new commit for fix.

2023-01-07 10:03 UTC, Royal-lobster commented on src/components/Landing/HeroCard.tsx
> +              getWikiSummary(wiki, CARD_DETAILS_LENGTH as WikiSummarySize)}
Thanks ! will add a fix for this.

2023-01-09 16:34 UTC, merged