Fixes rank iteration
EveripediaNetwork/ep-ui pull request #1039
Opened 2023-01-09 14:26 UTC by Adebesin-Cell

Fixes rank iteration

Before:

<img width="955" alt="issue" src="https://user-images.githubusercontent.com/66301634/211330812-3c590227-d0a9-4e70-a03e-3261908d61b4.png">

After:

<img width="1440" alt="Screen Shot 2023-01-09 at 3 25 24 PM" src="https://user-images.githubusercontent.com/66301634/211331299-80e664e5-d641-40ca-ab82-d96fe81495b5.png">

fixes https://github.com/EveripediaNetwork/issues/issues/948

2023-01-09 14:42 UTC, Adebesin-Cell commented
I’ll increase the font sizes then. 👍

2023-01-09 23:57 UTC, Adebesin-Cell commented
@Simplypheyie96 I've adjusted the font sizes.

2023-01-10 08:12 UTC, Simplypheyie96 requested changes
The font size looks okay. 
Can't wait to finish the new ranking page. 
I think that would be so much more better.

also, why is the nft list not up to ten. It doesn't look good that way.
![image](https://user-images.githubusercontent.com/99387231/211496556-d8786bc2-a568-4eb3-a263-7402b60dfffb.png)

2023-01-10 08:24 UTC, Adebesin-Cell commented
> The font size looks okay. Can't wait to finish the new ranking page. I think that would be so much more better.
> 
> also, why is the nft list not up to ten. It doesn't look good that way. ![image](https://user-images.githubusercontent.com/99387231/211496556-d8786bc2-a568-4eb3-a263-7402b60dfffb.png)

Ashaka said the backend is filtering NFt wikis without a 24h volume. For the first page autoglyphs is an example of such nft wiki.

2023-01-10 08:43 UTC, Simplypheyie96 commented
> > The font size looks okay. Can't wait to finish the new ranking page. I think that would be so much more better.
> > also, why is the nft list not up to ten. It doesn't look good that way. ![image](https://user-images.githubusercontent.com/99387231/211496556-d8786bc2-a568-4eb3-a263-7402b60dfffb.png)
> 
> Ashaka said the backend is filtering NFt wikis without a 24h volume. For the first page autoglyphs is an example of such nft wiki.

hmmnn.
you can go ahead and merge then.

2023-01-10 08:49 UTC, Adebesin-Cell commented
Yeah, I think we’ll review more on that 🙂.

2023-01-10 09:21 UTC, Royal-lobster commented on src/components/Rank/InvalidRankCardItem.tsx
> +              fontSize={{ base: 'xs' }}
```suggestion
              fontSize="xs"
```
I think this is same as 'xs'

2023-01-10 09:21 UTC, Royal-lobster commented on src/components/Rank/InvalidRankCardItem.tsx
> +              <Text fontWeight="bold" fontSize={{ base: 'xs' }}>
```suggestion
              <Text fontWeight="bold" fontSize="xs" >
```
please check if it is same, if it is same we can directly use "xs".

2023-01-10 09:30 UTC, Adebesin-Cell commented on src/components/Rank/InvalidRankCardItem.tsx
> +              <Text fontWeight="bold" fontSize={{ base: 'xs' }}>
Alright, I’ll look into i!t.

2023-01-10 16:25 UTC, Adebesin-Cell commented
@Simplypheyie96 I think you can check now, we have the 10 rankings listed out properly.

2023-01-10 16:34 UTC, Softdev1 approved these changes

2023-01-10 16:34 UTC, merged

2023-01-10 17:56 UTC, Simplypheyie96 commented
> @Simplypheyie96 I think you can check now, we have the 10 rankings listed out properly.

good to go