cls issue fixed
EveripediaNetwork/ep-ui pull request #1041
Opened 2023-01-09 19:27 UTC by OleanjiKingCode

#Fixed CLS issue for wiki page

## Linked issues

 closes https://github.com/EveripediaNetwork/issues/issues/949

2023-01-09 19:30 UTC, kesar commented
i think its still showing closed / without content which moves the content

2023-01-09 19:37 UTC, OleanjiKingCode commented
> i think its still showing closed / without content which moves the content

Alright sir

2023-01-10 21:50 UTC, OleanjiKingCode commented
After a discussion with Srujan we decided to use next middleware to solve this

2023-01-15 16:55 UTC, kesar commented
> After a discussion with Srujan we decided to use next middleware to solve this

is there any PR about this?

2023-01-16 09:03 UTC, OleanjiKingCode commented
> 

We later concluded to use normal css to for it

2023-01-16 09:12 UTC, kesar commented
<img width="930" alt="Captura de pantalla 2023-01-16 a las 10 09 00" src="https://user-images.githubusercontent.com/1288106/212640367-d6b80509-20aa-43d2-9381-dae85d3f13cd.png">
<img width="984" alt="Captura de pantalla 2023-01-16 a las 10 09 06" src="https://user-images.githubusercontent.com/1288106/212640379-fe905e8e-3408-405f-9955-69405d47f98b.png">
<img width="987" alt="Captura de pantalla 2023-01-16 a las 10 09 09" src="https://user-images.githubusercontent.com/1288106/212640381-1c550a9e-678a-43f9-88d8-55335dcf76f7.png">


cool, lets make sure we address this as soon as possible. 


@Royal-lobster plz also review if there are other stuff that might be interfering on the CLS / LCP

2023-01-17 07:27 UTC, kesar commented
this pr has code commented please make sure pr is ready to review/merge

2023-01-17 07:28 UTC, kesar requested changes

2023-01-17 07:28 UTC, kesar commented on src/components/Admin/WikiEditorInsight/WikiEditorsInsight.tsx
> +    // eslint/no-unused-disable-next-line @typescript-eslint/no-explicit-any
this file hasnt changed so we wont need any new eslint rule

2023-01-17 07:29 UTC, kesar commented
can u provide a proof that the issue is solved? attach screenshots or some report

2023-01-17 08:55 UTC, OleanjiKingCode commented
Before :

![image](https://user-images.githubusercontent.com/75235148/212852976-7503fa28-7204-480b-954d-ece1119c5eac.png)


Now :  
![image](https://user-images.githubusercontent.com/75235148/212852577-fa346f31-0c41-4d40-a474-86e3629db4ea.png)

that's what i use to judge the layout shift

2023-01-17 09:06 UTC, kesar commented
> Before :
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/75235148/212852976-7503fa28-7204-480b-954d-ece1119c5eac.png)
> 
> 
> 
> 
> 
> Now :  
> 
> ![image](https://user-images.githubusercontent.com/75235148/212852577-fa346f31-0c41-4d40-a474-86e3629db4ea.png)
> 
> 
> 
> that's what i use to judge the layout shift
> 
> 
> 
> 

nice one 👍 lets fix the comments and merge 🚀🚀

2023-01-17 11:16 UTC, kesar approved these changes

2023-01-17 11:19 UTC, merged