first iteration of trending page section
EveripediaNetwork/ep-ui pull request #1049
Opened 2023-01-12 16:11 UTC by OleanjiKingCode

# Trending Page Section Remake

Before:
![image](https://user-images.githubusercontent.com/75235148/212119114-582e0deb-9efe-4a3e-825f-8f146e8806ba.png)

After :
![image](https://user-images.githubusercontent.com/75235148/212118243-2439fed8-8c6b-422f-b3d6-302d5b9fa79f.png)

- [ ] code refactoring
- [ ] remove comments
- [ ] responsive 

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/939

2023-01-13 07:18 UTC, Royal-lobster commented
@OleanjiKingCode This is clean ! 

small thing, The last card is not correctly aligned with rest

<img width="1338" alt="CleanShot 2023-01-13 at 12 46 36@2x" src="https://user-images.githubusercontent.com/52039218/212260272-a046bdcb-83ee-43ad-8e84-05ec8f10ca43.png">

2023-01-13 07:20 UTC, Royal-lobster approved these changes

2023-01-13 07:20 UTC, Royal-lobster commented on src/components/Landing/TrendingWikis.tsx
> +      <Flex
We can divide this component to an other file since it exceeded 600 lines

2023-01-14 07:00 UTC, OleanjiKingCode commented on src/components/Landing/TrendingWikis.tsx
> +      <Flex
yes, this is just the first i did yeah istill havent finished thanks tho :)

2023-01-14 07:06 UTC, Royal-lobster commented on src/components/Landing/TrendingWikis.tsx
> +      <Flex
Cool ! looks promising.

2023-01-15 16:26 UTC, Simplypheyie96 requested changes
please re-inspect figma for the last card, doesn't look good yet, then the dark mode is yet to be done and other breakpoints are broken.

2023-01-17 10:18 UTC, Softdev1 commented
@OleanjiKingCode  can you work on the raised review from @Simplypheyie96  and @Royal-lobster  so that this issue can be closed down. well-done

2023-01-18 07:15 UTC, Royal-lobster commented
@OleanjiKingCode looking good now ! one small thing, it misses out responsiveness for final 320 breakpoint. 

<img width="1173" alt="CleanShot 2023-01-18 at 12 43 03@2x" src="https://user-images.githubusercontent.com/52039218/213107198-38db72bd-f56b-4e21-8ef7-cb259b23752e.png">

2023-01-18 09:53 UTC, Simplypheyie96 commented
The card is a little larger than the rest of the other cards.
Also the color used for the created/created by section of the card should be gray50. currently the color is not correct.
It doesn't look great on the md breakpoint yet and the last card should be aligned left.
for mobile, the card should also be equal in size with the rest. 
@OleanjiKingCode

2023-01-19 10:48 UTC, Simplypheyie96 requested changes
this shouldn't be happening on the desktop view. the cards shouldn't break. the 3 should be on the same level.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/99387231/213421904-da5bd987-1cf0-48b2-aceb-ce9e947ee280.png">
the md breakpoint still have some issues with content spilling out of the cards, if there needs to be adjustment with design, do communicate the issue with me @OleanjiKingCode

2023-01-19 10:54 UTC, kesar commented
I would highly recommend remove the date icon. AFAIK there is not other places across the site we do that and those cards have already a lot of information to add an extra icon. Whenever we add a new visual we need to think why that's not in created on wiki page, or in activity cards and wiki cards.

I would probably suggest to get rid of a 10 words description which highly doubt its gonna add any meaningful information to the user to click. Probably its better to reduce image and keep just title  and a line after that author. Worth to see how visually are the two options. If you check the original cmc widgets they are pretty clean and lean in information.

cc: @Simplypheyie96

2023-01-19 11:18 UTC, Simplypheyie96 commented
> I would highly recommend remove the date icon. AFAIK there is not other places across the site we do that and those cards have already a lot of information to add an extra icon. Whenever we add a new visual we need to think why that's not in created on wiki page, or in activity cards and wiki cards.
> 
> I would probably suggest to get rid of a 10 words description which highly doubt its gonna add any meaningful information to the user to click. Probably its better to reduce image and keep just title and a line after that author. Worth to see how visually are the two options. If you check the original cmc widgets they are pretty clean and lean in information.
> 
> cc: @Simplypheyie96

The issue is that the cmc page has a marketcap info in the cards alongside just the tokens, a little image and the token symbol, so to make ours different, since ours is a wiki, and we don't have symbols or marketcap info to add, the cards were looking really weird and empty, hence the decision to make it look similar to the wiki cards with the editor and date edited and a line of wiki details didn't really give any details which is why there is two. 

Also on cmc, the last card contains info for their articles and community post, but since ours is still a wiki, i don't think we should have the last card different from the others since it doesn't look cohesive and designing it with a carousel differently from the others doesn't look great either since it is the same layout.
i will show examples of what i mean by this in a few mins.

2023-01-19 11:28 UTC, kesar commented
> to make it look similar to the wiki cards with the editor and date edited and a line of wiki details didn't really give any details which is why there is two

The problem is that there is not enough space for some of the data you want to hook, and we need to take decision on what to remove. We can't get same data in a wiki card w image, title, summary, editor & last edit than in a one row

For example, a row will look like 
Title: Otherside
Summary: "Otherside is a metaverse project launched by ..."

Do you think that summary will add any valuable information in order to decide to visit that wiki ? or we are adding that summary to look like a wiki card / to fill empty space?

We could try w perhaps removing editor & last time edit and try to see how it looks w a proper summary. But we need to reduce some of the content in that trending sections.


About the last carrousel, I agree it breaks the coherence a bit, but its a spot we might sell. Some sites reserve spaces like that one for google adwords or stuff like that, I guess its a tradeoff

2023-01-19 12:10 UTC, Simplypheyie96 commented
@kesar 
These are some of different iterations i came up with.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/99387231/213439206-d6eef89e-863d-472b-83e5-c106595d6dad.png">

<img width="995" alt="image" src="https://user-images.githubusercontent.com/99387231/213439288-819747f8-4f74-4455-a08f-2591e9fe25ae.png">

2023-01-19 16:24 UTC, Simplypheyie96 commented
@OleanjiKingCode we are going with this one 
Remember the last card will have a little animation where the cards keeps changing just like on cmc.
figma Link: https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.WIKI?node-id=14567%3A99660&t=RssuHq43rZBhziFa-11
<img width="773" alt="image" src="https://user-images.githubusercontent.com/99387231/213496403-94eeedfb-d5ee-4aca-b935-05f970e85868.png">

2023-01-19 16:36 UTC, OleanjiKingCode commented
Alright

2023-01-19 20:39 UTC, OleanjiKingCode commented
A video of the design implementation @Simplypheyie96  @kesar 
https://user-images.githubusercontent.com/75235148/213553420-562c34b1-00a2-4cc9-8a35-9ad842739cbc.mp4

2023-01-20 10:13 UTC, kesar commented
> A video of the design implementation @Simplypheyie96 @kesar https://user-images.githubusercontent.com/75235148/213553420-562c34b1-00a2-4cc9-8a35-9ad842739cbc.mp4

thx for the video, looks very promising 👍🏻

2023-01-20 10:17 UTC, Simplypheyie96 commented
> A video of the design implementation @Simplypheyie96 @kesar https://user-images.githubusercontent.com/75235148/213553420-562c34b1-00a2-4cc9-8a35-9ad842739cbc.mp4

Looks good!

2023-01-20 10:58 UTC, OleanjiKingCode commented
Alright I'll get the correct data for the other cards 🚀

2023-01-23 08:41 UTC, Simplypheyie96 commented
> I dont know what data to put for featured wikis @Simplypheyie96
@kesar

2023-01-23 08:55 UTC, kesar commented
the wikis that we show in homepage in hero + trending.. the ones that come from the api

2023-01-23 13:44 UTC, Softdev1 commented
for the featured wikis the data should be same with the wiki  on the hero session @kesar

2023-01-24 09:17 UTC, Simplypheyie96 requested changes
Great work.
Please get rid of unnecessary space in card for other breakpoints. The desktop bp cards have some space so the cards can be aligned. 
![image](https://user-images.githubusercontent.com/99387231/214252745-bb770dcd-d0c8-4f12-a86c-3365d62ebe13.png)

2023-01-24 14:26 UTC, Simplypheyie96 commented
@OleanjiKingCode Here is a loading state for the section
figma: https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.WIKI?node-id=14838%3A94316&t=bAM4ICbmGM6B2Ruu-11

![image](https://user-images.githubusercontent.com/99387231/214320355-6dea3210-de5b-431f-86bf-ab148e24cb8a.png)

2023-01-26 11:25 UTC, Simplypheyie96 approved these changes
Great work!

2023-01-26 11:26 UTC, Royal-lobster approved these changes

2023-01-26 13:32 UTC, Softdev1 approved these changes

2023-01-26 13:53 UTC, merged