Adds wiki subscribe button on wiki action bar
EveripediaNetwork/ep-ui pull request #1110
Opened 2023-02-01 17:08 UTC by Royal-lobster

# DRAFT

2023-02-01 17:28 UTC, kesar commented
mmm great idea!

2023-02-02 11:50 UTC, Simplypheyie96 approved these changes
It looks cool. can see you already implemented the inactive state.

@Softdev1 please create an issue for some tooltip guide/message for the inactive state buttons on wiki page.  so we can design and implement that.

2023-02-02 13:09 UTC, Adebesin-Cell requested changes

2023-02-02 13:09 UTC, Adebesin-Cell commented on src/components/Settings/Notification/SearchWikiNotifications.tsx
>    const router = useRouter()
Same with this file > 200, the useEventListener logic is used twice, on Navbar and here, we can move it into one common file and use.

2023-02-02 13:21 UTC, Royal-lobster commented on src/components/Notification/NotificationCard.tsx
>    const isWikiSubscribed = useIsWikiSubscribed(wikiId, userAddress)
Good catch ! I guess we can add this to a new issue cuz it is unrelated to this pr

2023-02-02 13:21 UTC, Royal-lobster commented on src/components/Settings/Notification/SearchWikiNotifications.tsx
>    const router = useRouter()
Same, We can address this in another refactoring pr

2023-02-02 13:24 UTC, Royal-lobster commented on src/components/About/AboutFeaturesCard.tsx
> +    _dark={{
Oh yes ! Will add a commit for this. Thanks!

2023-02-02 13:54 UTC, Adebesin-Cell commented on src/components/Notification/NotificationCard.tsx
>    const isWikiSubscribed = useIsWikiSubscribed(wikiId, userAddress)
Yeah 👍, @Softdev1 You can an issue to refactor the code on Notifications.

2023-02-02 14:00 UTC, Adebesin-Cell approved these changes
Awesome 🚀.

2023-02-02 14:10 UTC, Adebesin-Cell commented
> i would suggest to avoid the remove notification as a primary button in the dialog. We use primary colors when we want to guide user to take a decision. I dont think we want the user to unsubscribe after subscribe. 😅
> 
> does the button change if user is already subscribed?
> 
> also make sure it works for mobile (not big priority, but that can work at least) 👍👍

Haha 😅, yeah. Thanks for pointing that out @kesar.

2023-02-02 14:10 UTC, Royal-lobster commented
> 

Good point ! i'll change the unsubscribe to outline button instead i think that should work. Yes the button changes to "unsubscribe" when it is already subscribed. It works for mobile too !

2023-02-02 14:47 UTC, Adebesin-Cell commented
Great 👍.

2023-02-02 15:02 UTC, Softdev1 approved these changes

2023-02-02 15:02 UTC, merged