Fixes Careers Page
EveripediaNetwork/ep-ui pull request #1139
Opened 2023-02-07 18:15 UTC by Adebesin-Cell

Fixes Careers Page

links:
https://iq-wiki-git-fixes-careers-page-prediqt.vercel.app/careers

Screenshots:
![localhost_4000_careers](https://user-images.githubusercontent.com/66301634/217330749-f25ccfd0-a494-4558-824e-bccb73304b2a.png)

fixes https://github.com/EveripediaNetwork/issues/issues/1024

2023-02-07 18:32 UTC, kesar commented on src/data/CareersData.ts
> +      'Are you an AI Developer with an insatiable appetite for a challenge? Then this job opportunity is for you! We are looking for an ambitious and creative AI Developer to join our team and help s
make sure it support line jumps

2023-02-07 18:33 UTC, kesar commented on src/data/CareersData.ts
> +    id: 1,
i dont think we need ids, we can use key in the react loop

2023-02-07 18:37 UTC, Adebesin-Cell commented on src/data/CareersData.ts
> +    id: 1,
Noted @kesar. I'll remove it.

2023-02-07 18:37 UTC, Adebesin-Cell commented on src/data/CareersData.ts
> +      'Are you an AI Developer with an insatiable appetite for a challenge? Then this job opportunity is for you! We are looking for an ambitious and creative AI Developer to join our team and help s
I'll investigate that @kesar.

2023-02-07 18:37 UTC, kesar commented
do we need a 1900x900 images for the hero? and dont we have those heros somewhere already?

also yarn.lock is updated without any new package added, so this is most likely something coming from other previous PR. probably worth revert yarn

2023-02-07 18:46 UTC, Adebesin-Cell commented
> do we need a 1900x900 images for the hero? and dont we have those heros somewhere already?
> 
> we have similar / same brainies bg (that i really love :P) in homepage and as header in profile page if user didnt setup one. I think we should try to reuse them if possible
> 
> also yarn.lock is updated without any new package added, so this is most likely something coming from other previous PR. probably worth revert yarn

Okay @kesar, I'll add the fix now. I'll also revert yarn.

2023-02-07 19:09 UTC, Adebesin-Cell commented
> code looks great now. kudos! the only missing things are linting & line jumping in job texts 👍🏻

Thanks @kesar. I'll look into how to implement line jumps and fix the lints.

2023-02-07 19:11 UTC, Softdev1 commented
Well done @Adebesin-Cell  looks great

2023-02-07 19:58 UTC, Simplypheyie96 requested changes
- The card in dark mode should be in gray700
![image](https://user-images.githubusercontent.com/99387231/217350229-f9870d49-d721-41d4-99c7-bca6de05ae4f.png)

- we're hiring tag is missing in footer
![image](https://user-images.githubusercontent.com/99387231/217350433-b2fc9782-c736-41e3-b4d0-f8bc9b20653f.png)

Brainies background not visible in dark mode

2023-02-08 11:40 UTC, Simplypheyie96 approved these changes

2023-02-08 11:44 UTC, Royal-lobster approved these changes

2023-02-08 11:53 UTC, merged