wiki editor page code refactor
EveripediaNetwork/ep-ui pull request #1147
Opened 2023-02-12 20:45 UTC by OleanjiKingCode

# Code refactor for WikiEditorsInsightTable

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1026

2023-02-13 19:28 UTC, Adebesin-Cell requested changes
I think we can break down some of the files logic into folders since the insight table is >200+ still, more like components/admin/utils or hooks as needed.

2023-02-16 13:19 UTC, Royal-lobster commented on src/components/Admin/WikiEditorInsight/WikiEditorFunctions.tsx
> +
@Adebesin-Cell  This can be in types folder

2023-02-16 13:19 UTC, Royal-lobster commented on src/components/Admin/WikiEditorInsight/WikiEditorFunctions.tsx
> +}
And this can be under AdminUtils folder.

2023-02-16 13:19 UTC, Royal-lobster commented on src/components/Admin/WikiEditorInsight/WikiEditorsInsight.tsx
> +  const [allowNext, setAllowNext] = useState<boolean>(true)
useState can infer from initial value ! so don't need to pass the type in the generic

```suggestion
  const [activatePrevious, setActivatePrevious] = useState(false)
  const [allowNext, setAllowNext] = useState(true)
```

2023-02-16 13:36 UTC, Adebesin-Cell commented on src/components/Admin/WikiEditorInsight/WikiEditorFunctions.tsx
> +}
Noted @Royal-lobster, I'll fix that.

2023-02-17 09:22 UTC, Adebesin-Cell approved these changes

2023-02-17 10:13 UTC, Royal-lobster approved these changes

2023-02-17 10:14 UTC, merged