Content feedback
EveripediaNetwork/ep-ui pull request #1170
Opened 2023-02-20 14:14 UTC by OleanjiKingCode

# Wiki Feedback for Users

## How should this be tested?

UI

- ## Question
![image](https://user-images.githubusercontent.com/75235148/220130546-ee7aa837-b2dc-45b1-8c85-94d0dee72393.png)
![image](https://user-images.githubusercontent.com/75235148/220130560-408c647e-1eff-430f-a727-77df066a050f.png)

- ## Feedback

![image](https://user-images.githubusercontent.com/75235148/220130654-cbf0fcf8-0864-44bb-af10-5701972a43bb.png)
![image](https://user-images.githubusercontent.com/75235148/220130664-17dc7c4d-8927-4457-babb-d80e83fd1eb1.png)

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/1007

2023-02-20 14:37 UTC, Simplypheyie96 approved these changes

2023-02-21 02:16 UTC, Softdev1 approved these changes
awesome

2023-02-21 08:55 UTC, AshakaE requested changes

2023-02-21 08:55 UTC, AshakaE commented on src/components/Wiki/WikiPage/InsightComponents/ContentFeedback.tsx
> +  userId: string | undefined
- [ ] I suggest we don't send undefined for the users, feedback should only be possible for logged in users

2023-02-21 09:01 UTC, OleanjiKingCode commented on src/components/Wiki/WikiPage/InsightComponents/ContentFeedback.tsx
> +  userId: string | undefined
Alright

2023-02-21 09:17 UTC, kesar commented on src/components/Wiki/WikiPage/InsightComponents/ContentFeedback.tsx
> +  userId: string | undefined
we barely have registered users, it would defeat the purpose of knowing if content is good or bad.

we should allow anonymous users until we have enough userbase

2023-02-21 09:21 UTC, OleanjiKingCode commented on src/components/Wiki/WikiPage/InsightComponents/ContentFeedback.tsx
> +  userId: string | undefined
@kesar using without db that makes users (anonymous or not ) like more than once

2023-02-21 09:34 UTC, AshakaE commented on src/components/Wiki/WikiPage/InsightComponents/ContentFeedback.tsx
> +  userId: string | undefined
I think we'll need to store some information about the feedback to prevent spamming

2023-02-21 09:35 UTC, OleanjiKingCode commented on src/components/Wiki/WikiPage/InsightComponents/ContentFeedback.tsx
> +  userId: string | undefined
yh

2023-02-21 09:35 UTC, AshakaE approved these changes

2023-02-21 09:39 UTC, merged

2023-02-21 10:06 UTC, kesar commented on src/components/Wiki/WikiPage/InsightComponents/ContentFeedback.tsx
> +  userId: string | undefined
api should do something similar to what we have for views and prevent that

2023-02-21 10:15 UTC, AshakaE commented on src/components/Wiki/WikiPage/InsightComponents/ContentFeedback.tsx
> +  userId: string | undefined
thought as much, I just wanted to be sure 👍