Event feature
EveripediaNetwork/ep-ui pull request #1211
Opened 2023-02-28 21:21 UTC by Adebesin-Cell

Event feature

closes https://github.com/EveripediaNetwork/issues/issues/986

2023-03-06 12:26 UTC, Softdev1 commented
Please review the title section it seems it should be read-only cos one can't type there @Adebesin-Cell

2023-03-06 12:31 UTC, Adebesin-Cell commented
> Please review the title section it seems it should be read-only cos one can't type there @Adebesin-Cell

Hi @Softdev1, for the first events, the check is to have a Date of Creation or Date of Birth as the first title of the event depending on the wiki category. So it's readonly on first inout, but editable after the first inputs 👍

2023-03-06 12:51 UTC, Softdev1 commented
I will have it tested again and revert back to you @Adebesin-Cell

2023-03-06 12:52 UTC, Adebesin-Cell commented
> I will have it tested again and revert back to you @Adebesin-Cell

Sweet! 🙂

2023-03-06 13:31 UTC, Simplypheyie96 requested changes
-This should have a default text guide in it, like (enter event title), it will be confusing to see this
<img width="227" alt="image" src="https://user-images.githubusercontent.com/99387231/223123664-a4dd3895-5eae-422c-bbe5-09b49841fc63.png">

- let's use another date selector that would be more user-friendly. 

besides that, everything looks good

2023-03-07 08:51 UTC, Royal-lobster commented
<img width="392" alt="CleanShot 2023-03-07 at 14 20 01@2x" src="https://user-images.githubusercontent.com/52039218/223371296-7c3a1f84-76d3-4e23-867f-5a4beb3b0a42.png">

@Adebesin-Cell make this read only as you said previously and also add a tooltip with sentence saying like it cannot be changed

2023-03-07 08:54 UTC, Adebesin-Cell commented
> <img alt="CleanShot 2023-03-07 at 14 20 01@2x" width="392" src="https://user-images.githubusercontent.com/52039218/223371296-7c3a1f84-76d3-4e23-867f-5a4beb3b0a42.png">
> 
> @Adebesin-Cell make this read only as you said previously and also add a tooltip with sentence saying like it cannot be changed

Yeah, it's read only when the wiki doesn't have an event.

2023-03-07 09:11 UTC, Royal-lobster commented
![image](https://user-images.githubusercontent.com/52039218/223376237-06cb153b-e1c5-440c-bc3a-2527ad9015d6.png)

We also have to update the blocks changed when every events are updated. and also events page should be revalidated on backend as well

2023-03-07 09:13 UTC, Softdev1 commented
We might still need to wait and properly test this PR again so it will only get merged after it is properly tested and confirmed.
@Adebesin-Cell  you would need to sync up with @AshakaE  cos something which I gave you feedback are still not solved.

2023-03-07 09:15 UTC, Softdev1 commented
Also, when a change is made on any event, it should be captured in the wiki history page @AshakaE , currently, this is not happening.

2023-03-08 10:22 UTC, Royal-lobster approved these changes
Looks great ! we are good to merge after fixes !

2023-03-08 10:22 UTC, Royal-lobster commented on src/pages/wiki/[slug]/events.tsx
> +  }
looks like duplicate code, i think this can be fixed

2023-03-08 10:22 UTC, Royal-lobster commented on src/store/slices/wiki.slice.ts
> +      }
```suggestion
      const index = state.events ? state.events?.findIndex(e => e.date === date) : -1
```

2023-03-08 10:23 UTC, Adebesin-Cell commented on src/pages/wiki/[slug]/events.tsx
> +  }
I'll fix this.

2023-03-08 10:24 UTC, Adebesin-Cell commented on src/pages/wiki/[slug]/events.tsx
> +  }
I think if the wiki doesn't exist we should use a no-wiki component.

2023-03-08 10:25 UTC, Royal-lobster commented on src/pages/wiki/[slug]/events.tsx
> +  }
i believe it should simply go to 404. or may be the wiki page since it has create wiki action

2023-03-08 12:57 UTC, Royal-lobster approved these changes

2023-03-08 13:20 UTC, Adebesin-Cell commented
@Royal-lobster @Softdev1 Good to merge?

2023-03-08 13:22 UTC, Royal-lobster commented
Yep lets get this merged !

2023-03-08 13:23 UTC, merged