Refactoring admin
EveripediaNetwork/ep-ui pull request #1222
Opened 2023-03-02 20:48 UTC by OleanjiKingCode

#Refactoring Admin Files 

Refactoring admin page large files to meet up with code climate standards

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1082

2023-03-07 10:09 UTC, Adebesin-Cell reviewed
Apart from those, it's good. Great work @OleanjiKingCode 👍

2023-03-07 10:09 UTC, Adebesin-Cell commented on .codeclimate.yml
> +      threshold: 240
Cool, but the codeclimate is not active on the repo at the moment.

2023-03-07 10:09 UTC, Adebesin-Cell commented on src/components/Admin/WikiCreatedInsight/GetWikisComponent.tsx
> +          py={{ base: 3, lg: 3 }}
```suggestion
          py={3}
```

2023-03-07 10:09 UTC, Adebesin-Cell commented on src/components/Admin/WikiCreatedInsight/GetWikisComponent.tsx
> +                      {/* eslint-disable no-nested-ternary */}
You handle the logic in a function and return the values.

2023-03-07 10:09 UTC, Adebesin-Cell commented on src/components/Admin/WikiCreatedInsight/WikiCreatedActionBar.tsx
> +  const ApplyFilterItems = (e: any) => {
```suggestion
  const ApplyFilterItems = (e: React.FormEvent<HTMLFormElement>) => {
```
You can remove the eslint disabled, let's avoid using any type 👍.

2023-03-07 10:09 UTC, Adebesin-Cell commented on src/components/Admin/WikiCreatedInsight/WikiCreatedActionBar.tsx
> +                _dark={{ borderColor: '#2c323d' }}
You can move this to ``semantic-tokens.ts`` file

2023-03-07 10:09 UTC, Adebesin-Cell commented on src/components/Admin/WikiCreatedInsight/WikisTable.tsx
> +                  color="#718096"
I think it's fine to inherit the colors.

2023-03-07 10:09 UTC, Adebesin-Cell commented on src/components/Admin/WikiCreatedInsight/WikiElemets.tsx
> +      <Text color="#718096">
You can move this to ``semantic-tokens.ts``

2023-03-07 10:40 UTC, OleanjiKingCode commented on .codeclimate.yml
> +      threshold: 240
yes, i dont know why, but i just added that in case its used

2023-03-07 10:42 UTC, Adebesin-Cell commented on .codeclimate.yml
> +      threshold: 240
Yeah, it was throwing some eslint errors so it's disabled for now.

2023-03-07 13:32 UTC, OleanjiKingCode commented on .codeclimate.yml
> +      threshold: 240
Alright

2023-03-07 14:34 UTC, Adebesin-Cell approved these changes
Cool, let's ensure we test properly before merge.

2023-03-08 10:14 UTC, Royal-lobster commented
Great work 👏 @OleanjiKingCode. Some things i noticed - 

- we can make this admin.tsx instead of admin/index.tsx
<img width="278" alt="CleanShot 2023-03-08 at 15 36 08@2x" src="https://user-images.githubusercontent.com/52039218/223684064-a6ed0592-9fd4-40d2-ada9-bc0c8b98490b.png">

- there are a lot of rtk fetch hooks on page file. i think we can make it more simplier by moving the data fetching closer to components that need them instead of passing the data via props.
<img width="696" alt="CleanShot 2023-03-08 at 15 38 50@2x" src="https://user-images.githubusercontent.com/52039218/223684662-173d2d68-53fa-4c16-8e2e-2a8088860946.png">

- also there is a lot of filterning logic there. ideally the page file should contain as minimum logic as possible while abstracting the logic in components
<img width="781" alt="CleanShot 2023-03-08 at 15 41 22@2x" src="https://user-images.githubusercontent.com/52039218/223685134-13cc0415-387c-4aaf-9e96-3351f8f2327a.png">

- this can be abstracted to a seperate component too ! so the first three boxes at top of admin page will be a seperate component
<img width="915" alt="CleanShot 2023-03-08 at 15 42 45@2x" src="https://user-images.githubusercontent.com/52039218/223685605-22814e86-85bb-4337-b2e9-0c5f8d2aeaec.png">

2023-03-08 11:24 UTC, Emmanueldmlr requested changes

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikiElemets.tsx
> +  PromoteClickOne: () => void
I think you should create a reusable type for this and use it for all the instances.

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikiElemets.tsx
> +            color={item.hidden ? '#E2E8F0' : '#FF5CAA'}
can you create a name for the colors instead? it's easy to update like that.

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikiElemets.tsx
> +              color="#E2E8F0"
can you create a name for the color instead? it's easy to update like that.

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikiElemets.tsx
> +            <Text color="#F11a82" _dark={{ color: '#FF1A88' }} cursor="pointer">
create a semantic token for this color.

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikiElemets.tsx
> +              color="#F11a82"
avoid using color code.

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikiInsightTable.tsx
> +            No data to display 🐌
not sure if the emoji is necessary.

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikisTable.tsx
> +                      _dark={{ bg: '#FFB3D7', color: '#FF409B' }}
use semantic token instead

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiEditorInsight/InsightTableWikiEditors.tsx
> +                    <Text color="#primaryGray">
```suggestion
                    <Text color="primaryGray">
```

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiEditorInsight/InsightTableWikiEditors.tsx
> +                    <Text color="#primaryGray">{item.wikisEdited.length}</Text>
```suggestion
                    <Text color="primaryGray">{item.wikisEdited.length}</Text>
```

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiEditorInsight/InsightTableWikiEditors.tsx
> +                    <Text color="#primaryGray">{item.wikisCreated.length}</Text>
```suggestion
                    <Text color="primaryGray">{item.wikisCreated.length}</Text>
```

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiEditorInsight/InsightTableWikiEditors.tsx
> +                    <Text color="#primaryGray">
```suggestion
                    <Text color="primaryGray">
```

2023-03-08 11:24 UTC, Emmanueldmlr commented on src/components/Admin/WikiEditorInsight/InsightTableWikiEditors.tsx
> +                  <Td color="#primaryGray">
```suggestion
                  <Td color="primaryGray">
```

2023-03-08 15:07 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikiElemets.tsx
> +                color: item.hidden ? 'davyGray' : '#495a68',
you are still using a color code

2023-03-08 15:07 UTC, Emmanueldmlr commented on src/components/Admin/WikiCreatedInsight/WikisTable.tsx
> +                        _dark={{ color: item.hidden ? '#AE5D35' : '#38A169' }}
use semantic token

2023-03-08 21:10 UTC, Emmanueldmlr approved these changes

2023-03-08 21:10 UTC, Emmanueldmlr commented on src/components/Admin/WikiEditorInsight/InsightTableWikiEditors.tsx
> +                            color="#primaryGray"
```suggestion
                            color="primaryGray"
```

2023-03-08 21:57 UTC, Royal-lobster approved these changes

2023-03-09 09:42 UTC, Softdev1 approved these changes

2023-03-09 09:51 UTC, OleanjiKingCode commented
> @OleanjiKingCode Can you fix the conflicts? Btw, is this PR related #1229?

Yes, they got mixed but its fixed now

2023-03-09 09:51 UTC, merged