Fixes #1196
EveripediaNetwork/ep-ui pull request #1271
Opened 2023-04-12 17:11 UTC by Aliiiu

# Fixing IG and Bond Links 

_PR description goes here_
This PR fixes the footer links for both Instagram (IG) and Bond on our website. Previously, the links were not redirecting to the correct pages. The issue has been resolved by updating the URLs in the code.

The changes have been thoroughly tested and verified on various devices and browsers.

Thank you for reviewing this PR.
## How should this be tested?

1. Go to footer.
2. click the bond link, this will open the bond page on a new tab.
3. click the ig logo, this will open a new tab of the iq-wiki Instagram page.

## Notes or observations

_jot down something here_

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/1196

2023-04-12 17:36 UTC, kesar requested changes

2023-04-12 17:36 UTC, kesar commented on src/types/admin.ts
> -  // rome-ignore lint/suspicious/noExplicitAny: <explanation>
wasnt needed?

2023-04-13 08:18 UTC, Aliiiu commented on src/types/admin.ts
> -  // rome-ignore lint/suspicious/noExplicitAny: <explanation>
i was unable to commit my changes without removing that line

2023-04-13 08:18 UTC, Aliiiu commented
> pls revert removing yarn.lock

alright i will do that

2023-04-13 08:46 UTC, kesar commented on .gitignore
> +yarn.lock
you can't ignore yarn.lock pls revert

2023-04-13 08:46 UTC, kesar commented on src/types/admin.ts
> -  // rome-ignore lint/suspicious/noExplicitAny: <explanation>
sync w the dev that added it to figure out if its needed or not

2023-04-13 08:48 UTC, Aliiiu commented on .gitignore
> +yarn.lock
alright, please what do you mean by "revert by removing yarn.lock"

2023-04-13 08:51 UTC, kesar commented on .gitignore
> +yarn.lock
you had removed yarn.lock from the project and that's something you need to revert. 
you also need to revert the changes in gitignore related to ignore yarn.lock 👍🏻

2023-04-13 09:33 UTC, Aliiiu commented on .gitignore
> +yarn.lock
Alright done

2023-04-13 09:37 UTC, kesar commented on .gitignore
> +yarn.lock
its not done, please carefully review your pull request. In your pull request you have removed yarn.lock file.

2023-04-13 09:38 UTC, kesar commented on .gitignore
> +yarn.lock
sorry, you haven't removed but you have changed it, when the task doesnt require to change yarn lock at all. PR should contain what its expected to review. If you edit other files it makes hard to review the PR and it can lead to unexpected bugs

I

2023-04-13 11:51 UTC, closed without merging