Carousel slider
EveripediaNetwork/ep-ui pull request #1289
Opened 2023-04-20 11:47 UTC by OleanjiKingCode

# Overflow of Carousel on mobile

## How should this be tested?

Before 
![image](https://user-images.githubusercontent.com/75235148/233356731-478dade4-3e35-4a3f-8ad7-9df4a3216c7a.png)

Now
![image](https://user-images.githubusercontent.com/75235148/233356739-eae81b40-8731-4333-9d44-4e211fe68b91.png)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1224

2023-04-20 13:21 UTC, Adebesin-Cell requested changes
https://user-images.githubusercontent.com/66301634/233379055-ef299264-5c36-4911-88cb-cf87777e21c8.mov

I think we can have this feature slider once the wikis promoted are more than 5 or 4, it'll make it look very nice and compact like in the design.

2023-04-20 16:38 UTC, OleanjiKingCode commented
> Screen.Recording.2023-04-20.at.2.12.07.PM.mov 
> I think we can have this feature slider once the wikis promoted are more than 5 or 4, it'll make it look very nice and compact like in the design.

what was used to make this carousel

2023-04-20 16:39 UTC, Adebesin-Cell commented
> > Screen.Recording.2023-04-20.at.2.12.07.PM.mov
> > I think we can have this feature slider once the wikis promoted are more than 5 or 4, it'll make it look very nice and compact like in the design.
> 
> what was used to make this carousel

Let me check 😅, I didn't check.

2023-04-24 16:20 UTC, Emmanueldmlr commented on src/components/Elements/Carousel/Carousel.tsx
> +// const Slider = SliderClass as unknown as (props: {
Remove the comment.

2023-04-24 16:20 UTC, Emmanueldmlr commented on src/components/Elements/Carousel/Carousel.tsx
> +  const handleClick = (index: number) => {
Looking so complex, can you rewrite this?

2023-04-24 16:55 UTC, kesar commented on src/components/Elements/Carousel/Carousel.tsx
> +  const [activeSlide2, setActiveSlide2] = useState(0)
https://docs.rome.tools/lint/rules/nounusedvariables/

use _ and avoid cutting corners w rome-ignores

2023-04-25 08:25 UTC, Royal-lobster commented
Its acting weird after reaching to end and looping back to first card

https://user-images.githubusercontent.com/52039218/234218669-ca137ea8-67a8-433d-8888-85144c2821a5.mp4

2023-04-26 07:06 UTC, OleanjiKingCode commented
it was meant to replicate Airbnb's own

https://user-images.githubusercontent.com/75235148/234496179-a6fb7b8d-6efb-4a93-aac9-c264aaf482d9.mp4

2023-04-26 07:21 UTC, Softdev1 commented
I would suggest that the arrows be included on the images so that users understand that there are still some featured wikis remaining

2023-04-26 10:04 UTC, Royal-lobster commented
> it was meant to replicate Airbnb's own
> 
Ahh ok, but i think air bnb is having a animation which indicates the slider moving to next page. with it out its looking buggy imo.

2023-04-26 14:05 UTC, Royal-lobster approved these changes

2023-04-26 14:16 UTC, Adebesin-Cell commented
https://user-images.githubusercontent.com/66301634/234603453-4c25a3cb-2416-4efc-af9e-2b6bdc87b039.mov

When the contents are longer than 5, the indicator isn't showing up. I think you can think up each slider item having dots since we have five elements rendered, then we give that one-page i.e. 5 elements per page, then after the fifth one we move to the next page with the elements inside.

2023-04-26 14:24 UTC, OleanjiKingCode commented
it works normally 

https://user-images.githubusercontent.com/75235148/234606508-315aae49-1d63-4c7c-a589-108555752353.mp4

@Adebesin-Cell

2023-04-26 14:32 UTC, Adebesin-Cell approved these changes
Great work 👏

2023-04-26 14:33 UTC, merged