Fix/metamask prompt modal
EveripediaNetwork/ep-ui pull request #1431
Opened 2023-08-14 23:15 UTC by Aliiiu

# Fix for Prompt Modal for Metamask installation Issue

## How should this be tested?

1.  Disconnect the metamask extension
2. Click on the wallet icon
3. Click on the metamask connector

## Notes or observations

<img width="955" alt="Screen Shot 2023-08-15 at 12 12 55 AM" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/ec28962f-776e-4cd3-aaa9-3885e26a4a63">

<img width="767" alt="Screen Shot 2023-08-15 at 12 13 22 AM" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/fc91e44b-9c61-434a-9687-13d19fee2fda">

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1679

2023-08-15 06:20 UTC, Emmanueldmlr commented
<img width="1361" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/70170061/e7503b6b-699f-43ab-b27b-dc37140717b2">

you don't have to create new files for the icons, just import RiErrorWarningFill from react-icons/ri.

2023-08-15 06:29 UTC, Emmanueldmlr requested changes

2023-08-15 06:29 UTC, Emmanueldmlr commented on src/components/Layout/WalletDrawer/Connectors.tsx
> +import MetaMaskConnectionErrorModal from './MetaMaskConnectionErrorModal'
I think we shouldn't limit it to metamask only. it works for other connectors when they are also not active. You might want to rename it to be more general.

2023-08-15 06:29 UTC, Emmanueldmlr commented on src/components/Layout/WalletDrawer/MetaMaskConnectionErrorModal.tsx
> +        _dark={{
check if we have a semantic token for this.

2023-08-15 06:29 UTC, Emmanueldmlr commented on src/components/Layout/WalletDrawer/MetaMaskConnectionErrorModal.tsx
> +            Metamask was not detected in your browser, You can acquire MetaMask,
Make this general so as to work for all other connectors.

2023-08-15 06:29 UTC, Emmanueldmlr commented on src/components/Layout/WalletDrawer/MetaMaskConnectionErrorModal.tsx
> +                colorMode === 'dark'
You don't need this when you use the Icon from react-icons/ri.

2023-08-15 09:47 UTC, Aliiiu commented on src/components/Layout/WalletDrawer/Connectors.tsx
> +import MetaMaskConnectionErrorModal from './MetaMaskConnectionErrorModal'
Alright

2023-08-15 09:47 UTC, Aliiiu commented on src/components/Layout/WalletDrawer/MetaMaskConnectionErrorModal.tsx
> +                colorMode === 'dark'
Noted

2023-08-15 11:15 UTC, Emmanueldmlr approved these changes

2023-08-15 13:01 UTC, Simplypheyie96 approved these changes

2023-08-16 09:29 UTC, Softdev1 approved these changes

2023-08-16 09:39 UTC, merged