Redesigning homepage
EveripediaNetwork/ep-ui pull request #1446
Opened 2023-08-21 22:52 UTC by Aliiiu

# Redesigning IQ Wiki Homepage

closes https://github.com/EveripediaNetwork/issues/issues/1687

## Notes or observations

<br />
<img width="1792" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/e8704020-58bb-4f9e-ab30-f6e937afeab9">

<img width="1792" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/df09412f-59c2-4a38-863a-a3e9767080f9">

<img width="1792" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/c238b9b8-da3e-418b-b33d-99b26a6d49d4">

<img width="1791" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/0f40593c-7db9-4cf4-b97c-9ba24fefa7e8">

<img width="1792" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/2132bc72-d5c0-44aa-8a9e-4a27ddc6eb8a">

<img width="1791" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/e6c9bbd7-f756-4e10-a70d-4eb3202b922b">

2023-08-22 09:12 UTC, Adebesin-Cell commented
One thing, try to reduce the size of the GIF of the robot, rn it's about 2.5 MB large. You can make it around 200kb - 500kb without losing the quality.

2023-08-22 09:13 UTC, Adebesin-Cell commented
<img width="1440" alt="Screen Shot 2023-08-22 at 10 12 22 AM" src="https://github.com/EveripediaNetwork/ep-ui/assets/66301634/7c993a3a-3446-4f33-9245-8454f365e7d0">

Not sure if it's related to the PR, but that card in the carousel shrinks, unlike the others. Try to fix it.

2023-08-22 09:20 UTC, Adebesin-Cell requested changes

2023-08-22 09:20 UTC, Adebesin-Cell commented on src/components/Landing/AboutIqgpt.tsx
> +            <Button
You can use ``LinkButton`` here

2023-08-22 09:20 UTC, Adebesin-Cell commented on src/components/Landing/AboutIqgpt.tsx
> +            <Button
``LinkButton`` here too, to allow for consistent link buttons across the page.

2023-08-22 15:55 UTC, Simplypheyie96 requested changes
- this is the value for shadows on dark mode including the shadows on hover for categories:
border-radius: 8px;
background: var(--gray-700, #2D3748);
box-shadow: 0px 25px 50px -12px rgba(16, 16, 17, 0.25);

- re-inspect the IQ gpt section. the implementation is not right yet for md/sm breakpoints. and the gif is not visible.
- there's something weird about the featured wikis in both light and dark mode. they should look like this: 
<img width="1224" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/ec5934e7-9b48-4024-baa5-3353535e8e34">

2023-08-23 14:16 UTC, Adebesin-Cell commented
@Aliiiu One thing, I think you should switch the order of the new banner and categories. On prod, the leaderboard doesn't show yet

2023-09-05 10:59 UTC, Adebesin-Cell commented
@Aliiiu This PR is getting too large and long. It's been open for two weeks, pls try to round off and make smaller PRs for easy review and feedbacks.
Rn, It's messy to know what's going on in the PR.

2023-09-06 10:52 UTC, Simplypheyie96 approved these changes
I think we can merge now.
@Softdev1

2023-09-06 10:56 UTC, Aliiiu commented
> I think we can merge now. @Softdev1

@Softdev1 I will have to resolve the PR

2023-09-06 11:05 UTC, Softdev1 commented
> > I think we can merge now. @Softdev1
> 
> @Softdev1 I will have to resolve the PR

No problem then @Aliiiu

2023-09-06 11:44 UTC, merged