Resolving link issues in the edit modal issue
EveripediaNetwork/ep-ui pull request #1455
Opened 2023-08-31 15:09 UTC by Aliiiu

# Updating the links in the edit details modal

Working to add the mirror link to the list of links and fixing the regex for medium

## How should this be tested?

1. Go to create wiki page
2. Click edit wiki
3. try to add mirror

## Notes or observations

<img width="764" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/67792966/95c3fd29-6f01-43fb-82ca-6f00bf92bd75">

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1737, 
closes https://github.com/EveripediaNetwork/issues/issues/1737

2023-08-31 17:22 UTC, Royal-lobster approved these changes

2023-08-31 17:22 UTC, Royal-lobster approved these changes

2023-09-04 14:02 UTC, Adebesin-Cell commented on src/data/WikiLinks.ts
> +    tests: [/^https:\/\/medium\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+$/],
https://fatfish.medium.com/my-boss-you-dont-know-react-at-all-7bc360ef0a23 testing this URL doesn't work, or is there a particular URL format for medium?

2023-09-04 14:05 UTC, Aliiiu commented on src/data/WikiLinks.ts
> +    tests: [/^https:\/\/medium\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+$/],
I did not consider this format. I think I will have to check for that. Will update it and revert

2023-09-04 14:07 UTC, Adebesin-Cell commented on src/data/WikiLinks.ts
> +    tests: [/^https:\/\/medium\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+$/],
I see, I think medium has three possible links, we should prolly use the test array to match tests, meaning, test array can be more than one test, instead of using | in the regex, I think that might help solve the complexity.

2023-09-04 14:09 UTC, Aliiiu commented on src/data/WikiLinks.ts
> +    tests: [/^https:\/\/medium\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+$/],
Can you drop the 3 link samples here

2023-09-04 14:14 UTC, Adebesin-Cell commented on src/data/WikiLinks.ts
> +    tests: [/^https:\/\/medium\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+$/],
1. https://medium.com/@mheidj/experts-may-have-figured-out-why-we-yawn-a10c0b5be749
2. https://judedoyle.medium.com/the-male-loneliness-epidemic-does-not-exist-9c2013daf644
3. https://medium.com/reimagining-the-civic-commons/can-a-folded-map-unite-us-e1d95e9544b8?source=home---------10------------------0----------

I think these are the possible cases, aside that we have custom urls 😅. Not sure if we need to test for the three cases.

2023-09-04 21:08 UTC, Adebesin-Cell requested changes

2023-09-04 21:08 UTC, Adebesin-Cell commented on src/data/WikiLinks.ts
> +      /^(https?:\/\/)?([\w-]+(\.[\w-]+)+)([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?$/,
Hmm, is this only for medium links?

2023-09-04 21:08 UTC, Adebesin-Cell commented on src/data/WikiLinks.ts
> +      /^(https?:\/\/)?([\w-]+(\.[\w-]+)+)([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?$/,
Nope, it's not. Please don't allow any random links, strictly only medium links.

2023-09-05 08:11 UTC, Adebesin-Cell commented
@Aliiiu It still fail for the medium link that brought about the issue https://medium.com/@ShapeShift.com.

2023-09-05 08:14 UTC, Aliiiu commented
> @Aliiiu It still fail for the medium link that brought about the issue https://medium.com/@ShapeShift.com.

Alright, will look into this.

2023-09-05 08:24 UTC, Adebesin-Cell commented
> > @Aliiiu It still fail for the medium link that brought about the issue https://medium.com/@ShapeShift.com.
> 
> Alright, will look into this.

Cool.

2023-09-05 13:20 UTC, Adebesin-Cell approved these changes
Looks good. 👍

2023-09-05 13:41 UTC, merged