Fixes editor auto focus scrolling page to bottom
EveripediaNetwork/ep-ui pull request #152
Opened 2022-04-07 16:31 UTC by Royal-lobster

Re-implemented fetching initial wiki content to editor. Did this for using `autofocus={false}` directly on `ToastUIEditor` component.

2022-04-07 16:40 UTC, Royal-lobster commented
@JustinCast @Emmanueldmlr Please kindly review. I am not 100% sure if this change don't break any other functionality as side-effect.

2022-04-07 20:34 UTC, JustinCast requested changes
The editor text is not changing after change the page type

2022-04-07 20:34 UTC, JustinCast commented on src/components/Layout/Editor/Editor.tsx
> +  console.log(markdown)
we can remove this console.log

2022-04-08 08:54 UTC, kesar commented on src/components/Layout/Editor/Editor.tsx
> +  console.log(markdown)
```suggestion
```

when there is something simple like this I would recommend to click in suggest button and send the suggestion since it takes no time and PR could even get accepted without getting back to the IDE if the creator commit suggestion 👍🏻 cc: @JustinCast

2022-04-08 08:54 UTC, kesar commented on src/components/Layout/Editor/Editor.tsx
> +  console.log(markdown)
```suggestion
```

when there is something simple like this I would recommend to click in suggest button and send the suggestion since it takes no time and PR could even get accepted without getting back to the IDE if the creator commit suggestion 👍🏻 cc: @JustinCast

2022-04-08 12:31 UTC, Royal-lobster commented
> The editor text is not changing after change the page type

Ohh i was thinking the same but, The editor text is not changing in main branch too.

2022-04-08 12:32 UTC, kesar commented
> > The editor text is not changing after change the page type
> 
> Ohh i was thinking the same but, The editor text is not changing in main branch too by changing the page type.

if its a issue on main, please open an issue related to that on github and we could merge this I guess 👍🏻

2022-04-08 12:36 UTC, Royal-lobster commented
Created a new issue for that !

2022-04-08 12:38 UTC, kesar approved these changes

2022-04-08 12:38 UTC, kesar commented
cool, lets wait for @JustinCast input 👍🏻

2022-04-08 15:24 UTC, JustinCast approved these changes
LGTM

2022-04-10 06:34 UTC, merged