Refactor rank page url
EveripediaNetwork/ep-ui pull request #1529
Opened 2023-11-22 14:00 UTC by SidharthK2

# Refactor rank page URL to be more shareable

New rank page URL :  `/rank/[category]`

![image](https://github.com/EveripediaNetwork/ep-ui/assets/58448956/6dc4037b-d152-418f-8aa3-081cccebee00)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1976

2023-11-22 14:34 UTC, Aliiiu requested changes

2023-11-22 14:34 UTC, Aliiiu commented on src/pages/rank/[id].tsx
> +  console.log('pg', page)
You can clean this

2023-11-22 14:34 UTC, Aliiiu commented on src/components/Rank/RankPagination.tsx
> +        p: pageNumber,
I think page is better

2023-11-22 14:41 UTC, Adebesin-Cell commented on src/pages/rank/[id].tsx
> +  console.log('pg', page)
Not a big deal, I think it’ll read better with [caregory].tsx 👍.

2023-11-22 14:42 UTC, SidharthK2 commented on src/pages/rank/[id].tsx
> +  console.log('pg', page)
@Adebesin-Cell Agreed.

2023-11-23 06:27 UTC, Aliiiu approved these changes

2023-11-23 07:29 UTC, merged