Fix Rank Table spacing
EveripediaNetwork/ep-ui pull request #1562
Opened 2023-12-19 14:48 UTC by SidharthK2

# Adjust Rank table spacing to prevent side scrolling

### Before

![image](https://github.com/EveripediaNetwork/ep-ui/assets/58448956/7b3de0c6-550d-44e9-9873-1fd668a3d6de)

### After

![image](https://github.com/EveripediaNetwork/ep-ui/assets/58448956/0cb39416-6ac6-4a55-b1ba-a3f44d9b3e22)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2087

2023-12-19 15:46 UTC, Simplypheyie96 requested changes
- we still need to get his fixed on mobile.
![image](https://github.com/EveripediaNetwork/ep-ui/assets/99387231/1d137573-13db-426e-99e7-ef76bf105e76)

2023-12-21 11:02 UTC, Softdev1 commented
@SidharthK2 This feedback has been here for two days now, this issue shouldn't take this long

2023-12-21 12:41 UTC, SidharthK2 commented
> * we still need to get his fixed on mobile.
>   ![image](https://private-user-images.githubusercontent.com/99387231/291638972-1d137573-13db-426e-99e7-ef76bf105e76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjI0NTUsIm5iZiI6MTcwMzE2MjE1NSwicGF0aCI6Ii85OTM4NzIzMS8yOTE2Mzg5NzItMWQxMzc1NzMtMTNkYi00MjZlLTk5ZTctZWY3NmJmMTA1ZTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEyMzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZTJhZGE4YzJiYzJmNjhkY2Q5MmEyN2E1YTY3NGU2Y2NlNjhlMTNkZGZhODU3ZTc5M2FlMDc0YzI1OTQ4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bMFRfbZ2msmjI7bbxLYcQ0kweGDI3ZiLOgW0J8XpdRE)

![image](https://github.com/EveripediaNetwork/ep-ui/assets/58448956/740133a1-3f9f-4ec7-a3e5-25b071b06d8c)


The gap should be fixed on populated table

2023-12-21 13:14 UTC, Simplypheyie96 approved these changes

2023-12-21 13:35 UTC, merged