Chat bot
EveripediaNetwork/ep-ui pull request #1567
Opened 2023-12-26 13:39 UTC by Aliiiu

# Design Chat Bot

This PR works on implementing the chatbot UI

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2082

2023-12-28 18:05 UTC, Simplypheyie96 reviewed
- This needs to be removed
![image](https://github.com/EveripediaNetwork/ep-ui/assets/99387231/90621032-5619-4f35-84f0-aa6b8aacb842)
- The UI needs to be updated
![image](https://github.com/EveripediaNetwork/ep-ui/assets/99387231/dcfb8191-ea7b-4a71-b58f-36f3418254b1)

- another thing that needs update
<img width="472" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/30968946-e96b-44f7-92d4-1300eb15c590">

- ![image](https://github.com/EveripediaNetwork/ep-ui/assets/99387231/b34bdd2e-bf2c-4aad-82c8-7398663e01bf)

2024-01-03 09:54 UTC, Simplypheyie96 requested changes
- I think there is enough space to make the least font size 12px. on the chatbot.
The components are to make it flexible for all screen sizes. 
if you check the main insert on the wiki page design, you will see the least font size is 12px, please adjust the sizes so they are more visible. they to small right now compared to other widgets (I mentioned this in the video sent). 
nb: let me know if you need me to increase the sizes of the components.
(an image of the insert on wiki page on figma)
![image](https://github.com/EveripediaNetwork/ep-ui/assets/99387231/8795ddf1-c861-4025-ae0d-8d853c88eee0)

- The logo has not been updated (also mentioned this in the video
<img width="41" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/4428c5f3-3f30-4480-be37-f15c88b49e44">

- Content really small on the collapsible widget and. there is no margin between text and logo 
![image](https://github.com/EveripediaNetwork/ep-ui/assets/99387231/7d8e32f0-4f9d-4f59-b303-001d206ce723)
- presenting data animation is static
<img width="269" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/974bd50d-dc0e-4e4c-9c09-66f5fa14d200">

2024-01-03 11:59 UTC, Adebesin-Cell commented on src/components/Wiki/WikiPage/InsightComponents/BrainBot/BotMessages.tsx
> +        console.log(message.answer)
remove logs

2024-01-03 11:59 UTC, Adebesin-Cell commented on src/components/Wiki/WikiPage/InsightComponents/BrainBot/BrainBot.tsx
> +export const queryMapper = (query: string, wiki: Wiki) => {
Kindly move this into a util file and use enums to handle the cases, makes it cleaner.

2024-01-03 11:59 UTC, Adebesin-Cell commented on src/components/Wiki/WikiPage/InsightComponents/BrainBot/ChatBot.tsx
> +  useEffect(() => {
Extract this logic into a hook and use in places that are duplicated.

2024-01-03 12:14 UTC, Aliiiu commented on src/components/Wiki/WikiPage/InsightComponents/BrainBot/ChatBot.tsx
> +  useEffect(() => {
The scrollToBottom logic?

2024-01-03 12:16 UTC, Adebesin-Cell commented on src/components/Wiki/WikiPage/InsightComponents/BrainBot/ChatBot.tsx
> +  useEffect(() => {
yes

2024-01-03 17:43 UTC, Simplypheyie96 requested changes
- this still looks unbalanced. i think you left a single word in one line, so the logo looks unaligned. (I will change the position of the design so the implementation looks better).
<img width="436" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/10bff4a8-c90d-4292-ba78-4bdf6bb46d95">

- please add hover states for all clickable buttons.
- presenting data animation (loading state) still not working
- for 'ask me about crypto' option on the first page, (I mentioned before), this should show the bot replying "ask me a question about crypto" and not it suggesting questions as answers.
<img width="430" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/bd8f1a7a-5c85-4dac-b8b9-384ddd1d04e7">
 
 - I also realized that the logo is for IQ wiki, so i will be changing all instances of the logo to IQ gpt logo

2024-01-04 07:11 UTC, Aliiiu commented
> * this still looks unbalanced. i think you left a single word in one line, so the logo looks unaligned. (I will change the position of the design so the implementation looks better).
> 
> <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/99387231/293985914-10bff4a8-c90d-4292-ba78-4bdf6bb46d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTM3MzIsIm5iZiI6MTcwNDMxMzQzMiwicGF0aCI6Ii85OTM4NzIzMS8yOTM5ODU5MTQtMTBiZmY0YTgtYzkwZC00MjkyLWJhNzgtNGJkZjZiYjQ2ZDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNzkxY2M3ZTQwNmM4OWVkYzFmZTIyOGEwM2VjYmUwOTdlNThmMzMzMTkzZWJhMDYwMDNlOWI1NWQyNzhkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-bnwRM3d9oMKQO-9NZ6I5bcwVlmkNMzlYdv48KzzYcc">
> * please add hover states for all clickable buttons.
> * presenting data animation (loading state) still not working
> * for 'ask me about crypto' option on the first page, (I mentioned before), this should show the bot replying "ask me a question about crypto" and not it suggesting questions as answers.
> 
> <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/99387231/293988129-bd8f1a7a-5c85-4dac-b8b9-384ddd1d04e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTM3MzIsIm5iZiI6MTcwNDMxMzQzMiwicGF0aCI6Ii85OTM4NzIzMS8yOTM5ODgxMjktYmQ4ZjFhN2EtNWM4NS00ZGFjLWI4YjktMzg0ZGRkMWQwNGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNDNiZWE2YTBmODNiYWRiOGNlODQ0Y2U5NTYwYzNiZTIzMWU5ZmE4MDVmMGNjOGIwNzlhNmYzNGMwNDQzNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uz0g86qMMpqsozuy0BbA5LkcQ8-17eBbaWbxI1z_-ts">
> * All logos used are for IQ wiki instead of IQ gpt. please change them
> * also, like I mentioned before, clicking on the logo should redirect to IQ gpt, so that the function of the IQ GPT banner we had before is maintained.

I don't think it is a good user experience to click on the logo of a widget and it's redirect you to a website. I only added that feature to the footer section of the widget. You can check if the hover state of the footer section is good enough

2024-01-04 10:14 UTC, Simplypheyie96 commented
> > * this still looks unbalanced. i think you left a single word in one line, so the logo looks unaligned. (I will change the position of the design so the implementation looks better).
> > 
> > <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/99387231/293985914-10bff4a8-c90d-4292-ba78-4bdf6bb46d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTM3MzIsIm5iZiI6MTcwNDMxMzQzMiwicGF0aCI6Ii85OTM4NzIzMS8yOTM5ODU5MTQtMTBiZmY0YTgtYzkwZC00MjkyLWJhNzgtNGJkZjZiYjQ2ZDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNzkxY2M3ZTQwNmM4OWVkYzFmZTIyOGEwM2VjYmUwOTdlNThmMzMzMTkzZWJhMDYwMDNlOWI1NWQyNzhkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-bnwRM3d9oMKQO-9NZ6I5bcwVlmkNMzlYdv48KzzYcc">
> > * please add hover states for all clickable buttons.
> > * presenting data animation (loading state) still not working
> > * for 'ask me about crypto' option on the first page, (I mentioned before), this should show the bot replying "ask me a question about crypto" and not it suggesting questions as answers.
> > <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/99387231/293988129-bd8f1a7a-5c85-4dac-b8b9-384ddd1d04e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTM3MzIsIm5iZiI6MTcwNDMxMzQzMiwicGF0aCI6Ii85OTM4NzIzMS8yOTM5ODgxMjktYmQ4ZjFhN2EtNWM4NS00ZGFjLWI4YjktMzg0ZGRkMWQwNGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNDNiZWE2YTBmODNiYWRiOGNlODQ0Y2U5NTYwYzNiZTIzMWU5ZmE4MDVmMGNjOGIwNzlhNmYzNGMwNDQzNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uz0g86qMMpqsozuy0BbA5LkcQ8-17eBbaWbxI1z_-ts">
> > * All logos used are for IQ wiki instead of IQ gpt. please change them
> > * also, like I mentioned before, clicking on the logo should redirect to IQ gpt, so that the function of the IQ GPT banner we had before is maintained.
> 
> I don't think it is a good user experience to click on the logo of a widget and it's redirect you to a website. I only added that feature to the footer section of the widget. You can check if the hover state of the footer section is good enough

I did mention previously in the video i sent to you on discord that the logo on the bottom should be the one to redirect to iq gpt and not the whole widget. I was using my cursor in the video to show what redirects to iq gpt. you can watch the video to see
<img width="432" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/8e3ba1d5-11b9-4f9e-9c11-f3857a5f9baa">

2024-01-04 15:26 UTC, Adebesin-Cell commented on src/utils/BotUtils/index.ts
> +  GenerateAdditionalInfo = 'Generate additional info for this page',
the enums can be in form of ids perhaps not content text, ``GenerateAdditionalInfo = AdditionalInfo``, just a simple word to describe it.

2024-01-04 15:26 UTC, Adebesin-Cell commented on src/utils/BotUtils/index.ts
> +          Generate an additional information for the content above?
To make the prompting better, I believe we can use ``Generate additional information for the content delimited by backticks  ${wiki.content} ``

2024-01-04 15:26 UTC, Adebesin-Cell commented on src/utils/BotUtils/index.ts
> +          Summarize the content above?
Same with this.

2024-01-04 15:42 UTC, Simplypheyie96 approved these changes

2024-01-04 15:47 UTC, Adebesin-Cell commented on src/components/Wiki/WikiPage/InsightComponents/BrainBot/BrainBot.tsx
> +              question={'Generate additional info for this page'}
Not in this PR, but we should add translations for the contents.

2024-01-04 15:47 UTC, Adebesin-Cell commented on src/utils/BotUtils/index.ts
> +      newQuery = `Generate additional information for the content delimited by backticks  ${wiki.content}`
Oh you missed to add backticks, it's just to make the focus of the llm better. you can use sth else like hash symbol

2024-01-04 15:47 UTC, Adebesin-Cell commented on src/utils/BotUtils/index.ts
> +      newQuery = `${wiki.content}
duplicated ${wiki.content}, also missing the backticks

2024-01-04 15:47 UTC, Adebesin-Cell commented on src/utils/BotUtils/index.ts
> +enum QueryType {
Cool, ensure to make the used in other pages so it's easy to edit and update content everywhere.

2024-01-04 15:48 UTC, Aliiiu commented on src/components/Wiki/WikiPage/InsightComponents/BrainBot/BrainBot.tsx
> +              question={'Generate additional info for this page'}
Alright

2024-01-04 16:22 UTC, Adebesin-Cell approved these changes

2024-01-04 16:31 UTC, merged