Wiki page UI improvements
EveripediaNetwork/ep-ui pull request #1593
Opened 2024-01-17 08:46 UTC by SidharthK2

# Various tweaks to the wiki insights panel on mobile and desktop

- Removes `created by` and `created at` rows
- Reorganizes the details section
- Removes excessive padding and margins

WIP
- Implements redesigned chatbot interface on mobile

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/2191

2024-01-17 09:08 UTC, Softdev1 commented
who is reviewing this issue @SidharthK2

2024-01-17 09:10 UTC, SidharthK2 commented
> who is reviewing this issue @SidharthK2

It's still WIP, will add soon.

2024-01-18 15:46 UTC, Simplypheyie96 requested changes
- this should be titled "network" {see figma: https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.wiki?type=design&node-id=28640-10978&mode=design&t=uMEzCv8GgxT4s4ZD-11)
<img width="415" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/6d2bff22-e8aa-49ff-a175-5c2ef527795a">

- on medium breakpoint, we can have the whole text fill the card without breaking the text
<img width="449" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/eca91c47-3453-4834-84b5-a19cbad703e2">

- on mobile, let's have all the widgets automatically minimized (except the first one that contains details of the wiki)
<img width="319" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/0a864f15-5ca0-4f50-9942-78ebb3639e4a">

2024-01-18 17:18 UTC, Simplypheyie96 approved these changes

2024-01-18 17:19 UTC, merged