fix wiki image sizing in wiki
EveripediaNetwork/ep-ui pull request #1624
Opened 2024-02-05 15:23 UTC by Tolu-Mals

# Summary
Fixes wiki image size to be the same in viewing mode and editing mode

<details>
<summary> Before </summary>

![Screenshot 2024-02-05 at 4 00 18 PM](https://github.com/EveripediaNetwork/ep-ui/assets/30352484/ba85a012-4880-44d1-9df7-7d008d84922d)
</details>

<details>
<summary> After </summary>

![Screenshot 2024-02-05 at 4 20 39 PM](https://github.com/EveripediaNetwork/ep-ui/assets/30352484/2ae1c29c-cdec-4f70-8590-17446f8503f9)

</details>

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/2242

2024-02-05 16:56 UTC, Aliiiu requested changes

2024-02-05 16:56 UTC, Aliiiu commented on src/components/Wiki/WikiPage/CustomRenderers/customImageRender.tsx
> +      style={{
Why are you using the image prop and inline-style to set the image dimension

2024-02-05 16:59 UTC, Tolu-Mals commented on src/components/Wiki/WikiPage/CustomRenderers/customImageRender.tsx
> +      style={{
Nextjs images require that you pass a specific width and height for their optimizations. However since I want the actual values to be 'auto', I specified that inline. If I specified only via inline styles, it'll throw an error, because width and height props are required, but If I specified 'auto' via props, it'll throw an error, cos it expects actual values.

2024-02-05 17:14 UTC, Tolu-Mals commented on src/components/Wiki/WikiPage/CustomRenderers/customImageRender.tsx
> +      style={{
What I'm trying to do is let the image use the intrinsic width and height, you do that by setting the value of width and height to 'auto'. The width and height props don't support that.

2024-02-05 23:29 UTC, Aliiiu approved these changes

2024-02-05 23:31 UTC, Aliiiu commented on src/components/Wiki/WikiPage/CustomRenderers/customImageRender.tsx
> +      style={{
Yes. Check i think using the fill prop of the next image can help with that.

2024-02-06 14:11 UTC, Softdev1 approved these changes
I think we are good

2024-02-06 14:40 UTC, merged