Fixing Avatar on Hero and ENS domain
EveripediaNetwork/ep-ui pull request #175
Opened 2022-04-18 16:47 UTC by codiejay

Now the avatar only appears when it is fetched completely. I had to take out the CustomAvatar component cause it causing the a placeholding avatar to appear even when the avatar is not ready and users might try to click which will direct to the wiki.  
## Linked issues

closes #233, closes #233, closes https://github.com/EveripediaNetwork/issues/issues/233

2022-04-18 18:28 UTC, Royal-lobster requested changes
I think the layout near the avatar is [shifting](https://web.dev/cls/) too much which might be sudden for users, i think it looks good if we add a shiny [skeleton](https://chakra-ui.com/docs/components/feedback/skeleton) for avatar while loading so it fixes that.  

Maybe we can also implement skeletons with a circle and two stacked horizontal rectangles at the side for the avatar, wiki name and username instead of loading with three dots 

![image](https://user-images.githubusercontent.com/52039218/163855784-6f9055a9-aeb7-4204-a1cc-31b0a8f5712b.png)

what do you think?

2022-04-23 20:04 UTC, Royal-lobster reviewed
There seems to be a problem with image, the placeholder is not getting updated with avatar 

<img width="675" alt="image" src="https://user-images.githubusercontent.com/52039218/164944400-c73db95f-c5c2-4a08-ad62-322b92a5a668.png">

2022-04-23 22:15 UTC, codiejay commented
> There seems to be a problem with image, the placeholder is not getting updated with avatar
> 
> <img alt="image" width="675" src="https://user-images.githubusercontent.com/52039218/164944400-c73db95f-c5c2-4a08-ad62-322b92a5a668.png">

@Royal-lobster oh this is because this last user to edit this wiki doesn’t have an avatar. In cases like this I should use the CustomAvatar component that displays a better looking placeholder avatar but when I do that the link to the users account page no longer works.

2022-04-24 05:52 UTC, Royal-lobster commented
> @Royal-lobster oh this is because this last user to edit this wiki doesn’t have an avatar. In cases like this I should use the CustomAvatar component that displays a better looking placeholder avatar but when I do that the link to the users account page no longer works. 

Ohh that's weird. did you find why the link is not working on custom avatar? I am wondering what may be causing the link to break. maybe we can link the user profile inside of  ```Avatar``` by default if that works since it is the logical behaviour.

2022-04-24 11:55 UTC, codiejay commented
> > @Royal-lobster oh this is because this last user to edit this wiki doesn’t have an avatar. In cases like this I should use the CustomAvatar component that displays a better looking placeholder avatar but when I do that the link to the users account page no longer works.
> 
> Ohh that's weird. did you find why the link is not working on custom avatar? I am wondering what may be causing the link to break. maybe we can link the user profile inside of `Avatar` by default if that works since it is the logical behaviour.

I have solved this locally now. Thanks for the suggestion. I'll push hopefully soon.

2022-04-27 18:21 UTC, anubra266 commented on src/components/Landing/Hero.tsx
> +              <chakra.span color="blue">
FOr accessibility issues, the child receiving `passHref` should be an `a` tag. 
```suggestion
            <NextLink href={`/account/${wiki?.user?.id}`} passHref>
              <chakra.a color="blue">
```

2022-04-27 18:21 UTC, anubra266 commented on src/components/Profile/UserDetails.tsx
> +  console.log(username)
Can we remove this?

2022-05-02 12:43 UTC, Royal-lobster approved these changes

2022-05-02 14:32 UTC, merged