Refactor/cmc token price
EveripediaNetwork/ep-ui pull request #1778
Opened 2024-04-02 20:05 UTC by SidharthK2

## Pull current IQ price from CMC

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/2459

2024-04-02 21:36 UTC, Aliiiu commented
The marketcap is different from the one on iq.dashboard

2024-04-02 21:39 UTC, Aliiiu requested changes

2024-04-02 21:39 UTC, Aliiiu commented on src/services/cmcTokenDetails/index.ts
> +        [tokenName: string]: {
Create a type for this to make it cleaner

2024-04-03 04:06 UTC, Softdev1 approved these changes
<img width="1440" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/32770520/6fe879d3-1076-4a48-bae4-2ff12db2caa2">

2024-04-03 04:06 UTC, Softdev1 reviewed
Please ensure to fix the feedback above @SidharthK2

2024-04-03 19:44 UTC, Aliiiu commented
Please update the branch before you merge

2024-04-03 19:45 UTC, Aliiiu approved these changes

2024-04-04 08:16 UTC, merged