Resolve external links
EveripediaNetwork/ep-ui pull request #1812
Opened 2024-04-30 14:42 UTC by Aliiiu

# Resolve External Links

This PR works on resolving external links to add nofollow to links external to IQ product

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2585

2024-05-01 06:34 UTC, Royal-lobster commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
Hmm, i think its not there, but you can modify linkWrapper and other link elements to pass down isExternal prop, if its passed, then we can add the target blank and rel no refer and no follow rules 

![CleanShot 2024-05-01 at 12 02 55](https://github.com/EveripediaNetwork/ep-ui/assets/52039218/312e260f-dcd6-411b-89ef-19f8b86467ea)

2024-05-01 07:33 UTC, Aliiiu commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
> This i think we have Link component with chakra, it can take isExternal as prop

I only used the nextLink for our product links and link for others

2024-05-01 07:34 UTC, Aliiiu commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
> Hmm, i think its not there, but you can modify linkWrapper and other link elements to pass down isExternal prop, if its passed, then we can add the target blank and rel no refer and no follow rules. That way devs only need to keep track if they added isExternal or not
> 
> ![CleanShot 2024-05-01 at 12 02 55](https://private-user-images.githubusercontent.com/52039218/327064888-312e260f-dcd6-411b-89ef-19f8b86467ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDg3OTUsIm5iZiI6MTcxNDU0ODQ5NSwicGF0aCI6Ii81MjAzOTIxOC8zMjcwNjQ4ODgtMzEyZTI2MGYtZGNkNi00MTFiLTg5ZWYtMTlmOGI4NjQ2N2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA3MjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYzczMjA4NzhjY2U1ZjBjZTMwNjVlZDhhOTYyNTY2MGFiMzIyNzZmNDk2NGQwOWM4ZjZlYzg1OTIyYjMwZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I2dTvPn0pTtA7ViBtQzzht77yRrscrGsg3cL1DP2fRI)

the chakra link can take the isExternal props but i think it serves the same purpose as the `target='_blank'`

2024-05-01 07:41 UTC, Royal-lobster commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
Ahh thats fine, tho, if we pass isExternal prop to chakra link, does it also include nofollow and noreffer ?

2024-05-01 07:53 UTC, Aliiiu commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
No, it doesn't

2024-05-01 08:06 UTC, Royal-lobster commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
Hmm in that case i think probably we should handle it in linkWrapper

2024-05-01 12:41 UTC, Aliiiu commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
> Hmm, i think its not there, but you can modify linkWrapper and other link elements to pass down isExternal prop, if its passed, then we can add the target blank and rel no refer and no follow rules. That way devs only need to keep track if they added isExternal or not
> 
> ![CleanShot 2024-05-01 at 12 02 55](https://private-user-images.githubusercontent.com/52039218/327064888-312e260f-dcd6-411b-89ef-19f8b86467ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTE5NjgsIm5iZiI6MTcxNDU1MTY2OCwicGF0aCI6Ii81MjAzOTIxOC8zMjcwNjQ4ODgtMzEyZTI2MGYtZGNkNi00MTFiLTg5ZWYtMTlmOGI4NjQ2N2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA4MjEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOGM4YThjMWZhZTA2OTc1NmQ5OTMyYTFkNDEzMDFlZWMyNjdmYzI3OWQ4YjRhODI3ZTdkMjU0MjE2MWIwYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4PR-32cuRjmtNYxT-0jffPRmsP5NzplXNaQ6i5l7r8)

The issue with this update is that not all isExternal props need the rel='noreferrer noopener'. For example if we have want isExternal prop on a link to our other website we don't want to add rel='noreferrer noopener'

2024-05-01 12:45 UTC, Royal-lobster commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
Nope, for us we would for sure need rel noreferrer noopener always when there is target _blank

2024-05-01 12:51 UTC, Aliiiu commented on src/components/Landing/IQBar.tsx
> +import NextLink from 'next/link'
sorry i missed them, some external links need 'nofollow' while others don't, external links that are not our product needs.

2024-05-02 08:51 UTC, Adebesin-Cell approved these changes
<img width="1552" alt="Screenshot 2024-05-02 at 9 50 44 AM" src="https://github.com/EveripediaNetwork/ep-ui/assets/66301634/0dc9de1f-651e-4283-bf09-5db9ed4bb9af">

Upbit link doesn't work :))

2024-05-02 08:52 UTC, Adebesin-Cell requested changes
Same with binance

2024-05-02 09:04 UTC, Adebesin-Cell commented
Ha, weird. Prolly my network :))

2024-05-02 09:04 UTC, Adebesin-Cell approved these changes

2024-05-02 09:55 UTC, kesar approved these changes

2024-05-02 09:58 UTC, merged