User Profile Editing Bug
EveripediaNetwork/ep-ui pull request #1852
Opened 2024-05-22 13:20 UTC by Aliiiu

# User Profile Editing Bug

This PR works on resolving issues with users not being able to edit their details on the settings page

## How should this be tested?

1. Got to the settings page
2. Change any of the feeds

## Notes or observations

https://github.com/EveripediaNetwork/ep-ui/assets/67792966/2eb45ee9-e4ce-4fc3-9c62-59459b641647

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/2660

2024-05-22 13:40 UTC, Damola18 commented
Tested, this looks good.

2024-05-22 13:40 UTC, Damola18 approved these changes

2024-05-23 10:01 UTC, Softdev1 requested changes
Not yet fixed. Username is not updated and still showed "profile updated success toss"

2024-05-23 11:01 UTC, Aliiiu commented
> Not yet fixed. Username is not updated and still showed "profile updated success toss"

Tested it, it is working

https://github.com/EveripediaNetwork/ep-ui/assets/67792966/097e18ea-8e65-4ffb-a6fc-38a1c7dd3072

2024-05-26 15:04 UTC, Softdev1 commented
<img width="1440" alt="Screenshot 2024-05-26 at 16 00 36" src="https://github.com/EveripediaNetwork/ep-ui/assets/32770520/2dfe09a7-b637-46e2-80c4-eadc493a6bff">
this is the error i got

2024-05-27 07:53 UTC, Aliiiu commented
> <img alt="Screenshot 2024-05-26 at 16 00 36" width="1440" src="https://private-user-images.githubusercontent.com/32770520/333888981-2dfe09a7-b637-46e2-80c4-eadc493a6bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTY1OTMsIm5iZiI6MTcxNjc5NjI5MywicGF0aCI6Ii8zMjc3MDUyMC8zMzM4ODg5ODEtMmRmZTA5YTctYjYzNy00NmUyLTgwYzQtZWFkYzQ5M2E2YmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA3NTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MGM0MjkzZDBiMTY1NTE4NmE3NDAwZTE5NzU0YTdmNGMzYmI0ZTllNjlkNTJhN2Q1YzlhYmU0NjFkOTk5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWuaTvCYl5MuCEub4VcPSTLCAcd8Vg8-P4SMV-3Q25o"> this is the error i got

Now we can see the error, which wasn't the case before. The issue is from the backend and we need to resolve it. 

@AshakaE it is still not working

2024-05-27 09:16 UTC, Softdev1 approved these changes

2024-05-27 09:17 UTC, Softdev1 commented
Test-case for User Profile Editing Bug 

- User can now  edit profile details including Name, email, and other information
- Upon clicking the save button and refreshing the page, the entered information is updated.
- issues such as duplicate info have been fixed.

All test cases passed now welldone @Aliiiu  👍

2024-05-27 09:25 UTC, Adebesin-Cell commented on src/components/Settings/ProfileSettings/index.tsx
> +  useEffect(() => {
I think we don't need an effect to handle errors, it could be handled in the handleSubmit handler :))

2024-05-27 09:25 UTC, Adebesin-Cell commented on src/components/Settings/ProfileSettings/index.tsx
> +      const { toastTitle, toastMessage, toastType } = PostUserMessage(undefined)
Instead of passing undefined here, we can just call PostUserMessage and pass postProfileError, since it might be undefined hence it'll return the success message.

2024-05-27 09:26 UTC, Adebesin-Cell commented on package.json
> +    "graphql-request": "4.3.0",
Did we need a version bump?

2024-05-27 09:27 UTC, Aliiiu commented on package.json
> +    "graphql-request": "4.3.0",
yes, was unable to handle custom errors with the current version.

2024-05-27 09:27 UTC, Adebesin-Cell commented on package.json
> +    "graphql-request": "4.3.0",
Ha, okay 👍

2024-05-27 09:43 UTC, kesar commented on package.json
> +    "graphql-request": "4.3.0",
take in consideration that upgrade to a major release requires a full testing of the site. Have u consider what are the differences between 3.7 and 4.3 version of this library and retro compatibilities?

cc: @Softdev1 if you are testing this branch, you need to ensure everything works as expected not only the save because this is changing a library that its used across every single request.

2024-05-27 09:48 UTC, Aliiiu commented on package.json
> +    "graphql-request": "4.3.0",
Error handling on the previous version is not dynamic, we can't extract error messages. We can't also parse the error string. Using the new version, we can create a customer error to extract error message.

2024-05-27 09:49 UTC, Aliiiu commented on package.json
> +    "graphql-request": "4.3.0",
> Error handling on the previous version is not dynamic, we can't extract error messages. We can't also parse the error string. Using the new version, we can create a customer error to extract error message.

it was a bug that was fixed on that version

2024-05-27 09:49 UTC, kesar commented on package.json
> +    "graphql-request": "4.3.0",
also that version is 2y old. i wonder if we should update to 7 if we aim to refactor that part, but if so, most likely the right way of doing this is: 

- fix current issue w current grapqhl-request ( i doubt we need to update version to catch an error, then the whole site wouldnt be working) .
- create a follow up task for refactoring and use the latest graphql-request version

2024-05-27 09:59 UTC, Aliiiu commented on package.json
> +    "graphql-request": "4.3.0",
Updating to the latest version breaks a lot of things in the codebase. 4.3.0 was the one that resolved the issue. I will revert and create follow-up PR.

2024-05-27 10:04 UTC, kesar commented on package.json
> +    "graphql-request": "4.3.0",
okok nvm. lets then keep 4.3.0 but lets ensure we test everything else. 

I dont want to fix the update profile bug that its barely used by anyone and get a bug somewhere else where its a critical component.

2024-05-27 10:12 UTC, Aliiiu commented on src/components/Settings/ProfileSettings/index.tsx
> +  useEffect(() => {
The reason why I used a useEffect is because all request returns status 200 and the error won't be watched if I wrap the mutation in a try and catch.

2024-05-27 10:23 UTC, Adebesin-Cell commented on src/components/Settings/ProfileSettings/index.tsx
> +  useEffect(() => {
Ha, weird, but it's prolly meant to return error object perhaps, or @AshakaE ?

2024-05-27 10:32 UTC, Aliiiu commented on src/components/Settings/ProfileSettings/index.tsx
> +  useEffect(() => {
He said it's a graphql issue, all status is 200 for successful or failed request but the response is different for both

2024-05-27 10:42 UTC, Adebesin-Cell commented on src/components/Settings/ProfileSettings/index.tsx
> +  useEffect(() => {
FlaggingSystemModal we can use the same approach here then I believe.

2024-05-27 14:28 UTC, Aliiiu commented on src/components/Settings/ProfileSettings/index.tsx
> +  useEffect(() => {
@Adebesin-Cell resolved can you review again

2024-05-27 15:30 UTC, Adebesin-Cell commented on src/components/Settings/ProfileSettings/index.tsx
> +      console.log(response.error)
```suggestion
      console.log(response.error)
```

2024-05-27 15:30 UTC, Adebesin-Cell commented on src/components/Settings/ProfileSettings/index.tsx
> +    let errMsg
prolly make it string | undefined as type not any :))

2024-05-27 16:19 UTC, Adebesin-Cell commented on src/components/Settings/ProfileSettings/index.tsx
> +  useEffect(() => {
for sure!

2024-05-28 17:28 UTC, merged