New About Page Design
EveripediaNetwork/ep-ui pull request #1908
Opened 2024-06-25 15:50 UTC by Damola18

# Improvement of the About Page UI[WIP]

This PR 
- revamps the outlook of the about page
- updates all the sections on the about page including the history and mission
- updates employee profile

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2783

2024-06-26 09:18 UTC, Simplypheyie96 requested changes
- This animation is not working. Also it is quite small. The lines should also be pink (brand color)
<img width="662" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/a562591d-ff45-436d-8b6a-fcee39b70f7b">

- This section shouldn't have a drop shadow.
<img width="1466" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/7aa8f9fe-a671-4418-a31b-9b88976da403">

- On the history section, there should be more spacing between the header and the content.
<img width="1019" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/eb5d6342-e88f-498c-b590-417bd2031ac5">

- the pattern that's meant to be below the number is missing
<img width="393" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/74e7c093-d2b4-46f4-b6e1-83440509a551">

- There is a scroll bar indicator that shouldn't be there
<img width="758" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/e8c687b1-1ac9-42b8-802b-f50f7f7a692d">

- I realized the headings for each history is too big. so i will be adjusting this in the design too.
<img width="536" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/99dd572b-9860-4033-a436-51337fea5513">

- Let's add more padding between the content and footer too.
<img width="1495" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/33a0cb15-840c-46f9-b219-211f080b22df">

2024-06-26 09:33 UTC, Damola18 commented
> * This animation is not working. Also it is quite small. The lines should also be pink (brand color)
> 
> <img alt="image" width="662" src="https://private-user-images.githubusercontent.com/99387231/343088227-a562591d-ff45-436d-8b6a-fcee39b70f7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQyMDUsIm5iZiI6MTcxOTM5MzkwNSwicGF0aCI6Ii85OTM4NzIzMS8zNDMwODgyMjctYTU2MjU5MWQtZmY0NS00MzZkLThiNmEtZmNlZTM5YjcwZjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmZmMWEyNGRjZjE1MzNmMzFjNTFjYzQwZTc2NmI2MTk2ZDI4NjNhODZiZGE2YTk5ZmNlZmMxNTFiMzViZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cNowHsOmFVwRMiZdPbC1sXlwuPTkFNT5BV8kQRiiFOY">
> * This section shouldn't have a drop shadow.
> 
> <img alt="image" width="1466" src="https://private-user-images.githubusercontent.com/99387231/343090084-7aa8f9fe-a671-4418-a31b-9b88976da403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQyMDUsIm5iZiI6MTcxOTM5MzkwNSwicGF0aCI6Ii85OTM4NzIzMS8zNDMwOTAwODQtN2FhOGY5ZmUtYTY3MS00NDE4LWEzMWItOWI4ODk3NmRhNDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjg3M2Q5YzAzNWY0MjNlODFiNWNjNTM5ODk3MzZkMDU0M2VjMzcxYjk4MTMzZTcyZTBmNzM5NWU0YTk2NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e0XavzI3VZguFDaaCgbcbGx4YzA5xs-yJrC5dMu5llo">
> * On the history section, there should be more spacing between the header and the content.
> 
> <img alt="image" width="1019" src="https://private-user-images.githubusercontent.com/99387231/343090640-eb5d6342-e88f-498c-b590-417bd2031ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQyMDUsIm5iZiI6MTcxOTM5MzkwNSwicGF0aCI6Ii85OTM4NzIzMS8zNDMwOTA2NDAtZWI1ZDYzNDItZTg4Zi00OThjLWI1OTAtNDE3YmQyMDMxYWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNDg2NWUxYzgzNDBiYjVmNzlkYmIwN2U1NzkyMDA5MDA0NWQ4MTkyNzY5M2E3MmY3YTlmNTc1MDMxNTkzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.En39RYz05w-v1_G9aMGB9GHKB99wQknHtP0BLphZ4nQ">
> * the pattern that's meant to be below the number is missing
> 
> <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/99387231/343091162-74e7c093-d2b4-46f4-b6e1-83440509a551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQyMDUsIm5iZiI6MTcxOTM5MzkwNSwicGF0aCI6Ii85OTM4NzIzMS8zNDMwOTExNjItNzRlN2MwOTMtZDJiNC00NmY0LWI2ZTEtODM0NDA1MDlhNTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZDhkMDdiNjUzNjUzZDEyMjQyM2FjODMzOTIyYTAwMWUxY2RmZTI0NjRmY2E5MDA4NDlhNWE4MGM4MDFkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IU7lpscHp8BwtReidVWXW2NyCeL2p0hdT4VWCpZrzu0">
> * There is a scroll bar indicator that shouldn't be there
> 
> <img alt="image" width="758" src="https://private-user-images.githubusercontent.com/99387231/343091949-e8c687b1-1ac9-42b8-802b-f50f7f7a692d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQyMDUsIm5iZiI6MTcxOTM5MzkwNSwicGF0aCI6Ii85OTM4NzIzMS8zNDMwOTE5NDktZThjNjg3YjEtMWFjOS00MmI4LTgwMmItZjUwZjdmN2E2OTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MGI4ZDQzYWY5MDkyZjZiOGJlMmZkYWQ4ZTY2NGZjOWFjNDM0MDcyNmQ4YmZlNGVlNDVmZmVhOTRkNGMxYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6WOsPHv9GgB5Lln_WU04vDs4i3_7OGydOEA2IpZexY4">
> * I realized the headings for each history is too big. so i will be adjusting this in the design too.
> 
> <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/99387231/343092281-99dd572b-9860-4033-a436-51337fea5513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQyMDUsIm5iZiI6MTcxOTM5MzkwNSwicGF0aCI6Ii85OTM4NzIzMS8zNDMwOTIyODEtOTlkZDU3MmItOTg2MC00MDMzLWE0MzYtNTEzMzdmZWE1NTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZmUwNTY3MTAzNmZjOTI1Y2FkYTI1MzIyYTQwNjA1MTk2NDUzYTkwZjQ2MDI0NjlhNTEzYjI2Njg5NjQ2MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j3YC86TiYbgGDwEz2-O2ToZPtD5WXSsWM6AjPhsZjWw">
> * Let's add more padding between the content and footer too.
> 
> <img alt="image" width="1495" src="https://private-user-images.githubusercontent.com/99387231/343092551-33a0cb15-840c-46f9-b219-211f080b22df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQyMDUsIm5iZiI6MTcxOTM5MzkwNSwicGF0aCI6Ii85OTM4NzIzMS8zNDMwOTI1NTEtMzNhMGNiMTUtODQwYy00NmY5LWIyMTktMjExZjA4MGIyMmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OGY2ZDgzM2ZiODQxNGYzYWZkMGI3MDEwZGUzZTYxZjhmNDNmNzY3YzM1MmQ4NzEyMDU5NDM5MjhlODMzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lIwyQ6lGXGJ0SzTfTCGmJrL5b3RRjOHB22hFSlULNc">

Oh, let me check, something must have broken here, the images shows here. And yeah, i noticed the scrollbar and the pattern as well, i just added it. Let me check the images first please

2024-06-27 09:22 UTC, Softdev1 commented
I think there is a conflict between the design and implementation in the UI for some session 

- This is not what is in the design, kindly fix it 
<img width="1073" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/32770520/dffac23d-50cf-404b-9aa8-0a0aec038155">

- The dark mode text for this box should be white, not black 
<img width="1075" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/32770520/9a1b7b40-2aa2-4e9a-b668-183c7ae8a6cd">


Please I think it would be nice, let's try and resolve these issues

2024-06-27 09:31 UTC, Tolu-Mals commented
Nice work so far.

Here's what I noticed:

- The orbiting circle should be bigger than what we have at the moment, it should be like this
![Screenshot 2024-06-27 at 10 22 29 AM](https://github.com/EveripediaNetwork/ep-ui/assets/30352484/c36cf666-35a4-4b90-9d49-c18ceb440121)

- Also like Steve pointed out, the two big solid circles in the middle should not be the same size, on the design one is slightly smaller.

- The background color for the solid circles are different from the design. They should be more transparent such that the inner dashed lines should be clearly visible through the circles.

- The size of the white outline circles in the bigger solid pink circles are much smaller in the design, and one of them is actually a rounded square and not a circle

2024-06-27 09:47 UTC, Damola18 commented
> Nice work so far.
> 
> Here's what I noticed:
> 
> * The orbiting circle and IQ logo should be bigger than what we have at the moment, it should be like this
>   ![Screenshot 2024-06-27 at 10 22 29 AM](https://private-user-images.githubusercontent.com/30352484/343712956-c36cf666-35a4-4b90-9d49-c18ceb440121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODEwNzAsIm5iZiI6MTcxOTQ4MDc3MCwicGF0aCI6Ii8zMDM1MjQ4NC8zNDM3MTI5NTYtYzM2Y2Y2NjYtMzVhNC00YjkwLTlkNDktYzE4Y2ViNDQwMTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MjJjMTQzNDRlZWM4NTU0N2JjNjQ1MjZmNGYyN2Q4N2MwMmFiMjk2NDIyMmU1MDk5MTYwMjI0YzhlNjEwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xG-Hso2jsM_azeE5bhxItgmiLvUhevZ1h4909PW4Jac)
> * Also like Steve pointed out, the two big solid circles in the middle should not be the same size. On the design, one of the circles is slightly smaller.
> * The background color for the solid circles are different from the design. They should be more transparent such that the inner dashed lines should be clearly visible through the circles.
> * The size of the white outline circles in the bigger solid pink circles are much smaller in the design, and one of them is actually a rounded square and not a circle



> Nice work so far.
> 
> Here's what I noticed:
> 
> * The orbiting circle and IQ logo should be bigger than what we have at the moment, it should be like this
>   ![Screenshot 2024-06-27 at 10 22 29 AM](https://private-user-images.githubusercontent.com/30352484/343712956-c36cf666-35a4-4b90-9d49-c18ceb440121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODEwNzAsIm5iZiI6MTcxOTQ4MDc3MCwicGF0aCI6Ii8zMDM1MjQ4NC8zNDM3MTI5NTYtYzM2Y2Y2NjYtMzVhNC00YjkwLTlkNDktYzE4Y2ViNDQwMTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MjJjMTQzNDRlZWM4NTU0N2JjNjQ1MjZmNGYyN2Q4N2MwMmFiMjk2NDIyMmU1MDk5MTYwMjI0YzhlNjEwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xG-Hso2jsM_azeE5bhxItgmiLvUhevZ1h4909PW4Jac)
> * Also like Steve pointed out, the two big solid circles in the middle should not be the same size. On the design, one of the circles is slightly smaller.
> * The background color for the solid circles are different from the design. They should be more transparent such that the inner dashed lines should be clearly visible through the circles.
> * The size of the white outline circles in the bigger solid pink circles are much smaller in the design, and one of them is actually a rounded square and not a circle



> I think there is a conflict between the design and implementation in the UI for some session
> 
> * This is not what is in the design, kindly fix it
> 
> <img alt="image" width="1073" src="https://private-user-images.githubusercontent.com/32770520/343711201-dffac23d-50cf-404b-9aa8-0a0aec038155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODA0MzcsIm5iZiI6MTcxOTQ4MDEzNywicGF0aCI6Ii8zMjc3MDUyMC8zNDM3MTEyMDEtZGZmYWMyM2QtNTBjZi00MDRiLTlhYTgtMGEwYWVjMDM4MTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Mzk2MDU2NDEyOTg0OTE4MTAwOTYxMTUwNDYwOGY2ZTQ1OTllNmQ5ZTYxZDUxMTc1MWMwY2VmMWViY2YzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VoI0GKJQ7S7HBadzfWts8pQ6JtMPxvg7ocHxq4yzbUw">
> * The dark mode text for this box should be white, not black
> 
> <img alt="image" width="1075" src="https://private-user-images.githubusercontent.com/32770520/343711717-9a1b7b40-2aa2-4e9a-b668-183c7ae8a6cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODA0MzcsIm5iZiI6MTcxOTQ4MDEzNywicGF0aCI6Ii8zMjc3MDUyMC8zNDM3MTE3MTctOWExYjdiNDAtMmFhMi00ZTlhLWI2NjgtMTgzYzdhZThhNmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZmUxMzdiOWE2NjYyNDE4Mjk2NjJhY2Q3ZmI2Zjc5MTY2OTkwMmNlNTQxN2FhNTIwMzEwNTU1OTdlN2E0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bCK_16LRncNsuaD5102MtgFYnZ7AZ_jTV7KaUXUzTJ4">
> Please I think it would be nice, let's try and resolve these issues



> I think there is a conflict between the design and implementation in the UI for some session
> 
> * This is not what is in the design, kindly fix it
> 
> <img alt="image" width="1073" src="https://private-user-images.githubusercontent.com/32770520/343711201-dffac23d-50cf-404b-9aa8-0a0aec038155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODA0MzcsIm5iZiI6MTcxOTQ4MDEzNywicGF0aCI6Ii8zMjc3MDUyMC8zNDM3MTEyMDEtZGZmYWMyM2QtNTBjZi00MDRiLTlhYTgtMGEwYWVjMDM4MTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Mzk2MDU2NDEyOTg0OTE4MTAwOTYxMTUwNDYwOGY2ZTQ1OTllNmQ5ZTYxZDUxMTc1MWMwY2VmMWViY2YzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VoI0GKJQ7S7HBadzfWts8pQ6JtMPxvg7ocHxq4yzbUw">
> * The dark mode text for this box should be white, not black
> 
> <img alt="image" width="1075" src="https://private-user-images.githubusercontent.com/32770520/343711717-9a1b7b40-2aa2-4e9a-b668-183c7ae8a6cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODA0MzcsIm5iZiI6MTcxOTQ4MDEzNywicGF0aCI6Ii8zMjc3MDUyMC8zNDM3MTE3MTctOWExYjdiNDAtMmFhMi00ZTlhLWI2NjgtMTgzYzdhZThhNmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZmUxMzdiOWE2NjYyNDE4Mjk2NjJhY2Q3ZmI2Zjc5MTY2OTkwMmNlNTQxN2FhNTIwMzEwNTU1OTdlN2E0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bCK_16LRncNsuaD5102MtgFYnZ7AZ_jTV7KaUXUzTJ4">
> Please I think it would be nice, let's try and resolve these issues

Thanks for the observations, will check out and fix that

2024-06-27 09:54 UTC, Simplypheyie96 requested changes
It's a lot better than what we had before. Great job.
In addition to those pointed out:

- the space between the cards is huge and the border effect (magic cards) is missing.
it also makes it look weird in md breakpoint.
<img width="1409" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/150e6870-316c-4c77-a341-c656f124c88c">
<img width="477" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/464cf100-4774-42e5-a4be-1de099f04432">

- The pink card is still larger in width than the rest of the page.
<img width="1721" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/4250d0fc-efa1-45ea-b9ad-15777cdbead6">
- This should remain the same even in dark mode.
<img width="1553" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/6de3628c-3c64-48dc-b7d7-02accba29ea2">

2024-06-27 10:07 UTC, Simplypheyie96 commented
> Thanks very much, working on the changes highlighted.
> @Simplypheyie96 for the circles, can we have the different circle for the other one then. I only have one for both (for the ones you masked)

I have helped create those circles, but you will need to adjust their sizes in code to fit the orbiting circle.

2024-06-27 10:09 UTC, Damola18 commented
> > Thanks very much, working on the changes highlighted.
> > @Simplypheyie96 for the circles, can we have the different circle for the other one then. I only have one for both (for the ones you masked)
> 
> I have helped create those circles, but you will need to adjust their sizes in code to fit the orbiting circle.

Thanks

2024-06-27 10:12 UTC, Damola18 commented
https://github.com/EveripediaNetwork/ep-ui/assets/50779080/c7afebfd-8338-471d-bd22-d041f657d72b

@Simplypheyie96 , this is for the card

2024-06-27 10:15 UTC, Simplypheyie96 commented
> https://github.com/EveripediaNetwork/ep-ui/assets/50779080/c7afebfd-8338-471d-bd22-d041f657d72b
> 
> @Simplypheyie96 , this is for the card border effect .

Does it trigger only on hover?
It should work like the one we have on iq gpt

2024-06-27 10:18 UTC, Damola18 commented
> > Screen.Recording.2024-06-27.at.11.08.17.mov
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > @Simplypheyie96 , this is for the card border effect .
> 
> Does it trigger only on hover? It should work like the one we have on iq gpt

You mean The magic card effect or border beam effect?

2024-06-27 10:22 UTC, Simplypheyie96 commented
> You mean The magic card effect or border beam effect?

this is what we are using. Border beam.
https://magicui.design/docs/components/border-beam

2024-06-27 10:24 UTC, Damola18 commented
> I think there is a conflict between the design and implementation in the UI for some session
> 
> * This is not what is in the design, kindly fix it
> 
> <img alt="image" width="1073" src="https://private-user-images.githubusercontent.com/32770520/343711201-dffac23d-50cf-404b-9aa8-0a0aec038155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODA1OTYsIm5iZiI6MTcxOTQ4MDI5NiwicGF0aCI6Ii8zMjc3MDUyMC8zNDM3MTEyMDEtZGZmYWMyM2QtNTBjZi00MDRiLTlhYTgtMGEwYWVjMDM4MTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1M2ZiMGQ2MWE0OWQ2ZWEzNDI1MTdlMTgyMTQ0YTFiYTc3NTMzNTM2ZWIzNDlkZDdkNTNjZTI2NjQyODM5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kfq_OHLXtevo9jwaX0x5hA1dH7ewfc9JnDAkXahxlYc">
> * The dark mode text for this box should be white, not black
> 
> <img alt="image" width="1075" src="https://private-user-images.githubusercontent.com/32770520/343711717-9a1b7b40-2aa2-4e9a-b668-183c7ae8a6cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODA1OTYsIm5iZiI6MTcxOTQ4MDI5NiwicGF0aCI6Ii8zMjc3MDUyMC8zNDM3MTE3MTctOWExYjdiNDAtMmFhMi00ZTlhLWI2NjgtMTgzYzdhZThhNmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMGVlMDQ1ZDgyMjljNTE0OGM2NDc1YjA2MzVmNzc0ZWI5MmUyYzg4NjYyNDA0Y2JkOWM5NDk4YjRiMjRjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mo4VMH58dWUlloty7rZ9so0K9Pi-6Peq2SoIDIYptmU">
> Please I think it would be nice, let's try and resolve these issues



> > You mean The magic card effect or border beam effect?
> 
> this is what we are using. Border beam. https://magicui.design/docs/components/border-beam

Alright

2024-06-27 16:49 UTC, Simplypheyie96 commented
- Let's revisit the implementation of the circles. Currently, the size makes them overlap significantly, giving them a cluttered look. The previous implementation looked better than this. let's implement such that the circles won't overlap. I think that would be better if they are all orbiting. The bigger circle has covered up the dotted one too.
<img width="953" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/b2592268-280a-4970-bde3-ef7c5f360e46">

---

- this is what it looks like on mobile
<img width="337" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/22eb585b-d8e9-443b-a4bd-3c4827b86815">

---

- the gradient here is missing on the tablet view and on mobile view too.
<img width="485" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/59c53954-3ab1-40bc-8d2b-e629431b081b">
<img width="363" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/877408a0-86df-47c5-b457-81c5d8824488">

---

- this section on the tablet view is not properly aligned. It's meant to be left-aligned. right now, it is left-aligned and centered at the same time which is giving it a weird look

<img width="476" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/99387231/c383ef68-0d53-4d5d-a05c-67de0e2b2b31">


Every other thing is spot on now.
@Damola18

2024-07-02 08:53 UTC, Simplypheyie96 approved these changes

2024-07-02 09:34 UTC, Tolu-Mals commented
![Screenshot 2024-07-02 at 10 26 35 AM](https://github.com/EveripediaNetwork/ep-ui/assets/30352484/38244315-8058-4de9-81e4-5dcb93a4d62c)

These circles should be transparent. I should be able to see the dashed lines through it.

Look at the design

![Screenshot 2024-07-02 at 10 28 41 AM](https://github.com/EveripediaNetwork/ep-ui/assets/30352484/e1e82d91-6363-4c00-b432-59e653c1ff7f)

Also the IQ logo should be bigger. And then the white outline circle and rounded rectangle should be smaller.

2024-07-02 09:45 UTC, Damola18 commented
> ![Screenshot 2024-07-02 at 10 26 35 AM](https://private-user-images.githubusercontent.com/30352484/344964300-38244315-8058-4de9-81e4-5dcb93a4d62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxOTEsIm5iZiI6MTcxOTkxMjg5MSwicGF0aCI6Ii8zMDM1MjQ4NC8zNDQ5NjQzMDAtMzgyNDQzMTUtODA1OC00ZGU5LTgxZTQtNWRjYjkzYTRkNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZGVlNjRiY2FhZTViODg2MTA0NmNmMmE1NGNkMTEzOGJlMDhlNjM5MTM5NWJiYWZiZDFjNDIwY2YxYWUwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TW7lrygrKwQ9auLmXWVFwKYdo6mERiQlzlTaTy0ZnRU)
> 
> These circles should be transparent. I should be able to see the dashed lines through it.
> 
> Look at the design
> 
> ![Screenshot 2024-07-02 at 10 28 41 AM](https://private-user-images.githubusercontent.com/30352484/344966074-e1e82d91-6363-4c00-b432-59e653c1ff7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxOTEsIm5iZiI6MTcxOTkxMjg5MSwicGF0aCI6Ii8zMDM1MjQ4NC8zNDQ5NjYwNzQtZTFlODJkOTEtNjM2My00YzAwLWI0MzItNTllNjUzYzFmZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NDk2MmJkMzU3ZWVkYzg4MDMwYjFiYTU0YjVmZjQ0OGVhNDQ3NjVjOWIxM2Q0MmQ1NGJmMzM1MGUyMDZlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pU2xqlwSYV1g3Ojy0W5CZ72OM0mdHR_KV1D1DeRef7Q)
> 
> Also the IQ logo should be bigger. And then the white outline circle and rounded rectangle should be smaller.

The zIndex used underlays or overlays all the two dashed lines because I am mapping through all of them due to the structure of the Orbit Circle.

2024-07-02 09:47 UTC, Simplypheyie96 commented
> ![Screenshot 2024-07-02 at 10 26 35 AM](https://private-user-images.githubusercontent.com/30352484/344964300-38244315-8058-4de9-81e4-5dcb93a4d62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxODAsIm5iZiI6MTcxOTkxMjg4MCwicGF0aCI6Ii8zMDM1MjQ4NC8zNDQ5NjQzMDAtMzgyNDQzMTUtODA1OC00ZGU5LTgxZTQtNWRjYjkzYTRkNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NTBmMjA2YWNkOTZmNDc2MTFmZTZmMjNiNzYyMDY3NmI1NGZiOTZjMWJhZmU0MWFkNDhjMmQyOGE2MTU2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-fUa4tdjyztYlqg3k4Rl_T7SAxH0uppsm4olUuQKSjo)
> 
> These circles should be transparent. I should be able to see the dashed lines through it.
> 
> Look at the design
> 
> ![Screenshot 2024-07-02 at 10 28 41 AM](https://private-user-images.githubusercontent.com/30352484/344966074-e1e82d91-6363-4c00-b432-59e653c1ff7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxODAsIm5iZiI6MTcxOTkxMjg4MCwicGF0aCI6Ii8zMDM1MjQ4NC8zNDQ5NjYwNzQtZTFlODJkOTEtNjM2My00YzAwLWI0MzItNTllNjUzYzFmZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMTQ1NTU3MzZlNWI1Y2MxMDMwZGMxYzIxMjFmODc1MDU0YmMyZWExODJiOWY2OTM2YjkzYzg4MTM5YWZkZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UgIg4Aa1kfV1c88cYHjgHzL5i9l56JW189GjQcn39lI)
> 
> Also the IQ logo should be bigger. And then the white outline circle and rounded rectangle should be smaller.

I think the current state is acceptable. The assets are challenging to consolidate because they were separated by masking them out from the SVG. I had to mask them out.

Regarding the logo, we've reviewed it, and increasing its size further would make it too large on mobile devices. Unless there's a way to enlarge the logo on desktop without affecting the mobile/tablet view (@Damola18), we should keep the current size.

Also, I'm uncertain if we can make the circulating orbit look exactly like the design. The design is an SVG and isn't animated, which complicates replicating its exact appearance.

2024-07-02 09:58 UTC, Tolu-Mals commented
> > ![Screenshot 2024-07-02 at 10 26 35 AM](https://private-user-images.githubusercontent.com/30352484/344964300-38244315-8058-4de9-81e4-5dcb93a4d62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxODAsIm5iZiI6MTcxOTkxMjg4MCwicGF0aCI6Ii8zMDM1MjQ4NC8zNDQ5NjQzMDAtMzgyNDQzMTUtODA1OC00ZGU5LTgxZTQtNWRjYjkzYTRkNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NTBmMjA2YWNkOTZmNDc2MTFmZTZmMjNiNzYyMDY3NmI1NGZiOTZjMWJhZmU0MWFkNDhjMmQyOGE2MTU2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-fUa4tdjyztYlqg3k4Rl_T7SAxH0uppsm4olUuQKSjo)
> > These circles should be transparent. I should be able to see the dashed lines through it.
> > Look at the design
> > ![Screenshot 2024-07-02 at 10 28 41 AM](https://private-user-images.githubusercontent.com/30352484/344966074-e1e82d91-6363-4c00-b432-59e653c1ff7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxODAsIm5iZiI6MTcxOTkxMjg4MCwicGF0aCI6Ii8zMDM1MjQ4NC8zNDQ5NjYwNzQtZTFlODJkOTEtNjM2My00YzAwLWI0MzItNTllNjUzYzFmZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMTQ1NTU3MzZlNWI1Y2MxMDMwZGMxYzIxMjFmODc1MDU0YmMyZWExODJiOWY2OTM2YjkzYzg4MTM5YWZkZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UgIg4Aa1kfV1c88cYHjgHzL5i9l56JW189GjQcn39lI)
> > Also the IQ logo should be bigger. And then the white outline circle and rounded rectangle should be smaller.
> 
> I think the current state is acceptable. The assets are challenging to consolidate because they were separated by masking them out from the SVG. I had to mask them out.
> 
> Regarding the logo, we've reviewed it, and increasing its size further would make it too large on mobile devices. Unless there's a way to enlarge the logo on desktop without affecting the mobile/tablet view (@Damola18), we should keep the current size.
> 
> Also, I'm uncertain if we can make the circulating orbit look exactly like the design. The design is an SVG and isn't animated, which complicates replicating its exact appearance.

he can make the image responsive, it'll be larger on desktop, smaller on mobile.

2024-07-02 10:08 UTC, Tolu-Mals commented on public/locales/ko/about.json
> +  "aboutFeatTitle": "",
I think you forgot to add this translation

2024-07-02 10:10 UTC, Tolu-Mals commented on public/locales/ko/about.json
> +  "aboutNavinDescription": "",
The translation  here is empty as well

2024-07-02 10:13 UTC, Tolu-Mals commented on public/locales/zh/about.json
>    "aboutFeatContent": "我们是今天互联网上关于区块链技术和加密货币相关一切事物的首要知识来源。我们的愿景是使区块链在全世界更容易被发现和访问，并赋予用户他们可以信赖的信息。",
`aboutFeatTitle` for chinese is missing here.

2024-07-02 10:20 UTC, Damola18 commented
> > > ![Screenshot 2024-07-02 at 10 26 35 AM](https://private-user-images.githubusercontent.com/30352484/344964300-38244315-8058-4de9-81e4-5dcb93a4d62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxOTEsIm5iZiI6MTcxOTkxMjg5MSwicGF0aCI6Ii8zMDM1MjQ4NC8zNDQ5NjQzMDAtMzgyNDQzMTUtODA1OC00ZGU5LTgxZTQtNWRjYjkzYTRkNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZGVlNjRiY2FhZTViODg2MTA0NmNmMmE1NGNkMTEzOGJlMDhlNjM5MTM5NWJiYWZiZDFjNDIwY2YxYWUwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TW7lrygrKwQ9auLmXWVFwKYdo6mERiQlzlTaTy0ZnRU)
> > > These circles should be transparent. I should be able to see the dashed lines through it.
> > > Look at the design
> > > ![Screenshot 2024-07-02 at 10 28 41 AM](https://private-user-images.githubusercontent.com/30352484/344966074-e1e82d91-6363-4c00-b432-59e653c1ff7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxOTEsIm5iZiI6MTcxOTkxMjg5MSwicGF0aCI6Ii8zMDM1MjQ4NC8zNDQ5NjYwNzQtZTFlODJkOTEtNjM2My00YzAwLWI0MzItNTllNjUzYzFmZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NDk2MmJkMzU3ZWVkYzg4MDMwYjFiYTU0YjVmZjQ0OGVhNDQ3NjVjOWIxM2Q0MmQ1NGJmMzM1MGUyMDZlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pU2xqlwSYV1g3Ojy0W5CZ72OM0mdHR_KV1D1DeRef7Q)
> > > Also the IQ logo should be bigger. And then the white outline circle and rounded rectangle should be smaller.
> > 
> > 
> > The zIndex used underlays or overlays all the two dashed lines because I am mapping through all of them due to the structure of the Orbit Circle.
> 
> I don't understand, but it's fine, if it's not possible

I meant the zIndex to control the position of the icon and the dashed line only goes any of the two ways

2024-07-02 10:30 UTC, Tolu-Mals commented on src/components/About/AboutFeatures.tsx
> +          className="relative"
I don't think we need this

2024-07-02 10:32 UTC, Tolu-Mals commented on src/components/About/AboutFeaturesCard.tsx
> +    <MagicCard className="flex w-full cursor-pointer flex-col text-left overflow-hidden bg-white rounded-xl border border-gray200 dark:border-gray700">
```suggestion
    <MagicCard className="flex w-full cursor-pointer flex-col text-left overflow-hidden bg-white rounded-xl border border-gray-200 dark:border-gray-700">
```

Did you mean to write this?

2024-07-02 10:42 UTC, Tolu-Mals commented on yarn.lock
we can add `yarn.lock` to `.gitignore`

2024-07-02 12:40 UTC, Damola18 commented
@Tolu-Mals @Simplypheyie96  made the changes as reviewed

2024-07-02 14:18 UTC, Damola18 commented
> you need to run this `git rm --cached yarn.lock` to stop `yarn.lock` from being tracked too. See if you can push after that.

Yeah, i just did

2024-07-02 14:21 UTC, Tolu-Mals commented
please fix the build error


> > you need to run this `git rm --cached yarn.lock` to stop `yarn.lock` from being tracked too. See if you can push after that.
> 
> Yeah, i just did

please fix the build error

2024-07-02 14:21 UTC, Damola18 commented
> you need to run this `git rm --cached yarn.lock` to stop `yarn.lock` from being tracked too. See if you can push after that.

Checking vercel logs to find out what the build error is

2024-07-04 09:23 UTC, Tolu-Mals approved these changes

2024-07-04 10:28 UTC, Softdev1 approved these changes

2024-07-04 10:30 UTC, merged