Properly formatted the gas limit error and also resolved overflow on …
EveripediaNetwork/ep-ui pull request #1921
Opened 2024-07-05 11:59 UTC by Yomzy2223

…lengthy error

# PR title goes here

_PR description goes here_

## How should this be tested?

1. Step one
2. Step two
3. ...

## Notes or observations

_jot down something here_

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/ISSUE_NUMBER_GOES_HERE

2024-07-05 12:05 UTC, kesar commented on src/components/CreateWiki/EditorModals/WikiProcessModal.tsx
> -                    activeStep={activeStep}
are u sure about this change? not sure how it related to the issue

2024-07-05 12:07 UTC, kesar requested changes

2024-07-05 12:07 UTC, kesar commented on src/components/CreateWiki/EditorModals/WikiProcessModal.tsx
> +  const message = msg.match(messageInMsg)
now we have msg message and messageInMsg in the same component. This looks very confusing.

create a function outside of the component that receives a msg and return the proper message. Also ensure this should be done at this level and not in the previous level because we are already passing msg in props which leads me to think that perhaps the refining of msg needs to be done in the previous step.

2024-07-05 12:18 UTC, Yomzy2223 commented on src/components/CreateWiki/EditorModals/WikiProcessModal.tsx
> +  const message = msg.match(messageInMsg)
The messageInMsg helps match whether or not there is a message in the msg coming from the props, in the gas limit error message instance for example. I'll create a function outside the component as you said, will receive the message and return a proper message as you said.

<img width="1440" alt="Screenshot 2024-07-04 at 16 35 44" src="https://github.com/EveripediaNetwork/ep-ui/assets/85405629/04eb30e8-ca8e-4536-8e07-1a4b44176ac0">

2024-07-05 14:51 UTC, Yomzy2223 commented on src/components/CreateWiki/EditorModals/WikiProcessModal.tsx
> -                    activeStep={activeStep}
Oh, made this change just for testing. Corrected now.

2024-07-06 15:09 UTC, kesar approved these changes

2024-07-08 13:59 UTC, Adebesin-Cell approved these changes

2024-07-08 14:01 UTC, Adebesin-Cell commented on src/hooks/useGetSignedHash.ts
> +    const properMsg = hasInnerMsg ? hasInnerMsg[1] : msg
perhaps we rename variables, message instead of message, then proper message can be extractedMessage?

2024-07-08 14:05 UTC, Yomzy2223 commented on src/hooks/useGetSignedHash.ts
> +    const properMsg = hasInnerMsg ? hasInnerMsg[1] : msg
True. Will look into that now. Thanks.

2024-07-09 12:44 UTC, Softdev1 commented
When writing a pull request (PR), it is important to provide a proper title, description, and a guide on how to test the PR.@Yomzy2223 
<img width="974" alt="image" src="https://github.com/EveripediaNetwork/ep-ui/assets/32770520/1a65e6ad-77fc-42cf-a12e-adf75c4f5974">

2024-07-09 14:27 UTC, Softdev1 approved these changes

2024-07-09 14:29 UTC, merged