Revamped Explorer list on wiki details
EveripediaNetwork/ep-ui pull request #1947
Opened 2024-07-18 11:05 UTC by Yomzy2223

# Revamped Explorer list on wiki details

## How should this be tested?

1. Go to wiki details page
2. Click on "Edit Wiki Details" from the right panel
3. Check Links and Link Wikis dropdown

## Notes or observations

_Also replaced Link Wikis select component with the new one_

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2906

2024-07-18 11:09 UTC, Yomzy2223 commented
Before:
<img width="1440" alt="Screenshot 2024-07-18 at 12 02 06" src="https://github.com/user-attachments/assets/1e02ba19-8d4f-41a4-874f-261b6083d6e5">

After:
<img width="1440" alt="Screenshot 2024-07-18 at 11 59 15" src="https://github.com/user-attachments/assets/c679017d-589f-4454-a9b9-8daa221b284a">

2024-07-18 11:35 UTC, Simplypheyie96 requested changes
The color for dark mode should be gray 800. I apologize for forgetting to implement the dark mode and for not considering that you are new. The dropdowns shouldn't be different from the modal. The contrast right now is huge.
<img width="276" alt="image" src="https://github.com/user-attachments/assets/8d23f76c-6dd7-4e46-9455-8ae06ba4db4e">

2024-07-18 11:42 UTC, Softdev1 approved these changes
Nice

2024-07-18 11:51 UTC, Yomzy2223 commented
> The color for dark mode should be gray 800. I apologize for forgetting to implement the dark mode and for not considering that you are new. The dropdowns shouldn't be different from the modal. The contrast right now is huge. <img alt="image" width="276" src="https://private-user-images.githubusercontent.com/99387231/349937916-8d23f76c-6dd7-4e46-9455-8ae06ba4db4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDMxMzUsIm5iZiI6MTcyMTMwMjgzNSwicGF0aCI6Ii85OTM4NzIzMS8zNDk5Mzc5MTYtOGQyM2Y3NmMtNmRkNy00ZTQ2LTk0NTUtOGFlMDZiYTRkYjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDExNDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZDlmODk3OTc2YjkyY2NkYmMwMTgzOWNhZTc4MDUzOWJhYzZkYjAxNmYyYzJjODMyOTBhYzdiNDIwMzE5NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.up-brBVmbAVjGccfvg5SCnE3Q1a995Orqkcuk9ZJlVg">
> 
> [https://www.figma.com/design/wosuJaHeV318k1ON82CZpo/🧠-IQ.wiki?node-id=34110-115000&t=rRzhVUmN6JAWLEJH-11](https://www.figma.com/design/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.wiki?node-id=34110-115000&t=rRzhVUmN6JAWLEJH-11) <img alt="image" width="1022" src="https://private-user-images.githubusercontent.com/99387231/349940031-7945abe6-3fac-4ea0-bc64-e1cbcf727927.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDMxMzUsIm5iZiI6MTcyMTMwMjgzNSwicGF0aCI6Ii85OTM4NzIzMS8zNDk5NDAwMzEtNzk0NWFiZTYtM2ZhYy00ZWEwLWJjNjQtZTFjYmNmNzI3OTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDExNDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTdhZTlmYzIwZTEyOWIzMTc4YzYzM2NhYWUzNmM2ODljZDYzYjJiYmU5ZDA2MDM5NGMyMGQ4NTk1MGRjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5d19rvv_cigQJQCiXqcdbBVGmK_aGSJvesiY8IIx7zc">

Oh, okay. It's completely fine. Will correct that now, thank you.

2024-07-18 13:41 UTC, Simplypheyie96 commented
It looks like this on mobile, you might want to check that out. 
@Yomzy2223 
<img width="208" alt="image" src="https://github.com/user-attachments/assets/9e0e6fe7-9175-4e6d-ac2b-b82a2f1652c0">

2024-07-18 15:30 UTC, Tolu-Mals commented on src/components/ui/popover.tsx
> +        'z-[9999] w-72 rounded-md border border-slate-200 bg-white p-4 text-slate-950 shadow-2xl outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out
don't hardcode the color values, check similar components too see what they used

2024-07-18 15:55 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +        'flex h-8 w-full rounded-md bg-transparent py-3 text-xs md:text-sm outline-none disabled:cursor-not-allowed disabled:opacity-50 dark:text-[#FFFFFFCC]',
here as well, don't hard code the color value

2024-07-18 15:55 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +    className="flex items-center px-3 m-1 -mx-1 bg-[#F5F9FF] dark:bg-[#FFFFFF0F] rounded-lg"
and here

2024-07-18 15:56 UTC, Tolu-Mals commented
check through and see where you can remove hard coded values

2024-07-19 09:08 UTC, Simplypheyie96 approved these changes
Looks great now

2024-07-19 16:27 UTC, Tolu-Mals commented on src/components/ui/popover.tsx
> +        'z-[9999] w-72 rounded-md border border-slate-200 bg-white p-4 text-slate-950 shadow-2xl outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out
you missed this one

2024-07-19 16:28 UTC, Tolu-Mals commented on src/components/ui/popover.tsx
> +        'z-[9999] w-72 rounded-md border border-slate-200 bg-white p-4 text-slate-950 shadow-2xl outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out
you missed this one

2024-07-22 09:06 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +      'flex h-full w-full flex-col overflow-hidden rounded-md bg-white text-gray800 dark:bg-gray800 dark:text-white dark:text-opacity-[92] px-2',
`text-gray800` should be `text-gray-800`

2024-07-22 09:06 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +        <Command className="[&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-gray500 [&_[cmdk-group]:not([hidden])_~[cmdk-group]]:pt-0 [&_[cmdk-group]]
`text-gray500` should be `text-gray-500`

2024-07-22 09:06 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +      'overflow-hidden p-1 text-gray800 [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:te
same issue here

2024-07-22 09:06 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +    className={cn('-mx-1 h-px bg-white dark:text-gray800', className)}
fix here too

2024-07-22 09:06 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +      'relative flex cursor-pointer items-center rounded-md px-2 py-1.5 text-xs md:text-sm outline-none aria-selected:bg-blue0 aria-selected:text-gray800 aria-disabled:cursor-not-allowed aria-disable
and here

2024-07-22 09:06 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +        'ml-auto text-xs tracking-widest text-gray500 dark:text-gray400',
and here

2024-07-22 13:49 UTC, Yomzy2223 commented on src/components/ui/command.tsx
> +      'flex h-full w-full flex-col overflow-hidden rounded-md bg-white text-gray800 dark:bg-gray800 dark:text-white dark:text-opacity-[92] px-2',
The extended colors in the tailwind config were all set in this format. And I think it's better, rather than overriding tailwind default palette.

2024-07-22 13:49 UTC, Yomzy2223 commented on src/components/ui/command.tsx
> +        <Command className="[&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-gray500 [&_[cmdk-group]:not([hidden])_~[cmdk-group]]:pt-0 [&_[cmdk-group]]
The extended colors in the tailwind config were all set in this format. And I think it's better, rather than overriding tailwind default palette.

2024-07-22 13:50 UTC, Yomzy2223 commented on src/components/ui/command.tsx
> +      'overflow-hidden p-1 text-gray800 [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:te
The extended colors in the tailwind config were all set in this format. And I think it's better, rather than overriding tailwind default palette.

2024-07-22 13:50 UTC, Yomzy2223 commented on src/components/ui/command.tsx
> +        'ml-auto text-xs tracking-widest text-gray500 dark:text-gray400',
The extended colors in the tailwind config were all set in this format. And I think it's better, rather than overriding tailwind default palette.

2024-07-22 13:51 UTC, Yomzy2223 commented on src/components/ui/command.tsx
> +      'relative flex cursor-pointer items-center rounded-md px-2 py-1.5 text-xs md:text-sm outline-none aria-selected:bg-blue0 aria-selected:text-gray800 aria-disabled:cursor-not-allowed aria-disable
The extended colors in the tailwind config were all set in this format. And I think it's better, rather than overriding tailwind default palette.

2024-07-22 15:44 UTC, Tolu-Mals commented on src/components/ui/command.tsx
> +        'ml-auto text-xs tracking-widest text-gray500 dark:text-gray400',
I don't understand. Can you explain what you mean? or share some reference

2024-07-22 18:18 UTC, Tolu-Mals approved these changes

2024-07-22 18:25 UTC, merged