Event updates
EveripediaNetwork/ep-ui pull request #1954
Opened 2024-07-19 16:40 UTC by Aliiiu

# Reworking Events 

This PR works on improving the user experience on the event page

## How should this be tested?

1. Got to the event page
2. Check to see if you can see events in descending order
3. Test other filters to see if it works

## Notes or observations

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/5370ba05-cbbe-4f79-87d1-2924a72adb3e">

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2909

2024-07-24 09:31 UTC, Royal-lobster commented on src/components/Event/EventInterest.tsx
> +        // startDate: dateFormater(new Date()),
```suggestion
```

2024-07-24 09:32 UTC, Royal-lobster approved these changes

2024-07-24 09:40 UTC, Tolu-Mals commented
The images in the slides are stretched. It becomes very apparent on mobile viewports

![Screenshot](https://github.com/user-attachments/assets/d9b1b65e-6baf-4daf-8297-6f34ff7c3e36)

2024-07-24 09:48 UTC, Tolu-Mals commented
the pointer should switch to a cursor when click the tags in 'interests' and 'filter'

2024-07-24 09:55 UTC, Tolu-Mals commented
![Screenshot 2024-07-24 at 10 55 01 AM](https://github.com/user-attachments/assets/362cd57f-9b56-4c06-9158-98996e316482)

The description text is too small

2024-07-24 09:58 UTC, Tolu-Mals commented
I feel like the description here is too small as well, maybe sync with Feyi on this

![Screenshot 2024-07-24 at 10 57 53 AM](https://github.com/user-attachments/assets/4d0d9c3d-fb41-441e-9ff3-d951362ae6fc)

2024-07-24 10:02 UTC, Tolu-Mals commented
the text in the tags are also really small

![Screenshot 2024-07-24 at 11 00 01 AM](https://github.com/user-attachments/assets/ef1c1a62-504e-4ffa-9be8-5d0dc4d9f6d5)

2024-07-24 10:14 UTC, Tolu-Mals commented
sync with Feyi on all the design changes I suggested

2024-07-24 10:50 UTC, Aliiiu commented
> Also, when are we implementing these guys
> 
> ![Screenshot 2024-07-24 at 10 51 57 AM](https://private-user-images.githubusercontent.com/30352484/351667080-775976ca-9ec6-4693-ac6a-95d382abfcf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTUwNjIsIm5iZiI6MTcyMTgxNDc2MiwicGF0aCI6Ii8zMDM1MjQ4NC8zNTE2NjcwODAtNzc1OTc2Y2EtOWVjNi00NjkzLWFjNmEtOTVkMzgyYWJmY2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA5NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MjI5MTM1ZGI0MzFkOGFhMjU3NzhiOTMyMTAzY2Y0OTRlNzc3ZTZkYWY5Mzk4ODcxODcwM2EyZTQ4Yjc3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mMfj1sQbl8chPRGXuI10wpgazwkJdbwKTXfm__GKMLw)

I have implemented them but i am not sure if it is a good user experience to see old nearby events or popular events

2024-07-24 10:54 UTC, Aliiiu commented
> sync with Feyi on all the design changes I suggested

I feel like when you view them on your phone you won't get the same experience for the font size

2024-07-24 11:07 UTC, Aliiiu commented
> the pointer should switch to a cursor when click the tags in 'interests' and 'filter'


https://github.com/user-attachments/assets/91b7fbec-f635-47ab-8b99-aae9bce8f644

That's the behavior. is this not what you are talking about?

2024-07-24 11:24 UTC, Tolu-Mals commented
> > the pointer should switch to a cursor when click the tags in 'interests' and 'filter'
> 
>  Screen.Recording.2024-07-24.at.12.01.22.mov 
> That's the behavior. is this not what you are talking about?

yes. weird it's not like that on my end. ignore that then.

2024-07-24 12:27 UTC, Simplypheyie96 requested changes
- Images are stretched
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/0f0b3a5e-328d-4a46-b463-6a5e759cd78d">

- Let's make "clear all" button inactive when there is no filter to clear.
- All fonts are fine.
- Text is too close with content (this is on md bp)
<img width="307" alt="image" src="https://github.com/user-attachments/assets/9d5cdf20-1e69-4e09-8a47-7fcc8bd80ad8">
- On mobile, let's have the date and tags a little bigger. 
<img width="249" alt="image" src="https://github.com/user-attachments/assets/bceec13a-08d4-4f42-b4b7-df13cbbf7802">

(so sorry about this: reviewed and thought i already submitted the review

2024-07-24 16:01 UTC, Simplypheyie96 approved these changes
Let's hide sections for where there is no data when this goes live.

2024-07-24 19:02 UTC, Aliiiu commented
> Let's hide sections for where there is no data when this goes live.

That's what this issue solves, we want it to be populated even though the data is outdated

2024-07-25 09:42 UTC, Tolu-Mals approved these changes
looks good ✨

2024-07-25 09:44 UTC, Softdev1 approved these changes
Awesome fix

2024-07-25 09:47 UTC, merged