Resolving EditWiki Validation Error
EveripediaNetwork/ep-ui pull request #1977
Opened 2024-07-24 22:19 UTC by Aliiiu

# Resolving EditWiki Validation Error

This PR works on resolving the validation error when a user tries to add event details for a wiki

## How should this be tested?

1. Navigate to the create-wiki page
2. Click on Edit wiki
3. Try to add an event wiki details 

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2948

2024-07-25 12:11 UTC, Softdev1 approved these changes
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/3c9cbb47-9de5-44bf-9106-c943d19f8eb7">

2024-07-25 12:21 UTC, Yomzy2223 requested changes

2024-07-25 12:21 UTC, Yomzy2223 commented on src/components/CreateWiki/EditorModals/EditWikiDetailsModal/EventsInput/index.tsx
> -              <ComboBoxPopup
Any reason for removing the ComboBox? You might have to reuse it here for consistency sake, as the ui currently differs from others.

<img width="1440" alt="Screenshot 2024-07-25 at 20 14 19" src="https://github.com/user-attachments/assets/58d44e16-8ca2-4720-b797-3337ac411469">
<img width="1440" alt="Screenshot 2024-07-25 at 20 14 32" src="https://github.com/user-attachments/assets/3afab945-f909-4536-8b3b-2c9af34708db">

2024-07-25 12:54 UTC, Aliiiu commented on src/components/CreateWiki/EditorModals/EditWikiDetailsModal/EventsInput/index.tsx
> -              <ComboBoxPopup
Then i will have to test others on that modal to see if they are also in a form with uncontrolled inputs. The comboBox failed the validation test because it checks for the missing type input.

2024-07-25 13:38 UTC, Yomzy2223 commented on src/components/CreateWiki/EditorModals/EditWikiDetailsModal/EventsInput/index.tsx
> -              <ComboBoxPopup
The Event Dates section is the only form on the dialog. I think others work fine with the combobox. Can we modify the combobox to work with the form?

2024-07-29 08:44 UTC, Yomzy2223 approved these changes

2024-07-29 09:41 UTC, merged