Improve Event User Experience
EveripediaNetwork/ep-ui pull request #1982
Opened 2024-07-29 08:07 UTC by Aliiiu

# Improve Event User Experience

This PR works on improving user experience on the event page

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2963

2024-07-29 10:49 UTC, Simplypheyie96 requested changes
- Events section has not been enabled on the homepage
link: https://www.figma.com/design/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.wiki?node-id=33990-7951&t=5nr4WJoRrQmP1Mek-11
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/9d828284-b864-4b02-9c01-a426c6ae73d0">

---
I suggest extending the search bar to match the width of the content area. I think this will enhance the ui. 

link: https://www.figma.com/design/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.wiki?node-id=30810-23622&t=5nr4WJoRrQmP1Mek-11
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/768786ef-8430-44ef-acb2-bb99ec352398">

---

- Tags on event cards should show events with similar tags, and not wikis.
---
- This might be for the editors, but the "register link" for events shouldn't redirect to another events page on another site but to the main registration site for that event. @Softdev1 
---
- Tags in event details page redirect to the homepage instead of showing results for that event tag.
<img width="691" alt="image" src="https://github.com/user-attachments/assets/00f7eec2-7fc3-4d74-9951-0b0b9ccddf20">

2024-07-29 12:18 UTC, Aliiiu commented
https://github.com/user-attachments/assets/6ecc0af0-3d08-46c2-8db3-c9f0784f1f41

@Simplypheyie96 The behavior for tags on event details page is different from what you raised

2024-07-29 14:24 UTC, Softdev1 commented
> * Events section has not been enabled on the homepage
>   link: https://www.figma.com/design/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.wiki?node-id=33990-7951&t=5nr4WJoRrQmP1Mek-11
> 
> <img alt="image" width="1094" src="https://private-user-images.githubusercontent.com/99387231/353000719-9d828284-b864-4b02-9c01-a426c6ae73d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjE2OTcsIm5iZiI6MTcyMjI2MTM5NywicGF0aCI6Ii85OTM4NzIzMS8zNTMwMDA3MTktOWQ4MjgyODQtYjg2NC00YjAyLTljMDEtYTQyNmM2YWU3M2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYWIwMWY2YmNjMGU1YTMxMDhkZGY1NzgyZjBiZmU4YjIxNjViZGM5NDhiYTc5NWI0OTFmOTVmZTRmNWZkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uuHqYyUnoUEDSA51ZJ0vfc6L_aFhqjHt4eyI3VmpS7w">
> I suggest extending the search bar to match the width of the content area. I think this will enhance the ui.
> 
> link: https://www.figma.com/design/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.wiki?node-id=30810-23622&t=5nr4WJoRrQmP1Mek-11 <img alt="image" width="1060" src="https://private-user-images.githubusercontent.com/99387231/353001693-768786ef-8430-44ef-acb2-bb99ec352398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjE2OTcsIm5iZiI6MTcyMjI2MTM5NywicGF0aCI6Ii85OTM4NzIzMS8zNTMwMDE2OTMtNzY4Nzg2ZWYtODQzMC00NGVmLWFjYjItYmI5OWVjMzUyMzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YTg5MTg1Njk0NGUyYjVhNjE2ZjUzNjMxMjZmYzc0ODRlMmE0MmU4MmYzY2JjZGVmNDhiN2JhY2U4NzZiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CeJjCtRobyrmHOiE0i02eVR7jPVTQungcb6aKAQ4vbs">
> 
> * Tags on event cards should show events with similar tags, and not wikis.
> 
> * This might be for the editors, but the "register link" for events shouldn't redirect to another events page on another site but to the main registration site for that event. @Softdev1
> 
> * Tags in event details page redirect to the homepage instead of showing results for that event tag.
> 
> <img alt="image" width="691" src="https://private-user-images.githubusercontent.com/99387231/353012064-00f7eec2-7fc3-4d74-9951-0b0b9ccddf20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjE2OTcsIm5iZiI6MTcyMjI2MTM5NywicGF0aCI6Ii85OTM4NzIzMS8zNTMwMTIwNjQtMDBmN2VlYzItN2ZjMy00ZDc0LTk5NTEtMGIwYjljY2RkZjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNzlhYmU4MWZiMjk0ZTczYTM1OTQyZDk4NTZiZTA1NmM1YTEzZGE5ZDBlMjdlNjNkODM5ZTM4YmE4YTM2YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0vG1w9Z-Hi8Qpp2KLgZcH-muipNK8tDWodohsIF1hIM">

yeah. I think the registration link is not going to the right link. I would support you to route to the registration link

2024-07-30 05:58 UTC, Softdev1 approved these changes

2024-07-30 14:51 UTC, Yomzy2223 approved these changes

2024-07-30 14:52 UTC, merged