Event translations
EveripediaNetwork/ep-ui pull request #1986
Opened 2024-07-30 22:57 UTC by Aliiiu

# Event Translations

This PR resolves translations regarding events

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2962

2024-07-31 13:57 UTC, Simplypheyie96 requested changes
or the Chinese and Korean versions, let's split the header text into two lines. The current spacing below the header feels unbalanced.
<img width="1580" alt="image" src="https://github.com/user-attachments/assets/1d1114d9-9a7a-436a-8a29-52fb828e9dd9">

2024-08-01 08:35 UTC, Aliiiu commented
> Translating to Korean (Ko) gave an entirely different outcome , the past event and upcoming events aren't displaying on the screen again
> 
> <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/32770520/353878835-b3aea393-c6ed-40f4-81e1-4e88bf488f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDA4MTMsIm5iZiI6MTcyMjUwMDUxMywicGF0aCI6Ii8zMjc3MDUyMC8zNTM4Nzg4MzUtYjNhZWEzOTMtYzZlZC00MGY0LTgxZTEtNGU4OGJmNDg4ZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4MjE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYzBkN2E5NTY2OTA0ZmQ4ZDFmMDdhMjIxNzZhOTE5NGQ0NDNlMzEzNzQ4OGYyNWJlZWIyM2IzZmM0ZDk0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZdhCXHtDJHGf0q8z-p5r5Ktt4-W7-iG-l4FJK7xjV3U">

@Softdev1 Test it again
https://iq-wiki-git-event-translations-prediqt.vercel.app/events/

2024-08-01 12:55 UTC, Simplypheyie96 approved these changes

2024-08-01 13:14 UTC, Softdev1 approved these changes

2024-08-01 14:16 UTC, Yomzy2223 reviewed
Looks good, but why not follow a particular naming convention for the keys, for consistency and readability sake? I can see some in camel case, and some pascal.

2024-08-01 14:18 UTC, Aliiiu commented
> Looks good, but why not follow a particular naming convention for the keys, for consistency and readability sake? I can see some in camel case, and some pascal.


Can you drop screenshot of examples so I can work on them

2024-08-01 15:54 UTC, Yomzy2223 approved these changes

2024-08-01 16:01 UTC, Adebesin-Cell commented on public/locales/ko/event.json
> +  "North America": "북아메리카",
Can this be made camelCase as well?

2024-08-01 16:04 UTC, Aliiiu commented on public/locales/ko/event.json
> +  "North America": "북아메리카",
They are static data that are used for filtering. When creating an event we don't have options for regions in different languages. Same with all other filtering options and interests.

2024-08-01 16:05 UTC, Adebesin-Cell commented on public/locales/ko/event.json
> +  "North America": "북아메리카",
Oh fair enough!

2024-08-01 16:06 UTC, Adebesin-Cell approved these changes

2024-08-01 16:06 UTC, Aliiiu commented on public/locales/ko/event.json
> +  "North America": "북아메리카",
![image](https://github.com/user-attachments/assets/fbbc2e74-6642-4c94-86e5-0c877859f424)
![image](https://github.com/user-attachments/assets/cef080e0-579d-43ba-94c4-e1f1e2d3e5c2)

2024-08-01 16:08 UTC, Aliiiu commented on public/locales/ko/event.json
> +  "North America": "북아메리카",
<img width="670" alt="image" src="https://github.com/user-attachments/assets/2cb89004-b289-4bca-9f38-f77ffff975b9">

2024-08-01 16:08 UTC, merged