UI revamp mobile optimization
EveripediaNetwork/ep-ui pull request #1989
Opened 2024-07-31 15:18 UTC by invisiblemask

# PR title goes here

_PR description goes here_

## How should this be tested?

1. Step one
2. Step two
3. ...

## Notes or observations

_jot down something here_

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/ISSUE_NUMBER_GOES_HERE

2024-08-05 07:55 UTC, Tolu-Mals commented
please add screenshots when possible. it makes it easier to review.

2024-08-05 08:14 UTC, Tolu-Mals commented
Font weight should be slighly lesser

Implementation

![Screenshot 2024-08-05 at 9 13 09 AM](https://github.com/user-attachments/assets/cafe185a-8e4d-4ba0-bca6-61ff03211879)

Design
![Screenshot 2024-08-05 at 9 11 55 AM](https://github.com/user-attachments/assets/7d65718d-9d40-4ffd-a0c5-7e26a66f1b06)

2024-08-05 08:21 UTC, invisiblemask commented
> please add screenshots when possible. it makes it easier to review.

I'm getting them at the moment, I will also add the Figma link too

2024-08-05 08:22 UTC, invisiblemask commented
> Font weight should be slighly lesser
> 
> Implementation
> 
> ![Screenshot 2024-08-05 at 9 13 09 AM](https://private-user-images.githubusercontent.com/30352484/355025257-cafe185a-8e4d-4ba0-bca6-61ff03211879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDU5NTcsIm5iZiI6MTcyMjg0NTY1NywicGF0aCI6Ii8zMDM1MjQ4NC8zNTUwMjUyNTctY2FmZTE4NWEtOGU0ZC00YmEwLWJjYTYtNjFmZjAzMjExODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA4MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MTYwZTRiOGRhNmFkOTI4MjZmYmMxYTM3MDM3YTBlZjE1ODUyMmRmZjdhODQ4NmVkYTEyNDUyNWE4Y2IyMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ssy0sfH4kqjzPok0uDYEGiPvxdscAvhOD9JmwGJqvj4)
> 
> Design ![Screenshot 2024-08-05 at 9 11 55 AM](https://private-user-images.githubusercontent.com/30352484/355025519-7d65718d-9d40-4ffd-a0c5-7e26a66f1b06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDU5NTcsIm5iZiI6MTcyMjg0NTY1NywicGF0aCI6Ii8zMDM1MjQ4NC8zNTUwMjU1MTktN2Q2NTcxOGQtOWQ0MC00ZmZkLWEwYzUtN2UyNmE2NmYxYjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA4MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZWI0N2MzOTA1YWQ3ZTYxYmE4NGJlMGMzZWJhMDE0NzM1N2M4M2YyZGQ1NThlNGU5YjRmMjQzOGFkNmM3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K9GUElRKb-yTHQTDsDa_zyJiDw0cfbcwuhEnxyYDdwM)

Noted

2024-08-05 08:23 UTC, Tolu-Mals commented
The border in each group for the token stats should be slightly more visible like in the design.

Implementation
![Screenshot 2024-08-05 at 9 20 13 AM](https://github.com/user-attachments/assets/9471bf30-acbf-4c83-94a5-ab9486804214)

Design
![Screenshot 2024-08-05 at 9 18 23 AM](https://github.com/user-attachments/assets/af242e84-f576-44fd-97da-894dbfc2aab8)

2024-08-05 08:24 UTC, Tolu-Mals commented
> > please add screenshots when possible. it makes it easier to review.
> 
> I'm getting them at the moment, I will also add the Figma link too

For this, Figma link alone is sufficient I think

2024-08-05 08:39 UTC, Royal-lobster commented
UI looks awesome !! ❤️‍🔥 @Simplypheyie96  @invisiblemask

2024-08-05 09:20 UTC, Tolu-Mals commented
Font weight should be slightly lesser

Implementation
![Screenshot 2024-08-05 at 10 17 02 AM](https://github.com/user-attachments/assets/5500b71a-6b7d-4da2-bdf4-230a4dad52d5)

Design
<img width="551" alt="Screenshot 2024-08-05 at 10 17 27 AM" src="https://github.com/user-attachments/assets/2b324a2b-1959-4a02-87e8-1530c8bdea86">

2024-08-05 09:26 UTC, Tolu-Mals commented
Button text should be smaller

Implementation
![Screenshot 2024-08-05 at 10 18 03 AM](https://github.com/user-attachments/assets/333929e2-d96b-49fc-acb7-e8298c2dd525)

Design
<img width="551" alt="Screenshot 2024-08-05 at 10 17 49 AM" src="https://github.com/user-attachments/assets/ce22f96a-c5a9-4048-83e5-93228a6943ca">

2024-08-05 09:29 UTC, Tolu-Mals commented
This text has been updated to 'Discover more on IQ wiki'

![Screenshot 2024-08-05 at 10 28 30 AM](https://github.com/user-attachments/assets/73528802-a20c-43a2-a886-c523f29d688d)

2024-08-05 09:49 UTC, Tolu-Mals commented
Loader looks weird

https://github.com/user-attachments/assets/86ba1a99-508b-46be-8a4e-beb67b43f6ae

2024-08-05 09:57 UTC, Tolu-Mals commented
Seems there's a client side error on the home page, it shows up randomly sometimes. But you can reproduce it by clicking on the logo link when the page is transitioning to another page

![Screenshot 2024-08-05 at 10 52 16 AM](https://github.com/user-attachments/assets/4a937991-3b1a-4c5e-8b64-4a748723d125)

Look out for where you're getting the length property on a possibly undefined variable

![Screenshot 2024-08-05 at 10 52 34 AM](https://github.com/user-attachments/assets/78db43a0-5dc4-4b64-9ac8-0fca563119e2)

2024-08-05 10:03 UTC, invisiblemask commented
> Loader looks weird
> 
>  Screen.Recording.2024-08-05.at.10.47.45.AM.mov

I don't think I know where that loader came from but I will fix it

2024-08-05 10:08 UTC, Adebesin-Cell commented
> Seems there's a client side error on the home page, it shows up randomly sometimes. But you can reproduce it by clicking on the logo link when the page is transitioning to another page
> 
> ![Screenshot 2024-08-05 at 10 52 16 AM](https://private-user-images.githubusercontent.com/30352484/355059927-4a937991-3b1a-4c5e-8b64-4a748723d125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTIyMjYsIm5iZiI6MTcyMjg1MTkyNiwicGF0aCI6Ii8zMDM1MjQ4NC8zNTUwNTk5MjctNGE5Mzc5OTEtM2IxYS00YzVlLThiNjQtNGE3NDg3MjNkMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0N2QxNWJmMmM2MDJlY2FiNmRkMmJlMjhkYjdjMTZhYTRlYTdhNWE0ZDFjZTViNzdkMWRhODk4YTU0ZGU3ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jGgQJySGQ8kQS3WgHLjWZ-ProK9_VXBRxzPvUmAvt2w)
> 
> Look out for where you're getting the length property on a possibly undefined variable
> 
> ![Screenshot 2024-08-05 at 10 52 34 AM](https://private-user-images.githubusercontent.com/30352484/355060146-78db43a0-5dc4-4b64-9ac8-0fca563119e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTIyMjYsIm5iZiI6MTcyMjg1MTkyNiwicGF0aCI6Ii8zMDM1MjQ4NC8zNTUwNjAxNDYtNzhkYjQzYTAtNWRjNC00YjY0LTlhYzgtMGZjYTU2MzExOWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiN2NkZmY1Y2Y0YzljOWMzZDE2YmQ0YmYxMDNlYzc4ZTM3MTRkNDRiMDcxNjZlZWI0NWNkNTM2MjMyNjgzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gc9kcwg3aEMb4a4EjfckZ57f768GHb-iJF7_B2kmuQo)

Maybe related with the fix that homepage was breaking a while back?

2024-08-05 10:14 UTC, invisiblemask commented
> > Seems there's a client side error on the home page, it shows up randomly sometimes. But you can reproduce it by clicking on the logo link when the page is transitioning to another page
> > ![Screenshot 2024-08-05 at 10 52 16 AM](https://private-user-images.githubusercontent.com/30352484/355059927-4a937991-3b1a-4c5e-8b64-4a748723d125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTIyMjYsIm5iZiI6MTcyMjg1MTkyNiwicGF0aCI6Ii8zMDM1MjQ4NC8zNTUwNTk5MjctNGE5Mzc5OTEtM2IxYS00YzVlLThiNjQtNGE3NDg3MjNkMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0N2QxNWJmMmM2MDJlY2FiNmRkMmJlMjhkYjdjMTZhYTRlYTdhNWE0ZDFjZTViNzdkMWRhODk4YTU0ZGU3ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jGgQJySGQ8kQS3WgHLjWZ-ProK9_VXBRxzPvUmAvt2w)
> > Look out for where you're getting the length property on a possibly undefined variable
> > ![Screenshot 2024-08-05 at 10 52 34 AM](https://private-user-images.githubusercontent.com/30352484/355060146-78db43a0-5dc4-4b64-9ac8-0fca563119e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTIyMjYsIm5iZiI6MTcyMjg1MTkyNiwicGF0aCI6Ii8zMDM1MjQ4NC8zNTUwNjAxNDYtNzhkYjQzYTAtNWRjNC00YjY0LTlhYzgtMGZjYTU2MzExOWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiN2NkZmY1Y2Y0YzljOWMzZDE2YmQ0YmYxMDNlYzc4ZTM3MTRkNDRiMDcxNjZlZWI0NWNkNTM2MjMyNjgzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gc9kcwg3aEMb4a4EjfckZ57f768GHb-iJF7_B2kmuQo)
> 
> Maybe related with the fix that homepage was breaking a while back?

Has the fix been merged?

2024-08-05 10:19 UTC, Tolu-Mals commented
> > > Seems there's a client side error on the home page, it shows up randomly sometimes. But you can reproduce it by clicking on the logo link when the page is transitioning to another page
> > > ![Screenshot 2024-08-05 at 10 52 16 AM](https://private-user-images.githubusercontent.com/30352484/355059927-4a937991-3b1a-4c5e-8b64-4a748723d125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTIyMjYsIm5iZiI6MTcyMjg1MTkyNiwicGF0aCI6Ii8zMDM1MjQ4NC8zNTUwNTk5MjctNGE5Mzc5OTEtM2IxYS00YzVlLThiNjQtNGE3NDg3MjNkMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0N2QxNWJmMmM2MDJlY2FiNmRkMmJlMjhkYjdjMTZhYTRlYTdhNWE0ZDFjZTViNzdkMWRhODk4YTU0ZGU3ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jGgQJySGQ8kQS3WgHLjWZ-ProK9_VXBRxzPvUmAvt2w)
> > > Look out for where you're getting the length property on a possibly undefined variable
> > > ![Screenshot 2024-08-05 at 10 52 34 AM](https://private-user-images.githubusercontent.com/30352484/355060146-78db43a0-5dc4-4b64-9ac8-0fca563119e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTIyMjYsIm5iZiI6MTcyMjg1MTkyNiwicGF0aCI6Ii8zMDM1MjQ4NC8zNTUwNjAxNDYtNzhkYjQzYTAtNWRjNC00YjY0LTlhYzgtMGZjYTU2MzExOWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiN2NkZmY1Y2Y0YzljOWMzZDE2YmQ0YmYxMDNlYzc4ZTM3MTRkNDRiMDcxNjZlZWI0NWNkNTM2MjMyNjgzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gc9kcwg3aEMb4a4EjfckZ57f768GHb-iJF7_B2kmuQo)
> > 
> > 
> > Maybe related with the fix that homepage was breaking a while back?
> 
> Has the fix been merged?

Yes

2024-08-05 10:21 UTC, Adebesin-Cell commented on src/components/Categories/CategoriesCard.tsx
> +type CategoriesCardProps = {
interface reads better

2024-08-05 10:21 UTC, Adebesin-Cell commented on src/components/Landing/CategoriesList.tsx
> +  const { data } = useGetWikisAndCategoriesQuery({
Ensure to use a server fetch in getServerSideProps, we need to make homepage as static as possible.

2024-08-05 10:21 UTC, Adebesin-Cell commented on src/components/Landing/CategoriesList.tsx
> +              {data?.map(
That was data gets defined here 👍, incase we don't have data we should have empty fallback UI

2024-08-05 10:21 UTC, Adebesin-Cell commented on src/components/Landing/FeaturedWikiCard.tsx
> +            {shortenText(wiki?.title, 30)}
I think wiki is defined so we don't need to optionally chain properties

2024-08-05 10:21 UTC, Adebesin-Cell commented on src/components/Landing/IQBar.tsx
> +              {cmcLoading ? (
Let's use ``isDataFetching`` then we refactor such that instead of having three fetch calls we do the calls in parallel, perhaps not related with PR but if we can we can also fetch the data from getStaticProps.

2024-08-05 10:21 UTC, Adebesin-Cell commented on src/components/Landing/RankingList.tsx
> +  const [selectedTab, setSelectedTab] = useState<string>('cryptocurrencies')
This can be enums of the categories tab we want to put out.

2024-08-05 10:21 UTC, Adebesin-Cell commented on src/components/Landing/WikiCategories.tsx
> +        {AllCategoriesData.slice(0, 5).map((category) => {
We can use a variable stored to get 5 items and not put out 5 here, also, i think this would give static 5, we can always render random 5, that'll make it more engaging for other categories that we have.

2024-08-05 10:31 UTC, invisiblemask commented on src/components/Landing/WikiCategories.tsx
> +        {AllCategoriesData.slice(0, 5).map((category) => {
hmmm,make sense

2024-08-05 10:31 UTC, invisiblemask commented on src/components/Landing/RankingList.tsx
> +  const [selectedTab, setSelectedTab] = useState<string>('cryptocurrencies')
Okay noted

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/Landing/CategoriesList.tsx
> +  const { t: tr } = useTranslation('category')
You shouldn't have to call the same hook twice, there's a way to do it just once, check other pages or the docs

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/Landing/CustomTooltip.tsx
> +const CustomTooltip = ({ active, payload }: any) => {
You want to avoid using `any` for types, TypeScript might be able to infer the type if you don't specify one

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/Landing/TrendingCard.tsx
> +                  onKeyUpCapture={() => router.push(`wiki/${wiki.id}`)}
What is this for?

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/Layout/Layout/Layout.tsx
> +    <main className="flex flex-col min-h-screen">
wrong use of `main` here.

[What main element is used for](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main)

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/Layout/Navbar/WalletNavMenu.tsx
> +          role="button"
don't give a div a role of button. use a button instead. also why are you using an `onKeyDown` event handler here

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/Layout/WalletDrawer/WalletDrawer.tsx
> +          }}
you're using a lot of KeyUp and KeyDown event handlers, please explain why

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/Wiki/WikiPreviewCard/WikiPreviewCard.tsx
> +
```suggestion
```

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/ui/avatar.tsx
> +'use client'
```suggestion
```
IQ.wiki does not use the app directory, so there's no need for 'use client' directive, all components are client components by default. Please remove it from all the places you added it.

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/ui/avatar.tsx
> +
```suggestion
```
this new line is not needed

2024-08-05 11:52 UTC, Tolu-Mals commented on src/components/ui/label.tsx
> +'use client'
```suggestion
```

2024-08-05 11:52 UTC, Tolu-Mals commented on src/pages/index.tsx
> +    <main>
wrong use of main element

2024-08-05 11:52 UTC, Tolu-Mals commented on src/services/wikis/index.ts
> +    user: {
It is very likely that some of these types already exist. Please check other parts of the code, so we don't declare types multiple times.

2024-08-05 11:52 UTC, Tolu-Mals commented on src/services/wikis/queries.ts
> +    }
Also check that this didn't exist before. how did we fetch wikis and categories before this pr?

2024-08-05 13:07 UTC, invisiblemask commented on src/components/Landing/CategoriesList.tsx
> +  const { t: tr } = useTranslation('category')
For this I tried using `const { t } = useTranslation(['common', 'category'])` but it didn't work, I also checked other components and it worked there but wasn't working here, I will try to find out why it wasn't and fix

2024-08-05 13:15 UTC, invisiblemask commented on src/components/Layout/WalletDrawer/WalletDrawer.tsx
> +          }}
This is required by Biome for people with physical disability and cannot use a mouse so they can use the keyboard events 

[Here is the link for it](https://biomejs.dev/linter/rules/use-key-with-click-events/)

2024-08-05 13:15 UTC, invisiblemask commented on src/components/ui/avatar.tsx
> +'use client'
I missed that thanks 👍🏾

2024-08-05 14:55 UTC, invisiblemask commented on src/services/wikis/queries.ts
> +    }
For this, what we have is wiki by category, which fetches wikis based on the selected categories but it doesn't fetch all categories, so this fetches all categories and it's wikis, although I already updated this query to a proper schema based on the doc on the graphql playground

2024-08-06 15:52 UTC, Simplypheyie96 requested changes
- [x] The "View More" button on the rank page has been updated to "View All" to display the entire table.
<img width="625" alt="image" src="https://github.com/user-attachments/assets/6e962210-0c8d-4a87-ba7c-33227c9e08d4">

- [x] The subtle hover interactions on the wiki cards are missing. These interactions should be re-implemented.
- [x] In light mode, the hover state on buttons is not very noticeable. Consider using a shade of gray (e.g., Gray 200) to improve visibility.
- [x] Move the events button slightly closer to the accompanying text for better visual alignment.
<img width="415" alt="image" src="https://github.com/user-attachments/assets/150e19fa-6e39-4daa-9dda-eae8e4bf217d">

- [x] The "See More Wikis" button under wiki cards should navigate to the specific category selected, allowing users to see more wikis within that category instead of returning to the general wiki categories page.
- [ ] The menu needs to be updated. All options that have been moved to the new bottom navigation should be removed from the main menu bar.   (all updates on figma beside each screen).
<img width="367" alt="image" src="https://github.com/user-attachments/assets/e8cc0c18-ffdd-4176-b9a8-96af15d48e04">

- [x] The icons in the header are not properly aligned on the medium (md) breakpoint. Please adjust the alignment to ensure everything is visually consistent.
<img width="125" alt="image" src="https://github.com/user-attachments/assets/b75fa98c-9058-45a2-bc86-24c8de1a68d9">

---
I have made all into a checklist so you won't miss any of the corrections, and you can check them while you make the iterations.

2024-08-06 16:15 UTC, invisiblemask commented
> - [ ] The "View More" button on the rank page has been updated to "View All" to display the entire table.
> 
> <img width="625" alt="image" src="https://github.com/user-attachments/assets/6e962210-0c8d-4a87-ba7c-33227c9e08d4">
> 
> 
> 
> - [ ] The subtle hover interactions on the wiki cards are missing. These interactions should be re-implemented.
> 
> - [ ] In light mode, the hover state on buttons is not very noticeable. Consider using a shade of gray (e.g., Gray 200) to improve visibility.
> 
> - [ ] Move the events button slightly closer to the accompanying text for better visual alignment.
> 
> <img width="415" alt="image" src="https://github.com/user-attachments/assets/150e19fa-6e39-4daa-9dda-eae8e4bf217d">
> 
> 
> 
> - [ ] The "See More Wikis" button under wiki cards should navigate to the specific category selected, allowing users to see more wikis within that category instead of returning to the general wiki categories page.
> 
> - [ ] The menu needs to be updated. All options that have been moved to the new bottom navigation should be removed from the main menu bar.   (all updates on figma beside each screen).
> 
> <img width="367" alt="image" src="https://github.com/user-attachments/assets/e8cc0c18-ffdd-4176-b9a8-96af15d48e04">
> 
> 
> 
> - [ ] The icons in the header are not properly aligned on the medium (md) breakpoint. Please adjust the alignment to ensure everything is visually consistent.
> 
> <img width="125" alt="image" src="https://github.com/user-attachments/assets/b75fa98c-9058-45a2-bc86-24c8de1a68d9">
> 
> 
> 
> ---
> 
> I have made all into a checklist so you won't miss any of the corrections, and you can check them while you make the iterations.
> 
> 

Alright thanks, I will update them

2024-08-07 07:49 UTC, Simplypheyie96 approved these changes
Well done so far

2024-08-08 10:26 UTC, Tolu-Mals commented
The rank table doesn't display for other languages apart from English

<img width="1436" alt="Screenshot 2024-08-08 at 11 25 40 AM" src="https://github.com/user-attachments/assets/94637b4f-b433-4aa7-bfd7-08195dc714b3">

2024-08-08 10:28 UTC, invisiblemask commented
> The rank table doesn't display for other languages apart from English
> 
> <img alt="Screenshot 2024-08-08 at 11 25 40 AM" width="1436" src="https://private-user-images.githubusercontent.com/30352484/356182829-94637b4f-b433-4aa7-bfd7-08195dc714b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTMxNjIsIm5iZiI6MTcyMzExMjg2MiwicGF0aCI6Ii8zMDM1MjQ4NC8zNTYxODI4MjktOTQ2MzdiNGYtYjQzMy00YWE3LWJmZDctMDgxOTVkYzcxNGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDEwMjc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OWQ5MzQyMjA4NzYzYzNmMDI5M2VmMDU2MzgyZGEyMDVmNDFmNTU3MDM0Y2ViMjFhMWMzMDQ1Y2ZiMTA5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GSmd8_anjs38xHgriWDvTKmmlP9zBMeOnwyrPbUVN8E">

This has been fixed

2024-08-08 10:34 UTC, Tolu-Mals commented
Navbar goes off the viewport for english translation

<img width="1436" alt="Screenshot 2024-08-08 at 11 34 18 AM" src="https://github.com/user-attachments/assets/aed4788b-356d-4aee-96b2-98c17531f42f">

2024-08-08 10:43 UTC, invisiblemask commented
> Navbar goes off the viewport for english translation
> 
> 
> 
> <img width="1436" alt="Screenshot 2024-08-08 at 11 34 18 AM" src="https://github.com/user-attachments/assets/aed4788b-356d-4aee-96b2-98c17531f42f">
> 
> 

We fix that now

2024-08-08 10:48 UTC, Tolu-Mals approved these changes
Looks good ✨, after the navbar fix you can merge.

2024-08-08 10:54 UTC, SidharthK2 commented
Not sure if it's realted to this PR, but I'm getting clientside error on homepage sometimes.
![image](https://github.com/user-attachments/assets/a8df6479-b2cb-46ed-8963-beb0479c404e)

2024-08-08 10:58 UTC, invisiblemask commented
> The more button has a different font size from the rest of the buttons and is not aligned with the rest of the group
> 
> 
> 
> <img width="377" alt="Screenshot 2024-08-08 at 11 45 44 AM" src="https://github.com/user-attachments/assets/6a4c89dc-94eb-4362-ad12-9a28f08b6ee4">
> 
> 

Noted

2024-08-08 11:15 UTC, invisiblemask commented
> Not sure if it's related to this PR, but I'm getting clientside error on homepage sometimes.
> 
> ![image](https://github.com/user-attachments/assets/a8df6479-b2cb-46ed-8963-beb0479c404e)
> 
> 

I will look into it and fix, though I can't reproduce. Can you explain how you got it?

2024-08-08 11:48 UTC, SidharthK2 commented
> > Not sure if it's related to this PR, but I'm getting clientside error on homepage sometimes.
> > ![image](https://private-user-images.githubusercontent.com/58448956/356191247-a8df6479-b2cb-46ed-8963-beb0479c404e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTc5NjgsIm5iZiI6MTcyMzExNzY2OCwicGF0aCI6Ii81ODQ0ODk1Ni8zNTYxOTEyNDctYThkZjY0NzktYjJjYi00NmVkLTg5NjMtYmViMDQ3OWM0MDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDExNDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYTEyZjIzNWYxNjI2ODU4ZDY0MTU3MmVkOWJlODZjNTliN2U4MmZjMGEyNTVhZjIyOTY1MjY3Y2ExZDgyYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KdF161NGbX0ELq4XLDXTqJ9jnPmQA7EJjOJyRtGRZdQ)
> 
> I will look into it and fix, though I can't reproduce. Can you explain how you got it?

Wiki categories -> view all -> press back/iq logo

2024-08-08 13:09 UTC, merged