Event Page Improvement
EveripediaNetwork/ep-ui pull request #1996
Opened 2024-08-05 22:50 UTC by Aliiiu

# Event Page Improvement

THis PR works on resolving
- issue adding or removing multiple multiDate Range for event page
- issue with trending event card routing to a wrong link

## How should this be tested?

1. Try to edit a wiki
2. Open the edit wiki modal, and try to add multiple multiDate range event metadata
3. Go to the event page
4. Click on all events on the trending card

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2985

2024-08-06 12:09 UTC, Tolu-Mals approved these changes

2024-08-07 15:22 UTC, AshakaE approved these changes
Addition of event metadata works as expected

2024-08-08 11:03 UTC, Softdev1 requested changes
Deleting a location upon addition is not working as expected. When you add multiple locations and then delete one, the deletion should only remove the selected location, not clear all the added locations.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/37f96f97-bb89-44d7-a76e-2e7fdfbfde36">

2024-08-08 14:15 UTC, Softdev1 approved these changes

2024-08-08 15:41 UTC, merged