Reworking filter tags
EveripediaNetwork/ep-ui pull request #2022
Opened 2024-08-12 15:09 UTC by Aliiiu

# Rework Filter Tags

This PR works on fixing issues with tag filtering

## How should this be tested?

1. Go to the event page
2. Click on any of the events filter
3. Check the change in layout 

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/3007

2024-08-12 15:43 UTC, Simplypheyie96 requested changes
Great work!
We have just the tags under widgets in the events details page left. They need to be reworked in a similar way too.
<img width="492" alt="image" src="https://github.com/user-attachments/assets/bda8103c-fcbd-4a63-aa33-3486f8b5e964">

2024-08-13 10:44 UTC, Simplypheyie96 approved these changes
i think it works well now

2024-08-13 13:49 UTC, Adebesin-Cell commented on src/components/Event/EventFilter/index.tsx
> +    case 'custom range':
why not use an enum instead of strings? 

Enums provide type safety, prevent errors from typos or invalid values, improve code readability, and offer better performance.

2024-08-13 13:49 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +  useEffect(() => {
What does this do?

2024-08-13 13:49 UTC, Adebesin-Cell commented on src/pages/_app.tsx
> +              <EventContextProvider>
Hm, why are we using global context providers? Can't make it work parent -> child state?

2024-08-13 13:54 UTC, Aliiiu commented on src/pages/_app.tsx
> +              <EventContextProvider>
It's for a single page

2024-08-13 14:00 UTC, Adebesin-Cell commented on src/pages/_app.tsx
> +              <EventContextProvider>
Yep, which is why can be handled in one state, not global, I doubt we need active filter in any other page aside events page. You can prolly refactor into a hook of it'll be used in multiple places of event but having it as a global state is not right.

2024-08-13 14:10 UTC, Softdev1 approved these changes
Good work now

2024-08-13 14:38 UTC, Aliiiu commented on src/components/Event/EventInterest.tsx
> +  useEffect(() => {
it clears all selected tags when the query tag is empty. adding it in the first useEffects introduce a 3-state step for the event interest toggle

2024-08-13 14:38 UTC, Aliiiu commented on src/components/Event/EventFilter/index.tsx
> +    case 'custom range':
Alright

2024-08-13 15:47 UTC, Aliiiu commented on src/pages/_app.tsx
> +              <EventContextProvider>
it won't work as a hook because I want to keep the same state on navigating between /event and /event/[slug].

2024-08-13 15:51 UTC, Aliiiu commented on src/pages/_app.tsx
> +              <EventContextProvider>
We can jump on a call so I can explain the issue better

2024-08-13 21:55 UTC, Aliiiu commented on src/pages/_app.tsx
> +              <EventContextProvider>
resolved it you can review it again

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/context/event.context.tsx
> +import {
You can remove this file

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/components/Event/EventSearchBar.tsx
> +      if (query.title) setSearchQuery(String(query.title))
You can type cast query, sth like 
```ts
const { title, startDate, endDate } = router.query as { title: string; startDate: string; endDate: string }
```

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/pages/events/[slug].tsx
> +  let references: CiteReference[]
```ts

const EMPTY_ARRAY_JSON = '[]';

const getReferencesList = (event: any): CiteReference[] => {
  const referencesJsonString = getWikiMetadataById(event, CommonMetaIds.REFERENCES)?.value ?? EMPTY_ARRAY_JSON;

  try {
    const parsedReferences = JSON.parse(referencesJsonString) as CiteReference[];
    return Array.isArray(parsedReferences) ? parsedReferences : [];
  } catch (error) {
    console.error('Failed to parse references JSON:', error);
    return [];
  }
};

// In your component or function:
const referencesList = getReferencesList(event);

```

let's do this

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +  // const { data: countryName } = useGetIpDetailsQuery()
remove unused code

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +  const currentTag = (router.query.tags as string) ? router.query.tags : ''
type mismatch? tags suggest ``string[]``

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +  const activeTagFilter = currentTag.length > 0
Improve variable name so it gives a nicer description of what the boolean does, perhaps ``isThereCurrentTag`` based on context should be ``hasActiveTag``

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/utils/event.utils.ts
> +export type SetState<T> = Dispatch<SetStateAction<T>>
Hm, why defining this?

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +    setSelectedInterest((prevSelected) => {
What does Interest mean?

2024-08-14 16:47 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +        typeof interestFromQuery === 'string'
Idg, do we have an array of interests in url then we parse or we are doing some parses before we achieve a field of interests?

2024-08-14 16:53 UTC, Aliiiu commented on src/utils/event.utils.ts
> +export type SetState<T> = Dispatch<SetStateAction<T>>
it is a type for setState actions passed as props to other components. Instead of repeating the same type every where I created a custom type that works for every case

2024-08-14 16:53 UTC, Aliiiu commented on src/pages/events/index.tsx
> +  // const { data: countryName } = useGetIpDetailsQuery()
It is to be revised and tested well later. We are still using it

2024-08-14 17:01 UTC, Aliiiu commented on src/pages/events/index.tsx
> +  const currentTag = (router.query.tags as string) ? router.query.tags : ''
The expected query in this case is a string. The logic here is to filter events by tags when you click any tag in the event summary widget on the event details page. Clicking any of the tags take you to the event page.

2024-08-14 17:02 UTC, Aliiiu commented on src/components/Event/EventInterest.tsx
> +    setSelectedInterest((prevSelected) => {
Event interest in the event interest cards

2024-08-14 17:03 UTC, Aliiiu commented on src/components/Event/EventInterest.tsx
> +        typeof interestFromQuery === 'string'
Multiple interests can be selected, then they are parsed to an array. The query is expecting [string!]

2024-08-14 17:05 UTC, Adebesin-Cell commented on src/utils/event.utils.ts
> +export type SetState<T> = Dispatch<SetStateAction<T>>
I think it makes sense to allow for the repetition so it doesn't get complex to read code 🙏

2024-08-14 17:07 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +    setSelectedInterest((prevSelected) => {
Do you have a picture perhaps?

2024-08-14 17:07 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +        typeof interestFromQuery === 'string'
you mean filters? I'm confused how does it get passed to query?

2024-08-14 17:09 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +  const currentTag = (router.query.tags as string) ? router.query.tags : ''
Reads better as tag, tags gives sth like plural

2024-08-14 17:14 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +  const activeTagFilter = currentTag.length > 0
If current tag, then you can just check.
```ts
	const { tag } = router.query as {tag?: string}
 const activeTag = tab || null
```

then remove the activeTagFilter condition, and use activeTag

2024-08-14 17:15 UTC, Aliiiu commented on src/components/Event/EventInterest.tsx
> +    setSelectedInterest((prevSelected) => {
<img width="2046" alt="image" src="https://github.com/user-attachments/assets/4fb35e63-71f9-4e14-b7e8-cf919345dd33">

2024-08-14 17:24 UTC, Aliiiu commented on src/components/Event/EventInterest.tsx
> +        typeof interestFromQuery === 'string'
Using the picture attached to the previous conversation as a reference. To get events that have some selected tags [in the UI it is interests] we run a query that accepts tagIds:[string!]. When you click any of the interests it adds a state to the URL which you can get from useRouter() as a sting if it is a single param you add or an array if you add multiple params.

<img width="2047" alt="image" src="https://github.com/user-attachments/assets/f1fbb820-3c6d-4b43-b1e1-efa8d00c91b2">

2024-08-14 17:28 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +    setSelectedInterest((prevSelected) => {
Thanks!

2024-08-14 17:28 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +        typeof interestFromQuery === 'string'
we can name them interests and setSelectedInterests, also if there's a way to push to the .interests in query would be nicer like we have https://iq-wiki-git-reworking-filter-tags-prediqt.vercel.app/events/?interests=BinanceSmartChain&Blockchains&Protocols, then we know we have to parse all into an array

2024-08-14 17:28 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +        typeof interestFromQuery === 'string'
``interestArray`` can be 

we can do the interest parsing here to array from the stringified query
```ts
const interestQueryParam = query.interest;

const parsedInterests = parseInterestQueryParam(interestQueryParam);

function parseInterestQueryParam(param: string | string[] | undefined): string[] {
  if (!param) {
    return [];
  }
  return Array.isArray(param) ? param : [param];
}
```

2024-08-14 17:28 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +              {/* <NearbyEventFilter countryName={countryName ?? ''} /> */}
remove unused line

2024-08-14 17:28 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +// import NearbyEventFilter from '@/components/Event/NearbyEventFilter'
remove unused line

2024-08-14 17:28 UTC, Adebesin-Cell commented on src/pages/events/[slug].tsx
> +  // const { data: countryName } = useGetIpDetailsQuery()
remove unsed line

2024-08-14 17:28 UTC, Adebesin-Cell commented on src/components/Event/EventList.tsx
> +            {activeTagFilter ? 'Event Filter Results' : t('searchResult')}
Ensure to add translations to Event Filter Results text

2024-08-14 17:53 UTC, Aliiiu commented on src/components/Event/EventSearchBar.tsx
> +      if (query.title) setSearchQuery(String(query.title))
Nice, some other variable will share the same names with the ones you declared here and they are in the same scope. it will raise a conflict so I used this

`const query = router.query as {
      title: string
      startDate: string
      endDate: string
    }`

2024-08-14 17:55 UTC, Adebesin-Cell commented on src/pages/events/[slug].tsx
> +  let references: CiteReference[]
It reads better to have the function and UI separate instead of having the parsing of references, we could have a function that does that, I think it can also be used in wiki again.

2024-08-14 17:56 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +  // const { data: countryName } = useGetIpDetailsQuery()
In this code or another pr?

2024-08-14 18:00 UTC, Aliiiu commented on src/pages/events/index.tsx
> +  // const { data: countryName } = useGetIpDetailsQuery()
Part of the issue is to hide nearByEvent component

2024-08-15 05:37 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +    const interestQueryPaaram = query.interest
``interestQueryParam``

2024-08-15 05:37 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +    setSelectedInterest(parseInterestQueryParam(interestQueryPaaram))
better to always call and assign to a value before use state

I mean assign parseInterestQueryParam(interestQueryPaaram) to a variable then use the variable in state setter

2024-08-15 05:37 UTC, Adebesin-Cell commented on src/components/Event/EventInterest.tsx
> +    function parseInterestQueryParam(
Move this to event.utils

2024-08-15 05:37 UTC, Adebesin-Cell commented on src/components/Event/EventSearchBar.tsx
> +      if (query.title) setSearchQuery(String(query.title))
you can rename them to fit if such might happen, maybe ``{title: filterTitle}``

2024-08-15 05:37 UTC, Adebesin-Cell commented on src/pages/events/[slug].tsx
> +// import { useGetIpDetailsQuery } from '@/services/location'
Unused imports

2024-08-15 05:37 UTC, Adebesin-Cell commented on src/pages/events/[slug].tsx
> +  const getReferencesList = (event: any): CiteReference[] => {
move function to utils, it leaves a good code organization

2024-08-15 05:37 UTC, Adebesin-Cell commented on src/pages/events/index.tsx
> +  const hasActiveTags = currentTag.length > 0
Hm, since it's a string instead of checking the length we can add a null as value instead of empty string, then we do null check for hasActive	Tag, except if tag is an array of selection, then we can rename it to currentTags

2024-08-15 10:14 UTC, Adebesin-Cell commented
Fix build errors, but I think aside that code looks good

2024-08-15 10:15 UTC, Adebesin-Cell approved these changes

2024-08-15 11:59 UTC, merged