WIP - Admin page update
EveripediaNetwork/ep-ui pull request #2043
Opened 2024-08-16 20:49 UTC by Adebesin-Cell

# WIP - Admin page update

[DRAFT]

2024-08-19 15:43 UTC, Simplypheyie96 requested changes
- After updating, the token/NFT should no longer be part of the table.
- Switching between the NFT and cryptocurrency tabs should not reload the page; it should simply switch the tables.
- The dashboard tab remains selected even after navigating to other pages.
<img width="488" alt="image" src="https://github.com/user-attachments/assets/2b17e47a-25ef-4969-9384-8404b70c179e">

- Navigation for mobile breakpoints still needs to be updated.

2024-08-20 11:34 UTC, AshakaE approved these changes
<img width="1619" alt="image" src="https://github.com/user-attachments/assets/ad3b295f-9522-4120-9801-47934d80c769">
Works as expected, tested with abitrium wiki

2024-08-21 08:00 UTC, Simplypheyie96 approved these changes
NB: I have been told the issue of on removing updated tokens/nfts from the unlinked wiki table will be sorted in another pr. cc: @AshakaE

2024-08-26 08:02 UTC, Aliiiu commented on src/pages/admin/dashboard/index.tsx
> +  wikiViews: {
Create a type for this to make it look cleaner, you can also create a file for this type since it is a bit long

2024-08-26 08:04 UTC, Aliiiu commented
I tested the admin access thing like this and i was not able to see the admin navLink.

- sign in locally
- open the website using the preview link
- open the drawer to see if i can access the admin route

2024-08-26 08:12 UTC, Adebesin-Cell commented on src/services/admin/index.ts
> +  Day = 'day',
API requests accepts different form of time interval that's why we have the repetition, though I believe we could make some lowercase when passing to endpoint but it won't be safe to that.

2024-08-26 08:12 UTC, Adebesin-Cell commented on src/components/Admin/WikiDataGraph.tsx
> +  wikiVisits: {
Noted

2024-08-26 08:13 UTC, Adebesin-Cell commented on src/components/Admin/modules/checkAdminAccess.ts
> +  WIKIS = '/admin/dashboard/wikis',
Ha, good catch 👏, I'll add that, thanks!

2024-08-26 08:13 UTC, Adebesin-Cell commented on src/components/Layout/Navbar/Navbar.tsx
> +        {isAdminRoute ? (
If you're on an admin route we don't want to show some component so I hide them when you navigate to admin.

2024-08-26 08:17 UTC, Adebesin-Cell commented
> I tested the admin access thing like this and i was not able to see the admin navLink.
> 
> * sign in locally
> * open the website using the preview link
> * open the drawer to see if i can access the admin route

What do you mean?

2024-08-26 09:05 UTC, Aliiiu commented
> > I tested the admin access thing like this and i was not able to see the admin navLink.
> > 
> > * sign in locally
> > * open the website using the preview link
> > * open the drawer to see if i can access the admin route
> 
> What do you mean?

<Details>
 <Summary>Preview Link Home page</Summary>
<img width="2044" alt="image" src="https://github.com/user-attachments/assets/f04c7edc-e5ed-4032-8e32-56d92be15974">
</Details>

<Details>
 <Summary>Localhost Home Page</Summary>
<img width="2044" alt="image" src="https://github.com/user-attachments/assets/e50c39c0-9dd4-40c0-8c30-aa912df33a90"></Details>

On the preview link, I can access the admin route.

2024-08-26 09:19 UTC, Adebesin-Cell commented
I'll give it a check, thx 👏

2024-08-26 12:13 UTC, Adebesin-Cell commented
> > > I tested the admin access thing like this and i was not able to see the admin navLink.
> > > 
> > > * sign in locally
> > > * open the website using the preview link
> > > * open the drawer to see if i can access the admin route
> > 
> > 
> > What do you mean?
> 
> Preview Link Home page
> Localhost Home Page
> On the preview link, I can access the admin route.

<img width="1552" alt="Screenshot 2024-08-26 at 1 13 35 PM" src="https://github.com/user-attachments/assets/8ac61100-7ade-4f1d-8bdf-6a438146e437">

For some odd reasons I had to login again

2024-08-26 21:07 UTC, Aliiiu commented on src/services/admin/index.ts
> +  Day = 'day',
Since the case is uniform you can just use one then convert it when needed. Something like .toLowerCase()

2024-08-26 22:15 UTC, Adebesin-Cell commented on src/services/admin/index.ts
> +  Day = 'day',
Hm, I feel it'll ruin enum preservation though, breaks its security :))

2024-08-27 06:58 UTC, Aliiiu commented on src/services/admin/index.ts
> +  Day = 'day',
sync with @AshakaE to see if we can maintain a single case for the enum

2024-08-27 06:59 UTC, Aliiiu commented on src/components/Layout/Navbar/Navbar.tsx
> +        {isAdminRoute ? (
it is better to use && operator to avoid rendering extra ui that we don't need

2024-08-27 07:01 UTC, Adebesin-Cell commented on src/components/Layout/Navbar/Navbar.tsx
> +        {isAdminRoute ? (
It’s meant to render an empty box so layout won’t break :))

2024-08-27 07:01 UTC, Adebesin-Cell commented on src/services/admin/index.ts
> +  Day = 'day',
For sure, thanks!

2024-08-27 07:03 UTC, Adebesin-Cell commented on src/services/admin/index.ts
> +  Day = 'day',
I believe we can have that in another pr, might take a while to update db/backend if needed. Seems like another issue on its own :))

2024-08-27 07:19 UTC, Aliiiu approved these changes

2024-08-27 07:38 UTC, merged

2024-08-27 11:07 UTC, Adebesin-Cell commented
Reverting this till ep-api backend gets merged :))