Rearrange categries 4 col
EveripediaNetwork/ep-ui pull request #2047
Opened 2024-08-16 22:16 UTC by invisiblemask

# Rearrangement of Categories card from 3 columns to 4 

_This PR fixes the issue of replacing 3 columns with 4 for the categories section, this makes images that are pixelated clearer_

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/3065

2024-08-16 22:18 UTC, kesar commented on src/components/Categories/CategoriesCard.tsx
> +          {shortenText(wiki.summary, 50)}
not big deal but code would look much better if we extract these 50, 80, 30 magic numbers into constants on top of the component and use it there 👍🏻

2024-08-16 22:19 UTC, kesar commented on src/components/Landing/CategoriesList.tsx
> +                          {category.wikis.slice(0, 8).map((wiki) => (
same wth this number, probably extract and const in the beginning to easily spot and replace

2024-08-16 22:19 UTC, kesar commented
great work, just some small suggestions

2024-08-16 22:20 UTC, kesar commented on src/components/Categories/CategoriesCard.tsx
> +      <div className="aspect-auto">
not sure how this work, but lets ensure this doesnt make things weird in some of the different screen sizes

2024-08-16 22:20 UTC, invisiblemask commented on src/components/Categories/CategoriesCard.tsx
> +          {shortenText(wiki.summary, 50)}
Okay sir

2024-08-16 22:21 UTC, invisiblemask commented on src/components/Categories/CategoriesCard.tsx
> +      <div className="aspect-auto">
I am already testing that

2024-08-18 10:15 UTC, Simplypheyie96 requested changes
1. it's for home and categories page, so we can't close this out yet.
2. There is inconsistency with the placement of the article author and i am just noticing that the "date edited is missing".
<img width="1260" alt="image" src="https://github.com/user-attachments/assets/620fc6b0-5f58-4a2a-bd56-1f3ba943bc70">

3. just like the design, we would have to adjust the font size of the wiki title and subtitles on the card since the cards are smaller now.

2024-08-18 13:20 UTC, invisiblemask commented
> 1. it's for home and categories page, so we can't close this out yet.
> 
> 2. There is inconsistency with the placement of the article author and i am just noticing that the "date edited is missing".
> 
> <img width="1260" alt="image" src="https://github.com/user-attachments/assets/620fc6b0-5f58-4a2a-bd56-1f3ba943bc70">
> 
> 
> 
> 3. just like the design, we would have to adjust the font size of the wiki title and subtitles on the card since the cards are smaller now.

Do you mean changing the wiki cards in categories page to 4 columns too?

The author name is not consistent because the wiki summary length is very small and that's because it's a test wiki, the summary length for the actual wikis are longer, but I will adjust that in case there's any scenario where we would have short wiki summary length and also add the date edited too

I will check the design and update the font sizes

2024-08-19 11:03 UTC, Simplypheyie96 commented
> Do you mean changing the wiki cards in categories page to 4 columns too?

It was added as part of the issue. @Softdev1 please confirm again if we are changing the categories page into 4 columns.
![image](https://github.com/user-attachments/assets/01dc3fa1-69ee-485a-8d9c-1055930cab88)

2024-08-19 11:50 UTC, Softdev1 commented
> > Do you mean changing the wiki cards in categories page to 4 columns too?
> 
> It was added as part of the issue. @Softdev1 please confirm again if we are changing the categories page into 4 columns. ![image](https://private-user-images.githubusercontent.com/99387231/359078645-01dc3fa1-69ee-485a-8d9c-1055930cab88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjg0NTEsIm5iZiI6MTcyNDA2ODE1MSwicGF0aCI6Ii85OTM4NzIzMS8zNTkwNzg2NDUtMDFkYzNmYTEtNjllZS00ODVhLThkOWMtMTA1NTkzMGNhYjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDExNDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNzk5Y2QxZjFiNTlhMWQ2MDdmODgwZDUyMmZiZjE1ZjQ0ZGQ2YWQzMDJkNzliNTAwODlhODUxNjU5YmQxNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ztrdk4VRMj0JGxCflaRuykrIb_qTjcBK1H6LgkyEuOM)

Yes we are doing it on both the homepage and the category page too

2024-08-19 15:26 UTC, Simplypheyie96 commented
> Yes we are doing it on both the homepage and the category page too

To avoid pr conflict, @Yomzy2223  can work on the the categories page since he is already working on the categories page.

2024-08-19 17:16 UTC, Simplypheyie96 approved these changes

2024-08-20 08:41 UTC, Tolu-Mals commented
When the user doesn't have a username, it should show the address instead of being blank

![Screenshot 2024-08-20 at 9 39 40 AM](https://github.com/user-attachments/assets/668a7642-ef81-4587-a6d8-02a8aabf3e55)

Reference - Activity Card
![Screenshot 2024-08-20 at 9 40 16 AM](https://github.com/user-attachments/assets/b3325a2b-57ac-47da-861a-fbd2e7b77a75)

2024-08-20 08:42 UTC, Softdev1 approved these changes

2024-08-20 10:43 UTC, Tolu-Mals approved these changes

2024-08-20 11:04 UTC, merged