No Wiki History View
EveripediaNetwork/ep-ui pull request #248
Opened 2022-05-06 15:22 UTC by codiejay

# No Wiki History View
_Users now see a "No wiki history" UI when a wiki has just been created and has zero commits._
## Linked issues

closes #298, closes #298, closes https://github.com/EveripediaNetwork/issues/issues/298

2022-05-06 15:59 UTC, Royal-lobster requested changes

2022-05-06 15:59 UTC, Royal-lobster commented on src/components/Wiki/History/NoHistoryView.tsx
> +      mb={{ base: '96' }}
```suggestion
      mt={{ base: '12', lg: '24' }}
```
margin bottom is giving too much white space the bottom. i think the page padding is enough for balance. 22 is not in chakra spacing list so its applying 22px. make it 24 so it gives enough space. also added 12 to make the space smaller in mobile devices and to be consistent with margin top on the sentence

2022-05-06 15:59 UTC, Royal-lobster commented on src/components/Wiki/History/NoHistoryView.tsx
> +      <Box mt={{ lg: '32', base: '12' }} textAlign="center">
```suggestion
      <Box mt={{ base: '12', lg: '24' }} textAlign="center">
```
Made this 24 as well to balance the margin top at the picture

2022-05-09 15:32 UTC, Royal-lobster commented on src/components/Wiki/History/NoHistoryView.tsx
> +      mb={{ base: '12' }}
```suggestion
```
Margin at the bottom seems to be too much. i think padding of page is enough for space

2022-05-09 19:11 UTC, anubra266 commented on src/components/Wiki/History/NoHistoryView.tsx
> +      justifyContent={{ base: 'center' }}
Nothing wrong here, but just so you know, when the component is a `<Flex/>` you can do:
```sugestion
      align={{ base: 'center' }}
      justify={{ base: 'center' }}
```

2022-05-09 19:14 UTC, anubra266 commented on src/components/Wiki/History/NoHistoryView.tsx
> +      justifyContent={{ base: 'center' }}
Nothing wrong here, but just so you know, when the component is a `<Flex/>` you can do:
```sugestion
      align={{ base: 'center' }}
      justify={{ base: 'center' }}
```

2022-05-09 21:30 UTC, anubra266 commented on src/components/Wiki/History/NoHistoryView.tsx
> +        justifyContent={{ base: 'center' }}
If you're not having different breakpoints and just `base`, then you don't need the object syntax.
```suggestion
        alignItems="center"
        justifyContent="center"
```

2022-05-09 22:33 UTC, anubra266 approved these changes

2022-05-09 23:25 UTC, Royal-lobster approved these changes

2022-05-10 07:39 UTC, merged