Fixing margin on About Hero section.
EveripediaNetwork/ep-ui pull request #277
Opened 2022-05-20 19:34 UTC by codiejay

## How should this be tested?

1. Step one
2. Step two
3. ...

## Notes or observations

_jot down something here_

## Linked issues

closes #330, closes #330, closes https://github.com/EveripediaNetwork/issues/issues/330

2022-05-20 21:56 UTC, Emmanueldmlr commented
The blog section looks shrank.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/70170061/169617571-443443c5-023a-4a54-b6e0-375a17f0354d.png">

2022-05-20 21:59 UTC, Emmanueldmlr commented
They are all supposed to be horizontally displayed.
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/70170061/169617869-b3586387-fa9d-4b77-bc15-17d203eb8d5c.png">

2022-05-20 22:06 UTC, Emmanueldmlr commented
The hero margin is a bit off on a larger screen 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/70170061/169618521-d70d27da-354d-47b5-aff3-8407e6b246a0.png">

2022-05-23 08:38 UTC, Emmanueldmlr commented
@codiejay, the margin is off on small screen 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/70170061/169779056-e766a3c0-22c3-4d40-9a35-184fa72cddec.png">

and also on medium screen
<img width="328" alt="image" src="https://user-images.githubusercontent.com/70170061/169779261-ece85189-82ce-4255-8343-be3ff7512e0e.png">

2022-05-23 09:02 UTC, codiejay commented
> @codiejay, the margin is off on small screen <img alt="image" width="410" src="https://user-images.githubusercontent.com/70170061/169779056-e766a3c0-22c3-4d40-9a35-184fa72cddec.png">
> 
> and also on medium screen <img alt="image" width="328" src="https://user-images.githubusercontent.com/70170061/169779261-ece85189-82ce-4255-8343-be3ff7512e0e.png">

oh that's weird @Emmanueldmlr , cause I have a different view on my local. 
Let me fix that

2022-05-23 10:56 UTC, Emmanueldmlr commented
@codiejay, can you add a margin-top to the hero and space the hero elements out on a smaller and medium screen...Am I right @Simplypheyie96?

<img width="200" alt="image" src="https://user-images.githubusercontent.com/70170061/169804412-d49d91b3-ea10-4f59-9736-ea18d878513b.png">

2022-05-23 10:59 UTC, Simplypheyie96 commented
> @codiejay, can you add a margin-top to the hero and space the hero elements out on a smaller and medium screen...Am I right @Simplypheyie96?
> 
> <img alt="image" width="200" src="https://user-images.githubusercontent.com/70170061/169804412-d49d91b3-ea10-4f59-9736-ea18d878513b.png">

Yes you are.

2022-05-24 11:07 UTC, kesar commented
@codiejay make sure in the PR description you attach images of before / after and different screens. That way its easier for reviewers 👍🏻 and that will force you to make sure it works fine before pushing it for reviewing.

Take as inspiration:
https://github.com/EveripediaNetwork/ep-ui/pull/257
https://github.com/EveripediaNetwork/ep-ui/pull/280
https://github.com/EveripediaNetwork/ep-ui/pull/279
https://github.com/EveripediaNetwork/ep-ui/pull/275

2022-05-24 11:51 UTC, Simplypheyie96 commented
Please do tag me for reviews so i can point out mistakes in ui @codiejay

2022-05-24 12:02 UTC, Emmanueldmlr commented
@codiejay , the 3rd blog card seems broken...you can inspect to know what's wrong, maybe the length of the text or the height of the card.
![image](https://user-images.githubusercontent.com/70170061/170029783-a026c5f5-40de-4cf4-a477-145f31fc173f.png)

2022-05-24 12:04 UTC, Emmanueldmlr commented
@codiejay, this is what it used to be like.
![image](https://user-images.githubusercontent.com/70170061/170030302-454ddd17-b813-4214-b27d-0dc8336ddd3b.png)

2022-05-24 12:07 UTC, Emmanueldmlr commented
That will be all from my side. @Simplypheyie96, do you have any other issues you think he should correct?.

2022-05-24 12:28 UTC, Simplypheyie96 requested changes
<img width="551" alt="image" src="https://user-images.githubusercontent.com/99387231/170034298-64900400-b262-4be4-b54e-fce6c944739e.png">
This image is for the dark mode.

This is for the light mode. you will see it in the zip file I sent
<img width="559" alt="image" src="https://user-images.githubusercontent.com/99387231/170034460-e93bdc20-ae5b-4f7e-a449-d337ab496e0d.png">

2022-05-24 12:34 UTC, Simplypheyie96 commented
As seen in section should be this way 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/99387231/170035848-ff124848-1e0e-4dc0-85f9-0f8eccdfb28e.png">
@codiejay

2022-05-24 12:39 UTC, Simplypheyie96 commented
The font sizes of sub-texts are too small and fonts in general are not in alignment with the homepage of everipedial

2022-05-29 11:58 UTC, Simplypheyie96 requested changes
Is there something we can do to make this not stretched? When i changed the zoom, i discovered that it shrinks as the size gets smaller. can we do something about that? Other cards don't behave that way.
<img width="969" alt="image" src="https://user-images.githubusercontent.com/99387231/170866829-610f9115-c3b9-4bb5-9c5a-cb0ae6a5b576.png">

Also, is there a way to not make the words sit atop each other? It shouldn't be more than 2 lines.
<img width="325" alt="image" src="https://user-images.githubusercontent.com/99387231/170866883-1ecff7f6-629b-4a03-a752-9d16933cb84f.png">

2022-05-30 20:51 UTC, anubra266 commented on src/components/About/AboutOurTeam.tsx
> +                  h="150px"
You can do
```suggestion
                  boxSize="150px"
```

2022-05-31 10:21 UTC, Simplypheyie96 approved these changes
It looks good now. Good to go!

2022-05-31 10:23 UTC, merged