Redesign for Career page.
EveripediaNetwork/ep-ui pull request #285
Opened 2022-05-24 12:08 UTC by codiejay

Redesign for Career page. 
Previously we had just a text that said "Career page". But now we have implemented the design for career page WHEN there are no openings. 

## Linked issues

closes #312, closes #312, closes https://github.com/EveripediaNetwork/issues/issues/312

2022-05-24 12:13 UTC, Simplypheyie96 commented
@codiejay  I need the link where i can view the implementation. the visit preview link is taking back to the homepage

2022-05-24 12:15 UTC, Simplypheyie96 commented
> @codiejay I need the link where i can view the implementation. the visit preview link is taking back to the homepage

found it. never mind

2022-05-24 12:16 UTC, Simplypheyie96 approved these changes
Looks great!

2022-05-24 13:09 UTC, kesar commented
I would suggest to remove the CTA it looks very redundant being so close to the other subscription button (same in figma)

![image](https://user-images.githubusercontent.com/1288106/170042103-444660b5-b75b-4f32-8d86-f3a363921be2.png)

![image](https://user-images.githubusercontent.com/1288106/170042128-98bcb503-e4cb-4faf-8072-e781fa688ab8.png)

cc: @Simplypheyie96 not big deal, but i guess in mobile looks very strange

2022-05-24 13:11 UTC, Simplypheyie96 commented
> I would suggest to remove the CTA it looks very redundant being so close to the other subscription button (same in figma)
> 
> ![image](https://user-images.githubusercontent.com/1288106/170042103-444660b5-b75b-4f32-8d86-f3a363921be2.png)
> 
> ![image](https://user-images.githubusercontent.com/1288106/170042128-98bcb503-e4cb-4faf-8072-e781fa688ab8.png)
> 
> cc: @Simplypheyie96 not big deal, but i guess in mobile looks very strange

oohh. okay. i will adjust that too

2022-05-24 13:12 UTC, kesar commented
![image](https://user-images.githubusercontent.com/1288106/170042857-ed8945f6-3702-4555-b095-cff6ab608cf9.png)
vs 
![image](https://user-images.githubusercontent.com/1288106/170042879-e84661a9-b72d-46f4-8196-1e5c790a5033.png)

also title seems very off to the left compared w other pages

2022-05-24 13:14 UTC, Simplypheyie96 commented
> ![image](https://user-images.githubusercontent.com/1288106/170042857-ed8945f6-3702-4555-b095-cff6ab608cf9.png) vs ![image](https://user-images.githubusercontent.com/1288106/170042879-e84661a9-b72d-46f4-8196-1e5c790a5033.png)
> 
> also title seems very off to the left compared w other pages

The guidelines page was not designed in figma and was just brought from the old everipedia page. The careers title was designed in line with other titles on the everipedia page. like the activity page, the search result page etc.

2022-05-24 13:18 UTC, kesar commented
![image](https://user-images.githubusercontent.com/1288106/170044111-9cf8757a-c0d0-48fa-bb0d-9a21bcbd9756.png)

![image](https://user-images.githubusercontent.com/1288106/170044154-04510589-c236-4872-8ac6-dabbd76b3201.png)

![image](https://user-images.githubusercontent.com/1288106/170044192-0e6e3ba9-7036-4a44-b79e-bccd2c64f6a2.png)

the three headers are different, so I guess we need to get some kind of harmony w the titles

2022-05-24 13:29 UTC, Simplypheyie96 commented
@kesar should i open new issues for all of these?

2022-05-24 19:19 UTC, anubra266 commented on src/components/Careers/NoOpeningsCard.tsx
> +      />
We could skip this one, but it's far better and performant to use SVGs for our illustrations.

2022-05-24 19:22 UTC, anubra266 requested changes

2022-05-24 19:22 UTC, anubra266 commented on src/pages/static/careers.tsx
> +  console.log(openings)
We should remove console logs

2022-05-24 19:22 UTC, anubra266 commented on src/pages/static/careers.tsx
> +  const [openings] = React.useState<Array<any> | null>()
What's the purpose of this? It's always going to be undefined

2022-05-24 19:26 UTC, codiejay commented on src/pages/static/careers.tsx
> +  const [openings] = React.useState<Array<any> | null>()
For now we don't really have live data to simulate with. So for now we have this and will refactor one we have a list of opening to loop through. (if i added a `[openings, setOpenings] `, I'll have a Type Error where I declared a var but never used it.

2022-05-25 11:59 UTC, anubra266 approved these changes

2022-05-25 12:01 UTC, merged