FAQ Page UI implemented
EveripediaNetwork/ep-ui pull request #308
Opened 2022-06-02 20:08 UTC by codiejay

FAQ page was previously blank but this PR is implementing the UI from the Figma design. 
Also the text are somewhat dynamic as they come from the translation logic:  

Preview: https://monopedia-ui-git-342-redesign-faq-page-prediqt.vercel.app/static/faq

## Linked issues

closes #342, closes #342, closes https://github.com/EveripediaNetwork/issues/issues/342

2022-06-02 20:35 UTC, Simplypheyie96 commented
the icons on the mobile looks weird too
spacing on mobile is really huge. 
I'll give you cue when i'm done. you can re-inspect on figma

2022-06-04 00:46 UTC, anubra266 requested changes

2022-06-04 00:46 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +          boxShadow={accordionShadow}
For better performance, rather than use the color mode hook:

```suggestion
          boxShadow="0px 0px 20px 11px #80808012"
          _dark={{ boxShadow: 'none' }}
```

2022-06-04 00:46 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +  const accordionBg = useColorModeValue('#ffffff', '#2D3748')
use the `_dark` pseudo prop instead, or better still add the color set to the `semanticTokens` file, and then reference the added key here.

2022-06-04 00:46 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +  faqData: Array<any>
Avoid the `any` type please, it defeats the purpose of typescript.
faqData is an array of objects, so give it that type.
```suggestion
  faqData: Record<string, string>[]
```

Find out more [here](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) to know exactly how that type works, and if you might need to tweak it.

2022-06-04 00:46 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +  icon: any
Use the Icon type
```ts
import { IconType } from 'react-icons/lib'

type SampleType {
  ...
  icon: IconType
}

2022-06-04 00:46 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +      {faqData.map((item: any, index: any) => {
After defining the type for `faqData` well, you won't even need any type here

2022-06-04 00:46 UTC, anubra266 commented on src/pages/static/faq.tsx
> +console.log(RiSettings2Fill)
Let's remove this

2022-06-04 00:46 UTC, anubra266 commented on src/pages/static/faq.tsx
> +  const faqData = [
Now that I see `faqData` it's self deductive, 

But just define it's type

```ts

type FaqDataItemData = {
  header: string;
  body: string;
}

export type FaqDataItem = {
  keyword: string;
  icon: IconType;
  data: FaqDataItemData[];
}


const faqData: FaqDataItem = [
 //the content you already have 
]
```

I've added `export` to `FaqDataItem` so you can use it to define the type for the props of the components you'll send it too.

2022-06-05 17:43 UTC, codiejay commented on src/components/Faq/FaqAccordion.tsx
> +          boxShadow={accordionShadow}
To avoid applying a shadow when on dark mode, that's why I did that. 
Does it affect performance to use `useColorModeValue`

2022-06-05 20:20 UTC, anubra266 requested changes

2022-06-05 20:20 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +                    {/* <AccordionIcon /> */}
Can we just remove this, if it's not being used?
```suggestion
```

2022-06-05 20:20 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +                    lineHeight={{ base: '2' }}
We don't need the responsive syntax, when the only breakpoint is base.
```suggestion
                    lineHeight={2}
```

2022-06-05 20:20 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +      <Flex gap={{ base: 2 }} align="center" justify="center" w="fit-content">
```suggestion
      <Flex gap={2} align="center" justify="center" w="fit-content">

2022-06-05 20:20 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +          mt={{ base: 5 }}
```suggestion
          mt={5}
```

2022-06-05 20:20 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +      {faqData.map((item, index: any) => {
No `any` type please, `index` is a number. Besides I suppose, you don't need to type it, because typescript already knows it's a number.
```suggestion
      {faqData.map((item, index) => {
```
OR
```suggestion
      {faqData.map((item, index: number) => {
```

2022-06-05 21:50 UTC, anubra266 approved these changes

2022-06-05 21:50 UTC, anubra266 commented on src/components/Faq/FaqAccordion.tsx
> +      <Flex gap={{ base: 2 }} align="center" justify="center" w="fit-content">
It's not resolved.

2022-06-06 11:32 UTC, Simplypheyie96 approved these changes
Great work!

2022-06-06 11:34 UTC, Simplypheyie96 commented
![Screenshot_2022-06-06-12-33-15-534_com android chrome](https://user-images.githubusercontent.com/99387231/172152933-efb48f0f-0d3f-43a0-92ca-36c6fc225a92.jpg)
A little bit of space before the footer & it'll be awesome @codiejay

2022-06-07 12:23 UTC, Simplypheyie96 approved these changes
Awesome!
You are good now.

2022-06-07 13:08 UTC, merged