UI/UI Fixes for activity and wiki page
EveripediaNetwork/ep-ui pull request #326
Opened 2022-06-08 18:52 UTC by codiejay

![image](https://user-images.githubusercontent.com/30846348/172693472-e7b1acc5-eb15-46d7-a162-ff441a3a1305.png)
before: 

![image](https://user-images.githubusercontent.com/30846348/172693564-c97fee8e-f958-4258-8704-d3fee3a0b972.png)
after 

![image](https://user-images.githubusercontent.com/30846348/172693736-5d7764d6-bf20-4e4c-b1b0-0fda85f3deab.png)
before: 

![image](https://user-images.githubusercontent.com/30846348/172693777-62f73f41-8b08-49f6-a670-9a58d7861f51.png)
after:

## Linked issues

closes #395, closes #395, closes https://github.com/EveripediaNetwork/issues/issues/395

2022-06-09 08:13 UTC, kesar commented
I think you linked wrong issue

2022-06-09 08:20 UTC, codiejay commented
> I think you linked wrong issue

Oopps; fixed this, thanks for the headsup.

2022-06-14 13:20 UTC, Simplypheyie96 requested changes
<img width="882" alt="image" src="https://user-images.githubusercontent.com/99387231/173586754-c5e1d985-a8e3-4755-9376-f762494e8e29.png">
the paddings on both sides of every wiki are yet to be added.

Also, check out this section of the wiki. there should be a little bit of space here before the footer starts

2022-06-14 13:21 UTC, Simplypheyie96 commented
@kesar, concerning the issue of line height, are you seeing a difference on your screen. yours is quite larger and can be easily visible

2022-06-14 13:25 UTC, Simplypheyie96 commented
This is the design on figma. notice the paddings on both sides. That is what every wiki should look like
<img width="834" alt="image" src="https://user-images.githubusercontent.com/99387231/173588016-66e71599-462e-45d6-bb3c-1cc093b38bf9.png">

2022-06-14 23:32 UTC, anubra266 requested changes

2022-06-14 23:32 UTC, anubra266 commented on src/pages/revision/[id].tsx
> +                      display={{ lg: 'none', base: 'block', md: 'none' }}
If `md` and `lg` are the same, you don't need `lg`, because it's a higher breakpoint than `md`
```suggestion
                      display={{ base: 'block', md: 'none' }}
```

2022-06-14 23:32 UTC, anubra266 commented on src/pages/revision/[id].tsx
> +                        md: 'row',
Same here, no need for `lg`
```suggestion
                        md: 'row',
```

2022-06-14 23:32 UTC, anubra266 commented on src/pages/revision/[id].tsx
> +                      display={{ base: 'block', lg: 'none', md: 'none' }}
```suggestion
                      display={{ base: 'block', md: 'none' }}
```

2022-06-14 23:32 UTC, anubra266 commented on src/pages/wiki/[slug]/index.tsx
> +  metadata: any[]
```suggestion
type Meta = {
  id: CommonMetaIds
  value: string
}

const MobileMeta = (wiki: {
  metadata: Meta[]
```

2022-06-14 23:32 UTC, anubra266 commented on src/pages/wiki/[slug]/index.tsx
> +                      metadata={wiki.metadata}
If the type defined gets disturbing, you can do
```suggestion
                      metadata={wiki.metadata as Meta[]}
```

2022-06-15 19:38 UTC, codiejay commented on src/pages/revision/[id].tsx
> +                      display={{ lg: 'none', base: 'block', md: 'none' }}
So the thing is for this UI we need to specify for `MD`. I will explain this offline

2022-06-16 15:41 UTC, Simplypheyie96 approved these changes
great work. @codiejay

2022-06-16 15:54 UTC, kesar approved these changes

2022-06-16 15:58 UTC, merged