Refactors and Fixes Wiki and Revision pages
EveripediaNetwork/ep-ui pull request #344
Opened 2022-06-20 12:04 UTC by Royal-lobster

Fixes https://github.com/EveripediaNetwork/issues/issues/431

# Changes
1. made wiki main content and insights bar to span all the way till actions bar
2. refactored wiki page mobile view to make code dry
3. extracted wiki page structure to ```WikiMarkup``` component which is common to revision and wiki pages 
4. removed widths for wiki main content and insights bar and replaced it with paddings and min-max widths to make implementation simpler

2022-06-20 12:18 UTC, Emmanueldmlr commented
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/70170061/174599920-11d567cb-6a24-45d3-a4a5-eb1ca983f8d8.png">

not sure if it's related to this PR, but I got this for the wiki with media.

ref. link: https://monopedia-orioblm3b-prediqt.vercel.app/wiki/remember-you-will-have-to-manually-add-that

2022-06-20 12:29 UTC, Simplypheyie96 reviewed
Everything looks good except for the issue @Emmanueldmlr pointed out about the media thing.

2022-06-20 14:23 UTC, anubra266 requested changes

2022-06-20 14:23 UTC, anubra266 commented on src/components/Wiki/WikiPage/WikiMarkup.tsx
> +                base: 'block',
```suggestion
            <chakra.div
              display={{
                base: 'block',

2022-06-21 00:07 UTC, Softdev1 reviewed
Yeah, what @Emmanueldmlr  pointed out should be fixed actually, that is the only issue

2022-06-21 05:16 UTC, Royal-lobster commented
> Yeah, what @Emmanueldmlr  pointed out should be fixed actually, that is the only issue 

@Softdev1 the bug is fixed in the previous commit, here is the updated url https://monopedia-ui-git-fix-wiki-layout-page-prediqt.vercel.app/wiki/remember-you-will-have-to-manually-add-that

2022-06-21 07:53 UTC, Emmanueldmlr approved these changes
Nice.

2022-06-21 17:21 UTC, Softdev1 approved these changes

2022-06-21 17:21 UTC, merged