fix build errors
EveripediaNetwork/ep-ui pull request #345
Opened 2022-06-20 16:07 UTC by Royal-lobster

Fixes https://github.com/EveripediaNetwork/issues/issues/435

2022-06-20 18:12 UTC, anubra266 approved these changes

2022-06-21 00:02 UTC, Softdev1 requested changes
The issue is not resolved, the predicted tags are not selectable
![Screenshot (289)](https://user-images.githubusercontent.com/32770520/174690710-a6773c8c-8998-44a5-a9fa-4c04c1c84f72.png)
e

2022-06-21 05:41 UTC, Royal-lobster commented
> The issue is not resolved, the predicted tags are not selectable ![Screenshot (289)](https://user-images.githubusercontent.com/32770520/174690710-a6773c8c-8998-44a5-a9fa-4c04c1c84f72.png) e

Which phrases are you trying ? currently the suggestions are only suggested from this predefined list https://github.com/EveripediaNetwork/issues/issues/395#issuecomment-1157550917

https://user-images.githubusercontent.com/52039218/174724199-d8209194-a164-48b2-84f5-351af2631c97.mp4

2022-06-21 17:08 UTC, merged

2022-06-21 17:11 UTC, Softdev1 reviewed
All looks good now