fixed the braines bg
EveripediaNetwork/ep-ui pull request #346
Opened 2022-06-20 20:46 UTC by OleanjiKingCode

# Braines background in the right place

_this fixes and removes the branies bg from the whole page to only the trandeing section page

## How should this be tested?

1. Before
![Screenshot 2022-06-20 214131](https://user-images.githubusercontent.com/75235148/174675528-b3d786b4-5363-43de-ad41-4bbe0951bcca.png)

2.Now

![Screenshot 2022-06-20 214500](https://user-images.githubusercontent.com/75235148/174675578-576bd47a-5e18-46c4-ac2d-fa51217f30e0.png)

## Linked issues
 closes https://github.com/EveripediaNetwork/issues/issues/434

2022-06-20 20:57 UTC, Emmanueldmlr commented
<img width="389" alt="image" src="https://user-images.githubusercontent.com/70170061/174676718-9c10a7d5-bae6-4624-985c-8623e167850a.png">

@OleanjiKingCode, it seems the update affected the mobile view of the categories.

2022-06-20 21:14 UTC, Simplypheyie96 commented
@OleanjiKingCode can't find the link to preview

2022-06-20 21:46 UTC, Emmanueldmlr commented
> @OleanjiKingCode can't find the link to preview

https://monopedia-2cbw4zksr-prediqt.vercel.app/

2022-06-20 22:06 UTC, Simplypheyie96 requested changes
seems like the padding for the categories section had been affected in the md and sm breakpoints

2022-06-21 01:34 UTC, anubra266 approved these changes

2022-06-21 08:06 UTC, Simplypheyie96 approved these changes
great job. you are good to go!

2022-06-21 11:45 UTC, merged