User Profiles Support
EveripediaNetwork/ep-ui pull request #354
Opened 2022-06-23 15:16 UTC by Royal-lobster

## [DRAFT]
Closes https://github.com/EveripediaNetwork/issues/issues/351

2022-06-28 00:41 UTC, anubra266 requested changes

2022-06-28 00:41 UTC, anubra266 commented on src/pages/account/SignTokenMessage.tsx
> +      <Center p={4} mt="25vh" mb="25vh">
```suggestion
      <Center p={4} my="25vh">

2022-06-28 00:41 UTC, anubra266 commented on src/pages/account/SignTokenMessage.tsx
> +      <Modal isOpen={isOpen} isCentered onClose={onClose}>
Has chakra UI fixed the issue of modals not closing well? cause if not we'll need to account for that by conditionally rendering the moal

2022-06-28 06:32 UTC, Royal-lobster commented on src/pages/account/SignTokenMessage.tsx
> +                  h="35px"
Thanks for the suggestion ! i didn't know about this one

2022-06-28 06:36 UTC, Royal-lobster commented on src/pages/account/SignTokenMessage.tsx
> +      <Modal isOpen={isOpen} isCentered onClose={onClose}>
I think they fixed it, the scroll is working fine when modal is closed

2022-07-05 05:24 UTC, anubra266 commented on src/components/Settings/ImageUpload.tsx
> +          >
I think this could just use `Center`
```suggestion
      <Center w="max-content">
        {isLoading && (
          <Box
            zIndex={9}
            bgColor="pageBg"
            p={2}
            borderRadius="50%"
          >

2022-07-05 15:44 UTC, Royal-lobster commented on src/components/Settings/ImageUpload.tsx
> +          >
Ohh thanks ! i will test it out with center

2022-07-06 10:09 UTC, Royal-lobster commented on src/components/Settings/ImageUpload.tsx
> +          >
@anubra266 nope did not work, the loader went side to the image instead of being on top.

2022-07-07 10:45 UTC, kesar commented
video is really impressive!

functionality looks fine, but we need to change username / avatar  in wiki cards, wiki page, etc if the user has set one.

not need to block this PR, we could merge this and create a follow up issue for that if needed.

2022-07-07 11:21 UTC, Simplypheyie96 approved these changes
Everything looks amazing. Great work srujan. 
One thing is that the links are not included in the user profile in the design and we might need to integrate that on the user profile.

2022-07-08 09:36 UTC, kesar commented on src/pages/account/[profile].tsx
> +          src={`${config.pinataBaseUrl}${profileData?.banner}`}
we should have a default bg in case user has no banner (not the old one, perhaps just a grey bg or something along those lines)

2022-07-08 09:40 UTC, anubra266 commented on src/pages/account/SignTokenMessage.tsx
> +      {isOpen && (
You said the modal issue was fixed, we wouldn't need this in that case

2022-07-08 09:50 UTC, Royal-lobster commented on src/pages/account/SignTokenMessage.tsx
> +      {isOpen && (
Nope the issues remains, for some reason the bug started to showing up, when closing the modal the page is getting stuck. so i added the fix back in

2022-07-08 10:04 UTC, kesar commented on src/pages/account/[profile].tsx
> +          src={`${config.pinataBaseUrl}${profileData?.banner}`}
there is a request call to ipfs/undefined then this image needs to be conditional 👍🏻

2022-07-08 10:53 UTC, Royal-lobster commented on src/pages/account/[profile].tsx
> +          src={`${config.pinataBaseUrl}${profileData?.banner}`}
ahh i missed that 😅

2022-07-08 14:01 UTC, merged