Fix tags page
EveripediaNetwork/ep-ui pull request #360
Opened 2022-06-25 12:55 UTC by OleanjiKingCode

#Fixed Tag header design issue.

_The tags page header was different from what was in the figma design 

## How should this be tested?

1. Before

![Screenshot (266)](https://user-images.githubusercontent.com/75235148/175774349-78269f0e-efba-48fe-b8d4-d145b0467e1d.png)

2.Now
![Screenshot (270)](https://user-images.githubusercontent.com/75235148/175774357-8c00aeba-fd1e-4bd7-beb1-5c4a91fc5e8a.png)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/438

2022-06-27 07:24 UTC, Royal-lobster commented on src/pages/tags/[tag].tsx
>        <Box bgColor="pageBg" border="solid 1px transparent" pb={12}>
```suggestion
      <Box bgColor="pageBg" mt={-2} border="solid 1px transparent" pb={12}>
```

This fixes the gap between the page and navbar

![CleanShot 2022-06-27 at 12 53 42@2x](https://user-images.githubusercontent.com/52039218/175883059-6d331661-d915-4dfc-99e9-01c1b7ca33d6.png)

2022-06-27 08:21 UTC, Emmanueldmlr requested changes

2022-06-27 08:21 UTC, Emmanueldmlr commented on src/components/Landing/CategoriesList.tsx
> +        px={{ base: 6, lg: 0 }}
since py and px are the same, you could do p={{base:6, lg:0}} instead.

2022-06-27 10:20 UTC, anubra266 approved these changes

2022-06-27 10:21 UTC, anubra266 approved these changes
After @Emmanueldmlr's suggestion of course

2022-06-28 08:13 UTC, Emmanueldmlr approved these changes

2022-06-28 08:54 UTC, merged