Fixed the empty routing
EveripediaNetwork/ep-ui pull request #401
Opened 2022-07-04 10:55 UTC by OleanjiKingCode

# Fixed the empty routing

_Removed the empty routing buttons in the learn more page about everipedia

## How should this be tested?

1.Before

![image](https://user-images.githubusercontent.com/75235148/177140752-35d68a0e-6f2a-4c6b-9d83-2998de8fe06a.png)

2. Now
![image](https://user-images.githubusercontent.com/75235148/177140763-e9967010-ca6c-4784-b3f6-066dc55027ed.png)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/473

2022-07-04 11:54 UTC, kesar commented
@OleanjiKingCode plz next time tag any of your other dev colleagues if its something simple like removing buttons or so on. I do try to review everything when I have time, but Its better if you am not specific assigned to a particular PR unless its something that we have architectural questions (that you can always tag me for specific questions / feedback) 👍🏻 

Thanks and great work 🚀

2022-07-04 11:57 UTC, OleanjiKingCode commented
> @OleanjiKingCode plz next time tag any of your other dev colleagues if its something simple like removing buttons or so on. I do try to review everything when I have time, but Its better if I am not assigned to a particular PR unless its something that we have architectural questions (that you can always tag me for specific questions / feedback) 👍🏻
> 
> Thanks and great work 🚀

sorry sir it was a mistake

2022-07-04 12:06 UTC, Emmanueldmlr commented
Nice @OleanjiKingCode .

But @Simplypheyie96, don't you think this will look better if the header is aligned to the center. 
![image](https://user-images.githubusercontent.com/70170061/177151402-0a860f94-80d5-4d67-bb51-d0263ab5c20c.png)

Just a side thought.

2022-07-04 12:10 UTC, Simplypheyie96 commented
> Nice @OleanjiKingCode .
> 
> But @Simplypheyie96, don't you think this will look better if the header is aligned to the center. ![image](https://user-images.githubusercontent.com/70170061/177151402-0a860f94-80d5-4d67-bb51-d0263ab5c20c.png)
> 
> Just a side thought.

If this is on mobile, it should be centre aligned.
Everything on sm/md is usually centre aligned

2022-07-04 12:12 UTC, Emmanueldmlr commented
> > Nice @OleanjiKingCode .
> > But @Simplypheyie96, don't you think this will look better if the header is aligned to the center. ![image](https://user-images.githubusercontent.com/70170061/177151402-0a860f94-80d5-4d67-bb51-d0263ab5c20c.png)
> > Just a side thought.
> 
> If this is on mobile, it should be centre aligned. Everything on sm/md is usually centre aligned

@OleanjiKingCode, you can make the header center-aligned on md then.

2022-07-04 15:27 UTC, Softdev1 commented
@OleanjiKingCode the <h2> texts are poorly aligned, kindly look into it .

2022-07-04 15:28 UTC, Softdev1 requested changes
@OleanjiKingCode  the <h2> is poorly aligned, try and align it properly.

2022-07-05 05:22 UTC, anubra266 approved these changes

2022-07-05 14:37 UTC, OleanjiKingCode commented
> if you implement those changes that are needed.

ive implemented the center and its aligned correctly

2022-07-05 18:39 UTC, OleanjiKingCode commented
> <img alt="image" width="1437" src="https://user-images.githubusercontent.com/70170061/177369032-780aa31e-a379-4f2a-bbd0-3425fa968523.png">
> 
> @OleanjiKingCode , the header is supposed to be left aligned on large screens.

I thought that but @Softdev1 said its okay so I wanted to ask @Simplypheyie96  if its okay before i change it

2022-07-05 19:14 UTC, Simplypheyie96 commented
> > <img alt="image" width="1437" src="https://user-images.githubusercontent.com/70170061/177369032-780aa31e-a379-4f2a-bbd0-3425fa968523.png">
> > @OleanjiKingCode , the header is supposed to be left aligned on large screens.
> 
> I thought that but @Softdev1 said its okay so I wanted to ask @Simplypheyie96 if its okay before i change it

it's not okay. It should be left aligned on larger screens, just like the homepage

2022-07-06 05:25 UTC, OleanjiKingCode commented
> > > <img alt="image" width="1437" src="https://user-images.githubusercontent.com/70170061/177369032-780aa31e-a379-4f2a-bbd0-3425fa968523.png">
> > > @OleanjiKingCode , the header is supposed to be left aligned on large screens.
> > 
> > 
> > I thought that but @Softdev1 said its okay so I wanted to ask @Simplypheyie96 if its okay before i change it
> 
> it's not okay. It should be left aligned on larger screens, just like the homepage

Done ......can I now merge

2022-07-06 09:33 UTC, Emmanueldmlr approved these changes

2022-07-06 10:59 UTC, merged