Rearranging the Mobile wiki page content
EveripediaNetwork/ep-ui pull request #468
Opened 2022-07-20 14:30 UTC by OleanjiKingCode

# Rearranging the Mobile wiki page content

_Since our priority should be the wiki content and not the commit message then i rearranged the mobile wiki view to show the content first.

## How should this be tested?
By opening up a wiki on mobile

1. Before   
![image](https://user-images.githubusercontent.com/75235148/180006967-3592abf6-e8f7-41c0-98a4-529957f834fb.png)

2. Now
![image](https://user-images.githubusercontent.com/75235148/180006933-63f1d274-332c-428d-8c6b-4ab4fdcf7844.png)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/511

2022-07-20 14:35 UTC, kesar commented
i would just collapse the commit message. main pic is powerful to get context of the wiki, i would not remove that as first element

2022-07-20 14:47 UTC, OleanjiKingCode commented
> i would just collapse the commit message. main pic is powerful to get context of the wiki, i would not remove that as first element





Sir what do you mean by collapsing?  i dont really get it

2022-07-20 14:48 UTC, OleanjiKingCode commented
> i would just collapse the commit message. main pic is powerful to get context of the wiki, i would not remove that as first element





Sir what do you mean by collapsing?  i dont really get it

2022-07-20 16:47 UTC, kesar commented
<img width="376" alt="Captura de Pantalla 2022-07-20 a las 18 46 38" src="https://user-images.githubusercontent.com/1288106/180037988-904e2483-165b-4fbd-9303-abf22105ae1a.png">

this by default only in mobile

2022-07-20 20:32 UTC, kesar commented
there are a bunch of widgets collapsed on desktop and mobile that were not in the specs.

The specs mentioned the commit msg. Some like twitter or related widgets sounds like a good idea to be collapsed by default on mobile, so feel free to keep it, but no reason for that on desktop since we have a bunch of space to fill on the screen 👍🏻

2022-07-21 07:25 UTC, OleanjiKingCode commented
> there are a bunch of widgets collapsed on desktop and mobile that were not in the specs.
> 
> The specs mentioned the commit msg. Some like twitter or related widgets sounds like a good idea to be collapsed by default on mobile, so feel free to keep it, but no reason for that on desktop since we have a bunch of space to fill on the screen 👍🏻

yes sir im sorry i missed that... done now tho

2022-07-21 08:16 UTC, kesar requested changes

2022-07-21 08:16 UTC, kesar commented on src/components/Wiki/WikiAccordion/index.tsx
> +  xl: boolean
this naming should change. Nobody will know without checking implementation what's the meaning of xl or base.

to follow chakra style of props we could send an object of breakpoints and define if we want them collapsed or not. make it optional and default to non-collapsed if prop is not defined.

```
      <WikiAccordion title="Media" collapsed={{base: false, xl: false}}> ...
```

2022-07-21 14:00 UTC, kesar approved these changes

2022-07-21 14:07 UTC, merged