Dynamic color for icon on Profile Summary
EveripediaNetwork/ep-ui pull request #471
Opened 2022-07-21 12:29 UTC by codiejay

<img width="450" alt="image" src="https://user-images.githubusercontent.com/30846348/180213347-278a20c7-d886-4472-993d-0cb07d55ee23.png"> Before 

<img width="447" alt="image" src="https://user-images.githubusercontent.com/30846348/180213438-fdc1a228-72f3-4ae8-be90-2442b69ae620.png"> After 

## Linked issues

closes #522, closes #522, closes https://github.com/EveripediaNetwork/issues/issues/522

2022-07-21 12:36 UTC, Simplypheyie96 reviewed
it is kind of too bright compared to the rest of the elements. i used White alpha-700 in the design. Also, the Instagram and twitter icon seems a bit out of alignment with the others
![image](https://user-images.githubusercontent.com/99387231/180214742-fa4763ce-3ba4-42f7-9bce-2a211fe9f5e5.png)

2022-07-21 12:40 UTC, Softdev1 approved these changes

2022-07-21 13:27 UTC, Royal-lobster commented on src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
> +    icon: <EmailIcon />,
@codiejay great work ! small suggestion, instead of fixing the colors styles directly inside icons, i believe it would be simpler if you create something like 

```javascript
const socialIconsStyles = {
    _dark: {{ fill: 'white', _hover: { fill: 'brand.500' } }}
    _light: {{ fill: '#4A5568', _hover: { fill: 'brand.500' } }}
}
```

and then pass the styles to all icons like this
```javascript
icon: <EmailIcon {...socialIconsStyles} />
```

that way we can simply change the common styles

2022-07-21 14:56 UTC, anubra266 commented on src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
> +    icon: <EmailIcon />,
@Royal-lobster @codiejay The best way to go about it is do `<Icon fill="currentColor" />` in the icon itself. THis way, whatever you use as color becomes the `fill`. So afterwards you can use `_dark={{color:"..."}}` as usual, or just use semanticTokens. `color="colorToken"`

2022-07-21 15:01 UTC, anubra266 commented on src/components/Icons/telegramIcon.tsx
> +      _light={{ fill: '#4A5568', _hover: { fill: 'brand.500' } }}
We should'nt do this in our icons. It makes them hardly reusable.

2022-07-21 15:26 UTC, Royal-lobster commented on src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
> +    icon: <EmailIcon />,
@anubra266 this is cool ! so currentColor takes the context of color prop passed to the component right ?

2022-07-21 15:34 UTC, anubra266 commented on src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
> +    icon: <EmailIcon />,
@Royal-lobster It's not really a react prop context thing, it's pure html svg css functionality. It takes whatever it finds as the color style value and uses it as `currentColor`

2022-07-21 19:05 UTC, Royal-lobster commented on src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
> +    icon: <EmailIcon />,
Ooooo i don't know that. thanks for the info 😇

2022-07-22 13:28 UTC, Simplypheyie96 approved these changes

2022-07-22 13:34 UTC, anubra266 approved these changes

2022-07-22 13:36 UTC, anubra266 requested changes
<img width="320" alt="CleanShot 2022-07-22 at 14 35 16@2x" src="https://user-images.githubusercontent.com/30869823/180450503-27b751ff-ff5d-49f5-9f70-25633885bb30.png">
The vertical spacing is bad, you could use a `Wrap` component instead of `HStack` and add a `spacingY` attribute

2022-07-22 13:37 UTC, Royal-lobster commented
@codiejay the icons need some gaps between rows

<img width="374" alt="CleanShot 2022-07-22 at 19 02 49@2x" src="https://user-images.githubusercontent.com/52039218/180449953-8e4338bd-7a40-4c43-b9bc-e829b0524c1a.png">

2022-07-22 13:37 UTC, anubra266 commented on src/components/Wiki/WikiPage/InsightComponents/ProfileSummary.tsx
>                  .map((social: { value: string; id: string }, i: any) => {
Let's change the `any` type here. `i` is a number

2022-07-22 13:38 UTC, Simplypheyie96 commented
> <img alt="CleanShot 2022-07-22 at 14 35 16@2x" width="320" src="https://user-images.githubusercontent.com/30869823/180450503-27b751ff-ff5d-49f5-9f70-25633885bb30.png">
> 
> The vertical spacing is bad, you could use a `` component instead of `` and add a `spacingY` attribute

oh wow. i didn't see this because it's a line on my end.

2022-07-22 15:20 UTC, anubra266 requested changes
<img width="345" alt="CleanShot 2022-07-22 at 16 19 06@2x" src="https://user-images.githubusercontent.com/30869823/180470947-a0f4986d-c5ef-4246-bf2e-d69811de604c.png">
This looks weird, let's use a facebook svg that starts the text at the beginning, this particular one is usually used with a background, but since we're not doing that, we shoud change it.

2022-07-22 15:44 UTC, codiejay commented
> <img alt="CleanShot 2022-07-22 at 16 19 06@2x" width="345" src="https://user-images.githubusercontent.com/30869823/180470947-a0f4986d-c5ef-4246-bf2e-d69811de604c.png">
> 
> This looks weird, let's use a facebook svg that starts the text at the beginning, this particular one is usually used with a background, but since we're not doing that, we shoud change it.

@Simplypheyie96 is it possible you get us an icon like so?

2022-07-22 15:48 UTC, Simplypheyie96 commented
> > <img alt="CleanShot 2022-07-22 at 16 19 06@2x" width="345" src="https://user-images.githubusercontent.com/30869823/180470947-a0f4986d-c5ef-4246-bf2e-d69811de604c.png">
> > This looks weird, let's use a facebook svg that starts the text at the beginning, this particular one is usually used with a background, but since we're not doing that, we shoud change it.
> 
> @Simplypheyie96 is it possible you get us an icon like so?

i don't recall understand what you mean by a facebook icon that starts it's text at the beginning. you mean like this:
![image](https://user-images.githubusercontent.com/99387231/180476210-11543c1c-2d91-428b-badc-f1fd3ebd9a3e.png)

2022-07-22 15:50 UTC, codiejay commented
> > > <img alt="CleanShot 2022-07-22 at 16 19 06@2x" width="345" src="https://user-images.githubusercontent.com/30869823/180470947-a0f4986d-c5ef-4246-bf2e-d69811de604c.png">
> > > This looks weird, let's use a facebook svg that starts the text at the beginning, this particular one is usually used with a background, but since we're not doing that, we shoud change it.
> > 
> > 
> > @Simplypheyie96 is it possible you get us an icon like so?
> 
> i don't recall understand what you mean by a facebook icon that starts it's text at the beginning. you mean like this: ![image](https://user-images.githubusercontent.com/99387231/180476210-11543c1c-2d91-428b-badc-f1fd3ebd9a3e.png)

<img width="606" alt="image" src="https://user-images.githubusercontent.com/30846348/180476373-06cabeb6-eb02-48b2-924d-dee1d4a5681a.png">

This is the Facebook Icon I see on Figma. Could you send me this one you just posted?

2022-07-22 15:51 UTC, Simplypheyie96 commented
it's on figma now. i just changed it

2022-07-22 16:06 UTC, Simplypheyie96 approved these changes
perfect!

2022-07-22 16:08 UTC, anubra266 approved these changes

2022-07-22 16:09 UTC, merged