Removed icon, Text margins smaller and made sub-cat card links
EveripediaNetwork/ep-ui pull request #489
Opened 2022-07-23 14:36 UTC by OleanjiKingCode

# Removed Cetgory page icon, Reduced Text margins and made sub-category card to link to pages

This Pr fixes the text margins , Category icons removed & linked sub-category cards

## How should this be tested?
By checking the Category page and sub-category pages, the text margins are smaller and the icons are removed as well as the sub-category cards are now linked to their respective pages.

 How they now look compared to before 
![image](https://user-images.githubusercontent.com/75235148/180609639-6e50a7bf-f25a-4d89-be0f-e0013618547b.png)

![image](https://user-images.githubusercontent.com/75235148/180609645-20bf17c5-5ccc-480e-817a-34bc534f0efa.png)

![image](https://user-images.githubusercontent.com/75235148/180609647-628778b1-4b25-4798-b625-4bc44a4977b3.png)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/551

2022-07-23 17:33 UTC, kesar commented
I would suggest we increase lines in order to fit descriptions in 2 lines, similar to what opensea has.

also i think margin between separator (line) and content (top & bottom) should be the same

<img width="1439" alt="Captura de Pantalla 2022-07-23 a las 19 30 37" src="https://user-images.githubusercontent.com/1288106/180616313-8c5df110-4d3d-4f9c-800d-83c7c5f8f253.png">
<img width="1440" alt="Captura de Pantalla 2022-07-23 a las 19 30 23" src="https://user-images.githubusercontent.com/1288106/180616315-2eff5480-6802-433f-ab45-c9210528331a.png">

2022-07-23 19:22 UTC, Simplypheyie96 commented
@kesar pointed out all the changes already. I wanted to mention that on desktop, the lines are remains 2 lines no matter the size of the desktop screen.

2022-07-24 11:02 UTC, Simplypheyie96 requested changes
@kesar  pointed out all the changes already. I wanted to mention that on desktop, the lines are remains 2 lines no matter the size of the desktop screen.

2022-07-24 12:31 UTC, OleanjiKingCode commented
Okay @kesar

2022-07-25 08:51 UTC, kesar commented
<img width="909" alt="Captura de Pantalla 2022-07-25 a las 10 50 54" src="https://user-images.githubusercontent.com/1288106/180737439-033d4004-668a-4b61-b961-0f03f38c7db8.png">

margins should have some kind of consistency

2022-07-25 09:44 UTC, OleanjiKingCode commented
> 

![image](https://user-images.githubusercontent.com/75235148/180748161-bece4b11-28a9-453f-abe5-4419127a9ec7.png)
 Hows this?

2022-07-25 09:48 UTC, kesar approved these changes

2022-07-25 10:04 UTC, merged