Design syncs 3.0
EveripediaNetwork/ep-ui pull request #600
Opened 2022-08-30 15:51 UTC by Royal-lobster

# WIP

2022-08-31 08:52 UTC, kesar commented
coming back to the hero buttons @Simplypheyie96 what if we keep Explore (perhaps another name?) as primary action and Create we change it for Learn More and remove the link? I think we have create in navigation and it shouldnt be an action a normal user can perform when they hit the landing

2022-08-31 13:29 UTC, Simplypheyie96 commented
> coming back to the hero buttons @Simplypheyie96 what if we keep Explore (perhaps another name?) as primary action and Create we change it for Learn More and remove the link? I think we have create in navigation and it shouldnt be an action a normal user can perform when they hit the landing

Totally on point. Explore just fits the purpose of the site perfectly, so I think it is fine. 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/99387231/187689649-8d320561-7dbf-4dde-8fc5-e917d943f3b6.png">

PS: I Have a little deal with some changes on figma, but I will work on the copy by tomorrow. I need to inspect all of the files on everipedia and IQ dashboard and others to set things right.

2022-09-01 08:22 UTC, kesar commented
lets try to get this merged before call so we show some updates regarding landing and page. If more changes are needed we can add a new PR later.

2022-09-01 09:02 UTC, kesar approved these changes

2022-09-01 10:16 UTC, Simplypheyie96 commented
![image](https://user-images.githubusercontent.com/99387231/187890872-b36acdad-5e3c-4b00-b2ad-b72619fab18d.png)
@Royal-lobster this should be learn more

2022-09-01 10:33 UTC, Simplypheyie96 requested changes
![image](https://user-images.githubusercontent.com/99387231/187890872-b36acdad-5e3c-4b00-b2ad-b72619fab18d.png)
@Royal-lobster this should be learn more

![image](https://user-images.githubusercontent.com/99387231/187891078-806961a8-b43d-431e-883d-aaa0345dcf8e.png)
the help center should be "IQ Learn"
![image](https://user-images.githubusercontent.com/99387231/187891366-254a2cb4-c7cf-4d86-a680-2e0d35c0db2a.png)
wrong colors here in dark mode. and wrong pink in light and dark mode
correct pink for "wallet" in light mode is brand 500
correct text color and pink in dark mode is alphaa-white 500/ Brand 800

2022-09-01 11:08 UTC, Royal-lobster commented on src/utils/i18n.js
> +      learnMoreHeroBttn: 'Learn',
```suggestion
      learnMoreHeroBttn: 'Learn More',
```

2022-09-01 11:08 UTC, Royal-lobster commented on src/utils/i18n.js
> +      learnMoreHeroBttn: 'Learn',
```suggestion
      learnMoreHeroBttn: 'Learn More',
```

2022-09-01 11:08 UTC, Royal-lobster commented on src/utils/i18n.js
> +      learnMoreHeroBttn: 'Learn',
```suggestion
      learnMoreHeroBttn: 'Learn More',
```

2022-09-01 11:37 UTC, kesar approved these changes

2022-09-01 12:54 UTC, merged