Fixes wiki flagging system UI
EveripediaNetwork/ep-ui pull request #715
Opened 2022-09-19 09:11 UTC by Adebesin-Cell

Fixes wiki flagging system UI

related to https://github.com/EveripediaNetwork/issues/issues/676

2022-09-19 10:08 UTC, Simplypheyie96 reviewed
The pink stroke shouldn't be there. The text inside the box should be gray 800. and the pink color in dark mode is wrong
![image](https://user-images.githubusercontent.com/99387231/190993956-0f5d5df8-31bb-4041-a9ce-79cc38b835a5.png)

In dark mode, the same issues, the gray text shouldn't be on dark mode, the stroke colors are wrong
![image](https://user-images.githubusercontent.com/99387231/190995177-1578bed0-d3c0-492b-8a10-22ba2d97ea36.png)

2022-09-19 11:21 UTC, Simplypheyie96 requested changes
Nothing happens upon clicking confirm after making a report
wrong colors in dark mode
![image](https://user-images.githubusercontent.com/99387231/191006078-2fa2f80b-2853-485a-9b33-e34c51fc4312.png)
![image](https://user-images.githubusercontent.com/99387231/191006181-a3a2d067-c3ad-4f85-b0da-cf086d66ac9a.png)
![image](https://user-images.githubusercontent.com/99387231/191006215-3179dc2b-fda6-454c-8fea-143fba78de69.png)

2022-09-21 15:27 UTC, Simplypheyie96 reviewed
Great work

2022-09-21 15:34 UTC, kesar commented
![mindblowing](https://media.giphy.com/media/V0IdVIIW1y5d6/giphy.gif)

2022-09-21 15:49 UTC, Royal-lobster approved these changes

2022-09-21 15:52 UTC, Softdev1 requested changes
after login , the toast still flags please login to continue which i showed you already

2022-09-21 15:57 UTC, Royal-lobster commented
> 

@Softdev1 I pushed a fix for this, now it should allow flagging after login.

2022-09-21 15:58 UTC, Softdev1 commented
Awesome welldone @Adebesin-Cell  @Royal-lobster

2022-09-21 18:49 UTC, Adebesin-Cell commented
Thanks @Simplypheyie96 and @Softdev1.

2022-09-21 19:22 UTC, Softdev1 approved these changes
This is great now 
welldone @Adebesin-Cell

2022-09-22 01:04 UTC, anubra266 commented on src/components/Wiki/WikiPage/WikiFlaggingSystem.tsx
> +                color: 'whiteAlpha.900',
Let's use `semanticTokens` instead

2022-09-22 01:08 UTC, anubra266 commented on src/components/Wiki/WikiPage/WikiFlaggingSystem.tsx
> +              background="brand.500"
Semantic tokens.
```suggestion
              background="brandLinkColor"

2022-09-22 01:09 UTC, anubra266 commented on src/components/Wiki/WikiPage/WikiFlaggingSystem.tsx
> +            ml="4px"
```suggestion
            ml="1"

2022-09-22 01:10 UTC, anubra266 commented on src/components/Wiki/WikiPage/WikiFlaggingSystem.tsx
> +              <Icon fontSize={{ base: '16px', sm: '20px' }} as={RiFlagFill} />
```suggestion
              <Icon fontSize={{ base: '4', sm: '5' }} as={RiFlagFill} />

2022-09-22 11:01 UTC, kesar commented
👍👍👍 lets merge to show today

2022-09-22 11:03 UTC, anubra266 approved these changes

2022-09-22 11:07 UTC, merged