Fixes italic markdown
EveripediaNetwork/ep-ui pull request #739
Opened 2022-09-23 09:33 UTC by Adebesin-Cell

Fixes italic markdown

fixes https://github.com/EveripediaNetwork/issues/issues/737

2022-09-23 09:41 UTC, kesar approved these changes

2022-09-23 09:42 UTC, kesar requested changes

2022-09-23 09:42 UTC, kesar commented on src/components/Wiki/WikiPage/WikiMainContent.tsx
> +      rehypePlugins={[rehypeRaw]}
ideally we should parse HTML only in editor. The problem its that this could lead into some html injection which could steal user credentials

2022-09-23 09:54 UTC, Softdev1 approved these changes

2022-09-23 10:37 UTC, Adebesin-Cell commented on src/components/Wiki/WikiPage/WikiMainContent.tsx
> +      rehypePlugins={[rehypeRaw]}
@Royal-lobster and I are experimenting to work it out from the editor. Though I got a solution: 
![Screenshot 2022-09-23 105832](https://user-images.githubusercontent.com/66301634/191943208-89b08642-35b9-4f0b-ade5-e919254a90bb.jpg)

2022-09-23 10:40 UTC, kesar commented on src/components/Wiki/WikiPage/WikiMainContent.tsx
> +      rehypePlugins={[rehypeRaw]}
ohh nice idea. then i think we could use it w that 👍🏻

2022-09-23 11:11 UTC, Royal-lobster commented on src/components/Wiki/WikiPage/WikiMainContent.tsx
> +      rehypePlugins={[rehypeRaw]}
@kesar we found the issue, it is that when user selects the text which has some charecters immediately to next to it, the editor seems to decorate it with html tags instead of traditional markdown syntax. we are looking for a fix for this so we no longer need to use hehype-raw. if we fail to find any we can proceed with rehype-raw + rehype-sanitize it also filters the iframes and other dangerous attributes on html tags 
 
![image](https://user-images.githubusercontent.com/52039218/191947689-2d04bfaf-c8eb-4fd0-b1d7-2bf7dc457bc6.png)

2022-09-23 11:56 UTC, Softdev1 approved these changes

2022-09-23 12:17 UTC, Softdev1 approved these changes

2022-09-24 01:05 UTC, Softdev1 approved these changes

2022-09-25 09:04 UTC, kesar approved these changes

2022-09-25 09:04 UTC, merged