Fixes wiki flagging system validation
EveripediaNetwork/ep-ui pull request #741
Opened 2022-09-23 14:23 UTC by Adebesin-Cell

Fixes wiki flagging system validation

fixes https://github.com/EveripediaNetwork/issues/issues/746

2022-09-23 14:29 UTC, Royal-lobster requested changes

2022-09-23 14:29 UTC, Royal-lobster commented on src/components/Wiki/WikiPage/WikiFlaggingSystem.tsx
> +              disabled={buttonIsDisabaled}
@Adebesin-Cell instead this can be done in a single line
```suggestion
              disabled={flagContent.trim().length === 0}
```

2022-09-23 14:35 UTC, kesar approved these changes

2022-09-23 16:43 UTC, Adebesin-Cell commented on src/components/Wiki/WikiPage/WikiFlaggingSystem.tsx
> +              disabled={buttonIsDisabaled}
Okay thanks @Royal-lobster.

2022-09-23 20:50 UTC, Royal-lobster approved these changes

2022-09-24 01:04 UTC, Softdev1 approved these changes

2022-09-24 08:37 UTC, merged