wiki page responsive fix
EveripediaNetwork/ep-ui pull request #746
Opened 2022-09-25 20:01 UTC by Adebesin-Cell

wiki page responsive fix

fixes https://github.com/EveripediaNetwork/issues/issues/724

2022-09-25 20:17 UTC, Simplypheyie96 requested changes
- Add border-radius to the widget boxes
- Spacing between the first widget and the commit info seems to small
- padding on the sides too small
- padding in the widgets looks small and kind of squished.

2022-09-26 14:01 UTC, Royal-lobster approved these changes

2022-09-26 14:54 UTC, Softdev1 approved these changes

2022-09-26 15:55 UTC, Simplypheyie96 requested changes
- padding above not consistent with padding below in this widget box giving it a  weird look
<img width="316" alt="image" src="https://user-images.githubusercontent.com/99387231/192317518-87d08c65-bcef-4ea7-b1c4-32da81c9e58e.png">
The padding on the right is really small. this is related to widgets being too wide too
<img width="36" alt="image" src="https://user-images.githubusercontent.com/99387231/192320354-af04ca7e-83dd-4004-a54b-024a1f2b4fb2.png">
- Twitter widget scroll not working

-might not be part of the wiki page but please help rewrite this sub-heading. 'curiousities' shouldn't be sitting alone. you can check figma homepage for md bp to fix this 
<img width="530" alt="image" src="https://user-images.githubusercontent.com/99387231/192318610-3497d6e4-d314-4cb3-839a-7f5a33488622.png">

2022-09-27 11:18 UTC, Simplypheyie96 approved these changes

2022-09-27 11:30 UTC, merged