Fixes SEO review
EveripediaNetwork/ep-ui pull request #817
Opened 2022-10-08 04:15 UTC by Adebesin-Cell

Fixes SEO review

fixes https://github.com/EveripediaNetwork/issues/issues/784

2022-10-08 08:11 UTC, kesar commented
done:
no index for revisions
revisions title should be same as wiki (missing category i think)

are you sure all pages have proper titles / descriptions ?
review seo titles / descriptions per page
review other static pages / sections to make sure they have title and description

2022-10-08 08:28 UTC, Softdev1 approved these changes

2022-10-08 09:05 UTC, kesar requested changes
done:
no index for revisions
revisions title should be same as wiki (missing category i think)

are you sure all pages have proper titles / descriptions ?
review seo titles / descriptions per page
review other static pages / sections to make sure they have title and description

2022-10-10 19:45 UTC, kesar commented on src/components/SEO/Activity.tsx
> +    title="Activities | IQ.Wiki | Largest Blockchain & Crypto Encyclopedia "
let me review all this before merging 👍🏻

2022-10-10 20:19 UTC, Royal-lobster commented on src/components/SEO/Activity.tsx
> +    title="Activities | IQ.Wiki | Largest Blockchain & Crypto Encyclopedia "
@Adebesin-Cell you can remove the`| IQ.Wiki | Largest Blockchain & Crypto Encyclopedia` currently we have the default tralier as `| IQ.Wiki |` or you can also edit the template if you are aiming for the short description in title

https://github.com/EveripediaNetwork/ep-ui/blob/51217485ade526e56bd6f4ddfa6f41e9b03b6454/src/components/SEO/Default.tsx#L12

2022-10-10 22:31 UTC, kesar commented on src/components/SEO/Default.tsx
> +    titleTemplate="%s | IQ.Wiki | Largest Blockchain & Crypto Encyclopedia"
```suggestion
    titleTemplate="%s | IQ.Wiki"
```

2022-10-10 22:32 UTC, kesar commented on src/components/SEO/Static.tsx
> +    title="Jobs | Opportunities at"
```suggestion
    title="Jobs"
```

2022-10-10 22:32 UTC, kesar commented on src/components/SEO/Static.tsx
> +      title: 'Jobs | Opportunities at',
```suggestion
      title: 'Jobs',
```

2022-10-11 08:40 UTC, kesar commented on src/pages/search/[query].tsx
> +interface SearchQueryProps {
im seeing unrelated to this branch changes, can you make sure this is not gonna lead in some overwrite / unexpected bugs ?

2022-10-11 09:23 UTC, Adebesin-Cell commented on src/pages/search/[query].tsx
> +interface SearchQueryProps {
The search result page was acting weird during my SEO review yesterday. So, I had to fix it to give proper titles and descriptions. I also improved the loading state. And I resolved some conflicts on the branch yesterday.

2022-10-11 09:26 UTC, kesar approved these changes

2022-10-11 09:34 UTC, Royal-lobster approved these changes

2022-10-11 10:07 UTC, merged