Dynamic linking for logo from categories.
EveripediaNetwork/ep-ui pull request #819
Opened 2022-10-08 16:19 UTC by codiejay

When logo is clicked from categories or any other page it loads dynamically to the home page. 
closes https://github.com/EveripediaNetwork/issues/issues/797

2022-10-08 18:02 UTC, Royal-lobster approved these changes

2022-10-08 18:05 UTC, kesar commented
its missing add proper linking to the categories in the homepage (that's why I took the screen) 👍🏻

2022-10-08 21:07 UTC, codiejay commented
> its missing add proper linking to the categories in the homepage (that's why I took the screen) 👍🏻

Fixed this.

2022-10-08 23:47 UTC, Royal-lobster requested changes

2022-10-08 23:47 UTC, Royal-lobster commented on src/components/Landing/CategoriesList.tsx
> +            <LinkBox
@codiejay for this use LinkOverlay from the custom component in `components/elements/link`

we wrote custom components for all link items in that directory with chakra + next link

2022-10-10 10:21 UTC, codiejay commented on src/components/Landing/CategoriesList.tsx
> +            <LinkBox
There is a bug with the link overlay where it makes the whole page one big link. Will send you a demo privately.

2022-10-10 13:11 UTC, Royal-lobster commented on src/components/Landing/CategoriesList.tsx
>                  {category.title}
@codiejay you can wrap the `LinkOverlay` just for title, it links the entire card in `LinkBox`

2022-10-10 13:11 UTC, Royal-lobster commented on src/components/Landing/CategoriesList.tsx
> -            key={category.id}
for key, you can just wrap the `LinkBox` with div and pass the key to that div. we can handle this with react forwardRef but this is simplier in this case.

2022-10-10 14:16 UTC, kesar approved these changes

2022-10-10 22:37 UTC, merged