Editor leaderboard
EveripediaNetwork/ep-ui pull request #824
Opened 2022-10-10 11:35 UTC by Emmanueldmlr

# The idea is to show the top editors for a period of time and their earnings

fixes https://github.com/EveripediaNetwork/issues/issues/613

2022-10-10 11:38 UTC, Emmanueldmlr commented
@kesar, I'm done with the UI design. I want to know if the API is ready.

2022-10-10 11:42 UTC, Simplypheyie96 reviewed
why not have other variations like on figma instead of just cesar all through? @Emmanueldmlr

2022-10-10 11:45 UTC, Simplypheyie96 requested changes
Also, the editors have different trophies for the !st, 2nd and 3rd editor, the a star for the rest of the editors.
ps: will the implementation of the top editor for user profile be on this pr too? @Emmanueldmlr 
![image](https://user-images.githubusercontent.com/99387231/194858911-d4668509-328f-4ba4-8214-a257b0a91d44.png)

2022-10-10 11:45 UTC, Simplypheyie96 requested changes
Also, the editors have different trophies for the !st, 2nd and 3rd editor, the a star for the rest of the editors.
ps: will the implementation of the top editor for user profile be on this pr too? @Emmanueldmlr 
![image](https://user-images.githubusercontent.com/99387231/194858911-d4668509-328f-4ba4-8214-a257b0a91d44.png)

2022-10-10 11:58 UTC, Emmanueldmlr commented
@Simplypheyie96, it's just mock data, they will change once I integrate it with the right endpoint.

2022-10-10 12:26 UTC, Emmanueldmlr commented
@OleanjiKingCode, let me know when you are available for a sync up.

2022-10-10 14:30 UTC, Emmanueldmlr commented
@OleanjiKingCode, let me know when you are done with the update we discussed.

2022-10-10 14:36 UTC, Emmanueldmlr commented
Oh...I already switched to the pending issue on the IQ dashboard.

2022-10-12 20:16 UTC, Emmanueldmlr commented
@OleanjiKingCode, what's the status of the ranking and value format we discussed on the call?

2022-10-13 10:15 UTC, Emmanueldmlr commented
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/70170061/195570407-24078b2c-aeec-471c-8526-89e9f0d2b8b7.png">

@Simplypheyie96, what we have now

2022-10-13 10:27 UTC, Emmanueldmlr commented
@OleanjiKingCode @kesar, I think we will need an endpoint to get the list of editors well ranked having their rank included as part of the object property, and also, another endpoint to fetch a single editor with the rank included. That will take off the sorting I'm doing on the front end and I will be able to display their individual rank on their profile too. @kesar, let me know what you think about it.

2022-10-13 10:28 UTC, Emmanueldmlr commented
What we currently have worked though.

2022-10-13 10:33 UTC, Emmanueldmlr commented
> can you elaborate the reason? I think w current graph you can get top 10 order by earnings to show the UI of all time.
> 
> >

I have implemented this. This is working fine.

2022-10-13 10:34 UTC, Emmanueldmlr commented
> yes, for now what we can do its to query the current graph to see if he has rewards. If he has rewards, we can query the top 3 to see if it needs a trophy icon or a star icon

This works then... @OleanjiKingCode, this is the update you need to make to the graph.

2022-10-13 10:37 UTC, Emmanueldmlr commented
@OleanjiKingCode, let me know when you are done. @kesar, pending the time @OleanjiKingCode is working on this, is there any other issue I can jump on?

2022-10-13 10:44 UTC, kesar commented
@Emmanueldmlr 

{
  editors(where: {Address}) {
    TotalRewards
  }
}

using where in editors you can get if the user has result for his profile
and using editors sorted by total rewards limit 3 you can see if he is in top 3

with that you should have all that you need for the v1

2022-10-13 10:50 UTC, Emmanueldmlr commented
Nice, I will do this. Thanks

2022-10-15 17:18 UTC, Emmanueldmlr commented
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/70170061/195999499-e66f8a67-2e57-4ea6-8c46-68e92bf83706.png">

2022-10-17 18:07 UTC, kesar commented on src/data/LeaderBoardData.ts
> +export const LEADERBOARD_DATA = [
this can be removed if its already using API

2022-10-17 20:31 UTC, Emmanueldmlr commented
removed now.

2022-10-18 09:40 UTC, kesar approved these changes

2022-10-19 13:43 UTC, kesar commented
merge and add env vars in vercel for dev and prod

2022-10-19 13:53 UTC, merged