Updating sloting function for promoting wikis
EveripediaNetwork/ep-ui pull request #866
Opened 2022-10-12 20:10 UTC by codiejay

- [ ] allow full urls on revalidate widget
- [x] make promote work correctly
- [ ] make archive / unarchive perform a revalidate action after graph is called

closes https://github.com/EveripediaNetwork/issues/issues/815

2022-10-18 07:04 UTC, kesar commented
lets get a review and merge if works as expected for this plz cc: @Softdev1 @Royal-lobster

2022-10-18 12:15 UTC, Softdev1 requested changes
The promote wiki is not still working as expected @codiejay

2022-10-18 12:22 UTC, codiejay commented
> The promote wiki is not still working as expected @codiejay

Working on it. This is just a bit weird cause locally everything works just fine.

2022-10-18 13:56 UTC, Softdev1 commented
This would better help to guide on what is really happening with it. When a wiki is been promoted, on the admin panel it shows that it is promoted with the right tag but on the UI side of things you get incorrect info.  it seems the revalidate wiki is not working well for the promoted wiki
![this is not working at all ](https://user-images.githubusercontent.com/32770520/196449964-147c4ecd-bfa5-496e-a3ed-017631525324.png)

2022-10-20 08:15 UTC, kesar commented
whats the status of this? still in development ?

2022-10-20 15:52 UTC, Softdev1 commented
@kesar  he is not done fixing this issue that is why it is still opened sir @kesar  , I still reached out to him about this

2022-10-21 13:40 UTC, Royal-lobster requested changes

2022-10-21 13:40 UTC, Royal-lobster commented on src/components/Admin/WikiCreatedInsight/PromoteCreatedWikisModal.tsx
>          let toastMessage =
@codiejay we can move the toast logic to the `handlePromoteWiki` function to make the code dry

2022-10-23 11:07 UTC, Royal-lobster approved these changes

2022-10-24 07:09 UTC, Royal-lobster approved these changes

2022-10-24 08:27 UTC, merged

2022-10-24 08:27 UTC, kesar commented
letss gooo