Ranking page
EveripediaNetwork/ep-ui pull request #926
Opened 2022-10-31 23:41 UTC by codiejay

- [ ] Create Ranking page 
- [ ] Create UI in accordance to Figma design 
- [ ] Fetch real data from endpoint. 

closes https://github.com/EveripediaNetwork/issues/issues/818

2022-11-19 23:20 UTC, Simplypheyie96 requested changes
i guess you are still working on it but it is not done yet. the spacing between header and content is too much and there are still a lot of details that have been swapped or not properly executed yet. 
It is best to inspect the design on figma to make sure details are correct.
Also, the dark mode too is not properly done yet as well as other breakpoints.

2022-11-20 20:03 UTC, codiejay commented
> i guess you are still working on it but it is not done yet. the spacing between header and content is too much and there are still a lot of details that have been swapped or not properly executed yet. It is best to inspect the design on figma to make sure details are correct. Also, the dark mode too is not properly done yet as well as other breakpoints.

Just updated now. Thnks!

2022-11-21 09:09 UTC, Simplypheyie96 requested changes
- [ ] Add background color for the header in light mode
![image](https://user-images.githubusercontent.com/99387231/203009009-468fe8fd-d2bd-4920-92f3-09dac6e33175.png)
- [ ] Align this properly like on figma and rework the font size/type and color for this part, both in light/dark mode. Inspect this part in figma again properly to see what I mean.
![image](https://user-images.githubusercontent.com/99387231/203009901-bd0a0530-d74e-405c-bc6c-b769973f193c.png)
- [ ] reduce the distance between these guys too
![image](https://user-images.githubusercontent.com/99387231/203010207-2495114b-1ce7-4739-87a0-44962cc13ce0.png)

2022-11-23 10:23 UTC, Simplypheyie96 requested changes
Header looks like this on my 13inches laptop.
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/99387231/203521571-742a9de1-1c53-4b6d-8de9-e34c3be830c4.png">
i think we have to do something about the numbers here to prevent it from breaking like this in mobile bp/tablet too
![image](https://user-images.githubusercontent.com/99387231/203522957-411b112f-50a7-44ce-90f7-52016473ef57.png)
there are still some corrections to be made on the mobile bp/tablet
![image](https://user-images.githubusercontent.com/99387231/203523136-9a22b466-5e6a-464c-9525-f836a15d1b36.png)

2022-11-24 09:24 UTC, Simplypheyie96 requested changes
Tablet doesn't look good yet. 
![image](https://user-images.githubusercontent.com/99387231/203746321-563fc31b-4540-4d62-b61c-3281d8b662ea.png)

2022-11-25 15:24 UTC, Simplypheyie96 requested changes
This is all that is left i think. It is joined together here.
![image](https://user-images.githubusercontent.com/99387231/204015439-9bb03419-d9f7-428c-bef3-1c88015f541d.png)

2022-11-28 09:28 UTC, Simplypheyie96 commented
I think the ui looks good now

2022-12-14 08:35 UTC, Royal-lobster commented
<img width="1426" alt="CleanShot 2022-12-14 at 14 02 22@2x" src="https://user-images.githubusercontent.com/52039218/207545656-0a87ca39-1966-42df-9646-2c59d11eb224.png">

i think the tables are not symmetric, probably because i am viewing from 13 inch. how about we center the tables so it looks good on all viewports ?

2022-12-14 11:34 UTC, Softdev1 commented
I thought I pointed this out to you @codiejay  about the centralizing the table since they are just two and you said you would discuss with @Simplypheyie96  please ensure to discuss please

2022-12-14 18:42 UTC, Simplypheyie96 requested changes
@codiejay change color in light mode to brand 500 for the prev/next buttons
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/99387231/207683368-e30dd353-21fd-473d-9e7b-e5f71822a92f.png">

then this page on md bp needs to fixed. 
<img width="173" alt="image" src="https://user-images.githubusercontent.com/99387231/207684104-f03c6ba7-1def-4530-9fdc-9960fffc9cf2.png">

2022-12-14 23:47 UTC, Simplypheyie96 requested changes
Now the dark mode needs to be brand 800 for the buttons :(
<img width="758" alt="image" src="https://user-images.githubusercontent.com/99387231/207739492-8fe2dcd1-829f-4e7d-b0f4-a722d6a8dbfa.png">

2022-12-15 12:04 UTC, merged

2022-12-15 12:27 UTC, Royal-lobster commented on src/components/Rank/RankCardItem.tsx
> +  }
@codiejay since these both functions are same you can remove `getTokenAlias`. also it can be shortened to this 

```typescript
  const getAlias = (text: string) => (text ?? 'Unknown') || ""
```

2022-12-15 12:27 UTC, Royal-lobster commented on src/components/Rank/RankCard.tsx
> +            }}
```suggestion
            onClick={offsetIncrease}
```

just incase you don't know but you can give the function name to onClick, it calls it with minimum syntax !

2022-12-15 12:27 UTC, Royal-lobster commented on src/components/Rank/RankCard.tsx
> +        })
wow thats cleaver but i don't think we can use hooks that way 😅 i think its better if we create a custom hook in `services/ranking/utils.tsx` which takes in kind and gives the data. like this

```javascript
const useRankingQuery = ({kind, limit, offset}) => {
	const [data, setData] = useState()
	const [loading, setLoading] = useState(false)
	useEffect(()=>{
		setLoading(true);
		let data = []
		if(kind === 'NFT')
			data = (await store.dispatch(getNftRanking.initiate({kind, limit, offset}))).data
		else
			data = (await store.dispatch(getTokenRanking.initiate({kind, limit, offset}))).data
		setLoading(false);
	}, [])
	return {data, loading}
}
```

then later use the query in this place 

```javascript
const {data: nftsQuery, loading} = useRankingQuery({
	kind: queryKind,
	limit: 10,
	offset: queryLimit,
})
```

this should remove linting issues, flexible for new changes changes and also abstracts the logic well

2022-12-15 12:27 UTC, Royal-lobster commented on src/components/Rank/InvalidRankCardItem.tsx
> +              {/* <AiFillCaretUp color={upIndicationIconColor} /> */}
```suggestion
```

2022-12-19 11:32 UTC, codiejay commented on src/components/Rank/RankCard.tsx
> +        })
This is a way logical way to do it, but the issue we have is accessing the object inside of data. 
The dataset returned by NFTQuery is different from the query returned by Tokenquery. 

But my logic is a bit off especially with the lint issue. I will find a way incorporating your idea and fix this. 
Thanks again!

2022-12-19 13:54 UTC, Royal-lobster commented on src/components/Rank/RankCard.tsx
> +        })
Hmm, i don't think it works since hooks should be called top level of a react component or another hook. is it working ?