Branding Page
EveripediaNetwork/ep-ui pull request #936
Opened 2022-11-03 13:25 UTC by codiejay

- [x] Create static page for branding 
- [x] Import brand images 
- [ ] Implement download as .png and .svg 

closes https://github.com/EveripediaNetwork/issues/issues/831

2022-11-03 18:13 UTC, Simplypheyie96 requested changes
one of the cards on the third row seems to be broken
![image](https://user-images.githubusercontent.com/99387231/199801104-74d56980-3557-4816-8094-6fdbe1fb80a9.png)

there should be options to download as png/svg, both means transparency. and the background shouldn't be downloaded together. as I earlier mentioned, they are separate entities.

There is an issue on top of the page too
![image](https://user-images.githubusercontent.com/99387231/199801709-074d69f2-b2f9-4722-a6d7-0dbe742b09ed.png)

looking good so far

2022-11-04 16:28 UTC, Simplypheyie96 requested changes
There is no way to go back to the log after clicking on download. I designed with an intention of the the download options to be an overlay. 
what was implemented is a good idea, but it would be nice if logos can go back to original position on click
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/99387231/200025961-d1ddebc2-985a-488f-abf8-4351b08ce9d9.png">

I don't know why this part is missing
<img width="360" alt="image" src="https://user-images.githubusercontent.com/99387231/200026557-a424d092-7c72-4d0a-8baa-dd67d2f4b4a9.png">

on tablet and mobile, the spacing at the very top is too small.
<img width="511" alt="image" src="https://user-images.githubusercontent.com/99387231/200026675-16302f6f-a32b-4530-9e9f-98cd867b496a.png">
great job so far

2022-11-06 14:23 UTC, Simplypheyie96 approved these changes
Awesome work!!

2022-11-07 08:28 UTC, Emmanueldmlr commented
@codiejay, why don't you want to use SVGs instead of .png?

2022-11-07 08:44 UTC, Emmanueldmlr requested changes

2022-11-07 08:44 UTC, Emmanueldmlr commented on src/components/Branding/BrandingAssets.tsx
> +      w={{ lg: '30%', base: '45%', md: '30%' }}
Do this instead
```suggestion
      w={{ base: '45%', md: '30%' }}
```

2022-11-07 08:44 UTC, Emmanueldmlr commented on src/pages/static/branding.tsx
> +      <Box maxW={{ base: '90%', xl: '90%', '2xl': '1280px' }} mx="auto">
do this instead
```suggestion
      <Box maxW={{ base: '90%', '2xl': '1280px' }} mx="auto">
```

2022-11-07 08:47 UTC, Emmanueldmlr commented
@codiejay, kindly add the link to the branding page to the PR so I can check the page out

2022-11-07 15:47 UTC, Emmanueldmlr approved these changes

2022-11-07 15:47 UTC, Emmanueldmlr commented on src/pages/static/branding.tsx
> +    <Box bg="#E2E8F0" _dark={{ backgroundColor: 'tetiaryDark' }} pb={20}>
You missed out the color code here.

2022-11-07 16:12 UTC, merged

2022-11-07 16:14 UTC, kesar commented
this is not linked from any menu? I guess it should be in footer and perhaps navbar under learn section