Feat/edit page
EveripediaNetwork/ep-ui pull request #94
Opened 2022-03-25 22:58 UTC by JustinCast

# PR title goes here

_PR description goes here_

## How should this be tested?

1. Step one
2. Step two
3. ...

## Notes or observations

_jot down something here_

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/ISSUE_NUMBER_GOES_HERE

2022-03-29 08:02 UTC, kesar commented on src/components/Elements/Dropzone/Dropzone.tsx
> +      setPaths([`https://ipfs.everipedia.org/ipfs/${initialImage}`])
ipfs url has a config value I think (if not pls add it)

2022-03-29 08:04 UTC, kesar commented on src/pages/_app.tsx
> +            <ImageProvider>
shouldnt this provider be at wiki create page level? I dont see any other use case outside of that scope

2022-03-29 08:06 UTC, kesar requested changes
two small changes, besides that it looks good

2022-03-30 18:47 UTC, JustinCast commented on src/pages/_app.tsx
> +            <ImageProvider>
> shouldnt this provider be at wiki create page level? I dont see any other use case outside of that scope

I had to include the image provider in the _app.tsx file, since in the nested component wasn't working

2022-03-31 03:15 UTC, merged