Iterations on Branding Page
EveripediaNetwork/ep-ui pull request #942
Opened 2022-11-08 20:05 UTC by codiejay

- [ ] Add "Branding" item to footer links. 
- [ ] Add new logos and update sections. 

closes https://github.com/EveripediaNetwork/issues/issues/871

2022-11-09 12:58 UTC, Simplypheyie96 requested changes
new sections looks good
one thing i wanted to point out that i totally forgot about is the quotes section. The texts have a bigger font size in the design. so it shouldn't be the same as the others.
![image](https://user-images.githubusercontent.com/99387231/200835910-1a4fed2b-042b-4832-8bd5-16430fbf0992.png)
Then i also thing that clicking outside the boxes should revert the download options to it's original state
![image](https://user-images.githubusercontent.com/99387231/200836554-9928b4b0-7e78-4d75-a16b-8b6d3038d4ed.png)

spacing between the words are a bit much on mobile and tab
![image](https://user-images.githubusercontent.com/99387231/200837007-fa4637d3-0b9e-4c3e-a748-b2aa0b41f0ab.png)

2022-11-09 13:12 UTC, kesar commented
> Then i also thing that clicking outside the boxes should revert the download options to it's original state

I would also suggest make them look like buttons if they are buttons. We need to train users to understand what buttons are in our site and use them across every single clickable interaction that will produce an effect.

current design looks like a text, not even a link. (a link should be pink w underline effect on hover, and it would be used if you are navigating to a page / url, in this case you are downloading a file)


corners in main image are not rounded like everywhere else. We should keep coherence and avoid squared corners if we use rounded.

![image](https://user-images.githubusercontent.com/1288106/200838691-5c71a839-ab62-4106-adbd-10e4cc46794c.png)

2022-11-09 13:15 UTC, codiejay commented
Fixing these issues now. 
@Simplypheyie96 will you go on to update the design with the new linking UI @kesar is suggesting?

2022-11-09 13:19 UTC, Simplypheyie96 commented
corners are rounded in the design . for the download button on the page, i felt it would be too colorful having everything in pink since the page itself is so colorful. so i added the text as black with a logo to indicate the download but i'll update that now

2022-11-09 13:35 UTC, kesar commented
> corners are rounded in the design . for the download button on the page, i felt it would be too colorful having everything in pink since the page itself is so colorful. so i added the text as black with a logo to indicate the download but i'll update that now
> 
> 

oh i see. we could overlay everything else grey if thats the issue, or as middle point we could try a design w white buttons that i think we have some in other pages. 

up to you, its not a big issue 👍👍

2022-11-09 13:45 UTC, Simplypheyie96 commented
> > corners are rounded in the design . for the download button on the page, i felt it would be too colorful having everything in pink since the page itself is so colorful. so i added the text as black with a logo to indicate the download but i'll update that now
> > 
> > 
> 
> oh i see. we could overlay everything else grey if thats the issue, or as middle point we could try a design w white buttons that i think we have some in other pages. 
> 
> up to you, its not a big issue 👍👍

an idea that came to me now is to just remove the download text or put them inside the boxes themselves such that a click in the box will show the options to download in svg or png.

2022-11-09 15:19 UTC, Simplypheyie96 commented
i used pink icons for the white backgrounds and white icons for the rest of the page due to contrast issues. I think it looks neater now compared to before. @kesar @codiejay 
![image](https://user-images.githubusercontent.com/99387231/200869199-e925de00-364e-4c44-bbe1-5d65789c11ec.png)

2022-11-10 16:20 UTC, Simplypheyie96 requested changes
-change color of download icons to brand color (pink)/ take note of color find dark mode
- The text here on the quotes should have a bigger font size compared to the other texts.
<img width="965" alt="image" src="https://user-images.githubusercontent.com/99387231/201148630-fa7fab64-b968-4e12-9218-92cd4212b3b4.png">
then increase spacings between hero and the quotes, then the quotes section and the first sub heading
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/99387231/201149841-2704f1a2-0b0f-421e-885d-f2b2a1933b2f.png">
- these texts should also be in pink. check figma
<img width="429" alt="image" src="https://user-images.githubusercontent.com/99387231/201150331-c56f0869-7880-4569-bfc5-fb3cc27164fe.png">

2022-11-10 18:16 UTC, Simplypheyie96 commented
you missed out the last sentence and the 3rd sentence is duplicated @codiejay 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/99387231/201174752-9e58e361-3980-4922-bdc2-bb5ce9197735.png">

2022-11-11 11:05 UTC, Simplypheyie96 requested changes
This should be gray700 in dark mode
<img width="448" alt="image" src="https://user-images.githubusercontent.com/99387231/201323657-65859eff-a0d1-4014-9722-7cf02357bdbd.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/99387231/201325260-deab48d3-eeaf-4e9b-b302-4d705351a28a.png">
there should be more spacing here
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/99387231/201325616-d26e199f-7419-469e-8bdb-d820e57ee575.png">

2022-11-11 11:55 UTC, Simplypheyie96 commented
@codiejay additional iterations according to the meeting yesterday is to switch the IQ logo only to the top and bring down the logo with texts. That is, switch sections. 
like this:
![image](https://user-images.githubusercontent.com/99387231/201335437-d9312ebe-ae94-4ca6-bcbc-9620815388b9.png)

2022-11-11 16:56 UTC, Simplypheyie96 approved these changes
well done. I think we can merge now

2022-11-12 00:43 UTC, Simplypheyie96 commented
You can totally merge now @codiejay

2022-11-12 02:05 UTC, Adebesin-Cell requested changes

2022-11-12 02:05 UTC, Adebesin-Cell commented on src/pages/static/branding.tsx
> +      bg="tetiaryGray"
Use semantic tokens.

2022-11-12 02:05 UTC, Adebesin-Cell commented on src/components/Branding/BrandingAssets.tsx
> +            m={{ base: '0', lg: '2', md: '2' }}
```suggestion
            m={{ base: '0', md: '2' }}
```

2022-11-12 02:05 UTC, Adebesin-Cell commented on src/components/Branding/BrandingAssets.tsx
> +            transform={{ base: 'scale(0.5)', lg: 'scale(1)', md: 'scale(1)' }}
```suggestion
            transform={{ base: 'scale(0.5)', md: 'scale(1)' }}
```

2022-11-12 02:05 UTC, Adebesin-Cell commented on src/components/Branding/BrandingAssetDownloadBttn.tsx
> +          color="brand.500"
Use semantic tokens.

2022-11-12 16:01 UTC, Adebesin-Cell approved these changes
Nice @codiejay.

2022-11-12 16:03 UTC, merged